// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

declare var exports: any;
const __config = new pulumi.Config("langfuse");

/**
 * Admin API key. Only needed when managing organizations. Can also come from LANGFUSE_ADMIN_KEY.
 */
export declare const adminApiKey: string | undefined;
Object.defineProperty(exports, "adminApiKey", {
    get() {
        return __config.get("adminApiKey");
    },
    enumerable: true,
});

/**
 * Base URI of the Langfuse instance (defaults to https://app.langfuse.com).
 */
export declare const host: string | undefined;
Object.defineProperty(exports, "host", {
    get() {
        return __config.get("host");
    },
    enumerable: true,
});

/**
 * Hostname to verify the TLS certificate against, also sent as the SNI value. Set this when the instance is reached through a port forward or tunnel, where the host above (typically localhost) cannot match the certificate. Certificate verification remains enabled.
 */
export declare const tlsServerName: string | undefined;
Object.defineProperty(exports, "tlsServerName", {
    get() {
        return __config.get("tlsServerName");
    },
    enumerable: true,
});

