// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Immutable;

namespace Pulumi.Langfuse
{
    public static class Config
    {
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "IDE1006", Justification = 
        "Double underscore prefix used to avoid conflicts with variable names.")]
        private sealed class __Value<T>
        {
            private readonly Func<T> _getter;
            private T _value = default!;
            private bool _set;

            public __Value(Func<T> getter)
            {
                _getter = getter;
            }

            public T Get() => _set ? _value : _getter();

            public void Set(T value)
            {
                _value = value;
                _set = true;
            }
        }

        private static readonly global::Pulumi.Config __config = new global::Pulumi.Config("langfuse");

        private static readonly __Value<string?> _adminApiKey = new __Value<string?>(() => __config.Get("adminApiKey"));
        /// <summary>
        /// Admin API key. Only needed when managing organizations. Can also come from LANGFUSE_ADMIN_KEY.
        /// </summary>
        public static string? AdminApiKey
        {
            get => _adminApiKey.Get();
            set => _adminApiKey.Set(value);
        }

        private static readonly __Value<string?> _host = new __Value<string?>(() => __config.Get("host"));
        /// <summary>
        /// Base URI of the Langfuse instance (defaults to https://app.langfuse.com).
        /// </summary>
        public static string? Host
        {
            get => _host.Get();
            set => _host.Set(value);
        }

        private static readonly __Value<string?> _tlsServerName = new __Value<string?>(() => __config.Get("tlsServerName"));
        /// <summary>
        /// Hostname to verify the TLS certificate against, also sent as the SNI value. Set this when the instance is reached through a port forward or tunnel, where the host above (typically localhost) cannot match the certificate. Certificate verification remains enabled.
        /// </summary>
        public static string? TlsServerName
        {
            get => _tlsServerName.Get();
            set => _tlsServerName.Set(value);
        }

    }
}
