# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = ['LlmConnectionArgs', 'LlmConnection']

@pulumi.input_type
class LlmConnectionArgs:
    def __init__(__self__, *,
                 adapter: pulumi.Input[_builtins.str],
                 project_public_key: pulumi.Input[_builtins.str],
                 project_secret_key: pulumi.Input[_builtins.str],
                 provider_name: pulumi.Input[_builtins.str],
                 secret_key: pulumi.Input[_builtins.str],
                 base_url: pulumi.Input[Optional[_builtins.str]] = None,
                 config: pulumi.Input[Optional[_builtins.str]] = None,
                 custom_models: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 extra_headers: pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 with_default_models: pulumi.Input[Optional[_builtins.bool]] = None):
        """
        The set of arguments for constructing a LlmConnection resource.

        :param pulumi.Input[_builtins.str] adapter: The LLM service type. Valid values: anthropic, openai, azure, bedrock, google-vertex-ai, google-ai-studio.
        :param pulumi.Input[_builtins.str] project_public_key: The project public key used to authenticate API calls.
        :param pulumi.Input[_builtins.str] project_secret_key: The project secret key used to authenticate API calls.
        :param pulumi.Input[_builtins.str] provider_name: The unique name identifying this LLM connection within the project. Changing this value destroys and recreates the resource, as the provider name is the upsert key.
        :param pulumi.Input[_builtins.str] secret_key: The API authentication key for the LLM provider.
        :param pulumi.Input[_builtins.str] base_url: Optional base URL override for the LLM provider API.
        :param pulumi.Input[_builtins.str] config: Adapter-specific configuration as a JSON string. Required for bedrock (`{"region": "<aws-region>"}`), optional for openai (`{"useResponsesApi": <bool>}`) and google-vertex-ai (`{"location": "<gcp-location>"}`), and unsupported for other adapters. Computed, because the API returns any config the connection holds and offers no way to unset one.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] custom_models: Optional list of custom model identifiers.
        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]] extra_headers: Optional map of additional HTTP headers for LLM API requests.
        :param pulumi.Input[_builtins.bool] with_default_models: Whether to include default models. Defaults to true if not set.
        """
        pulumi.set(__self__, "adapter", adapter)
        pulumi.set(__self__, "project_public_key", project_public_key)
        pulumi.set(__self__, "project_secret_key", project_secret_key)
        pulumi.set(__self__, "provider_name", provider_name)
        pulumi.set(__self__, "secret_key", secret_key)
        if base_url is not None:
            pulumi.set(__self__, "base_url", base_url)
        if config is not None:
            pulumi.set(__self__, "config", config)
        if custom_models is not None:
            pulumi.set(__self__, "custom_models", custom_models)
        if extra_headers is not None:
            pulumi.set(__self__, "extra_headers", extra_headers)
        if with_default_models is not None:
            pulumi.set(__self__, "with_default_models", with_default_models)

    @_builtins.property
    @pulumi.getter
    def adapter(self) -> pulumi.Input[_builtins.str]:
        """
        The LLM service type. Valid values: anthropic, openai, azure, bedrock, google-vertex-ai, google-ai-studio.
        """
        return pulumi.get(self, "adapter")

    @adapter.setter
    def adapter(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "adapter", value)

    @_builtins.property
    @pulumi.getter(name="projectPublicKey")
    def project_public_key(self) -> pulumi.Input[_builtins.str]:
        """
        The project public key used to authenticate API calls.
        """
        return pulumi.get(self, "project_public_key")

    @project_public_key.setter
    def project_public_key(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "project_public_key", value)

    @_builtins.property
    @pulumi.getter(name="projectSecretKey")
    def project_secret_key(self) -> pulumi.Input[_builtins.str]:
        """
        The project secret key used to authenticate API calls.
        """
        return pulumi.get(self, "project_secret_key")

    @project_secret_key.setter
    def project_secret_key(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "project_secret_key", value)

    @_builtins.property
    @pulumi.getter(name="providerName")
    def provider_name(self) -> pulumi.Input[_builtins.str]:
        """
        The unique name identifying this LLM connection within the project. Changing this value destroys and recreates the resource, as the provider name is the upsert key.
        """
        return pulumi.get(self, "provider_name")

    @provider_name.setter
    def provider_name(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "provider_name", value)

    @_builtins.property
    @pulumi.getter(name="secretKey")
    def secret_key(self) -> pulumi.Input[_builtins.str]:
        """
        The API authentication key for the LLM provider.
        """
        return pulumi.get(self, "secret_key")

    @secret_key.setter
    def secret_key(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "secret_key", value)

    @_builtins.property
    @pulumi.getter(name="baseUrl")
    def base_url(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Optional base URL override for the LLM provider API.
        """
        return pulumi.get(self, "base_url")

    @base_url.setter
    def base_url(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "base_url", value)

    @_builtins.property
    @pulumi.getter
    def config(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Adapter-specific configuration as a JSON string. Required for bedrock (`{"region": "<aws-region>"}`), optional for openai (`{"useResponsesApi": <bool>}`) and google-vertex-ai (`{"location": "<gcp-location>"}`), and unsupported for other adapters. Computed, because the API returns any config the connection holds and offers no way to unset one.
        """
        return pulumi.get(self, "config")

    @config.setter
    def config(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "config", value)

    @_builtins.property
    @pulumi.getter(name="customModels")
    def custom_models(self) -> pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        Optional list of custom model identifiers.
        """
        return pulumi.get(self, "custom_models")

    @custom_models.setter
    def custom_models(self, value: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "custom_models", value)

    @_builtins.property
    @pulumi.getter(name="extraHeaders")
    def extra_headers(self) -> pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]]:
        """
        Optional map of additional HTTP headers for LLM API requests.
        """
        return pulumi.get(self, "extra_headers")

    @extra_headers.setter
    def extra_headers(self, value: pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "extra_headers", value)

    @_builtins.property
    @pulumi.getter(name="withDefaultModels")
    def with_default_models(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        Whether to include default models. Defaults to true if not set.
        """
        return pulumi.get(self, "with_default_models")

    @with_default_models.setter
    def with_default_models(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "with_default_models", value)


@pulumi.input_type
class _LlmConnectionState:
    def __init__(__self__, *,
                 adapter: pulumi.Input[Optional[_builtins.str]] = None,
                 base_url: pulumi.Input[Optional[_builtins.str]] = None,
                 config: pulumi.Input[Optional[_builtins.str]] = None,
                 custom_models: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 extra_headers: pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 project_public_key: pulumi.Input[Optional[_builtins.str]] = None,
                 project_secret_key: pulumi.Input[Optional[_builtins.str]] = None,
                 provider_name: pulumi.Input[Optional[_builtins.str]] = None,
                 secret_key: pulumi.Input[Optional[_builtins.str]] = None,
                 with_default_models: pulumi.Input[Optional[_builtins.bool]] = None):
        """
        Input properties used for looking up and filtering LlmConnection resources.

        :param pulumi.Input[_builtins.str] adapter: The LLM service type. Valid values: anthropic, openai, azure, bedrock, google-vertex-ai, google-ai-studio.
        :param pulumi.Input[_builtins.str] base_url: Optional base URL override for the LLM provider API.
        :param pulumi.Input[_builtins.str] config: Adapter-specific configuration as a JSON string. Required for bedrock (`{"region": "<aws-region>"}`), optional for openai (`{"useResponsesApi": <bool>}`) and google-vertex-ai (`{"location": "<gcp-location>"}`), and unsupported for other adapters. Computed, because the API returns any config the connection holds and offers no way to unset one.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] custom_models: Optional list of custom model identifiers.
        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]] extra_headers: Optional map of additional HTTP headers for LLM API requests.
        :param pulumi.Input[_builtins.str] project_public_key: The project public key used to authenticate API calls.
        :param pulumi.Input[_builtins.str] project_secret_key: The project secret key used to authenticate API calls.
        :param pulumi.Input[_builtins.str] provider_name: The unique name identifying this LLM connection within the project. Changing this value destroys and recreates the resource, as the provider name is the upsert key.
        :param pulumi.Input[_builtins.str] secret_key: The API authentication key for the LLM provider.
        :param pulumi.Input[_builtins.bool] with_default_models: Whether to include default models. Defaults to true if not set.
        """
        if adapter is not None:
            pulumi.set(__self__, "adapter", adapter)
        if base_url is not None:
            pulumi.set(__self__, "base_url", base_url)
        if config is not None:
            pulumi.set(__self__, "config", config)
        if custom_models is not None:
            pulumi.set(__self__, "custom_models", custom_models)
        if extra_headers is not None:
            pulumi.set(__self__, "extra_headers", extra_headers)
        if project_public_key is not None:
            pulumi.set(__self__, "project_public_key", project_public_key)
        if project_secret_key is not None:
            pulumi.set(__self__, "project_secret_key", project_secret_key)
        if provider_name is not None:
            pulumi.set(__self__, "provider_name", provider_name)
        if secret_key is not None:
            pulumi.set(__self__, "secret_key", secret_key)
        if with_default_models is not None:
            pulumi.set(__self__, "with_default_models", with_default_models)

    @_builtins.property
    @pulumi.getter
    def adapter(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The LLM service type. Valid values: anthropic, openai, azure, bedrock, google-vertex-ai, google-ai-studio.
        """
        return pulumi.get(self, "adapter")

    @adapter.setter
    def adapter(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "adapter", value)

    @_builtins.property
    @pulumi.getter(name="baseUrl")
    def base_url(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Optional base URL override for the LLM provider API.
        """
        return pulumi.get(self, "base_url")

    @base_url.setter
    def base_url(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "base_url", value)

    @_builtins.property
    @pulumi.getter
    def config(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Adapter-specific configuration as a JSON string. Required for bedrock (`{"region": "<aws-region>"}`), optional for openai (`{"useResponsesApi": <bool>}`) and google-vertex-ai (`{"location": "<gcp-location>"}`), and unsupported for other adapters. Computed, because the API returns any config the connection holds and offers no way to unset one.
        """
        return pulumi.get(self, "config")

    @config.setter
    def config(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "config", value)

    @_builtins.property
    @pulumi.getter(name="customModels")
    def custom_models(self) -> pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        Optional list of custom model identifiers.
        """
        return pulumi.get(self, "custom_models")

    @custom_models.setter
    def custom_models(self, value: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "custom_models", value)

    @_builtins.property
    @pulumi.getter(name="extraHeaders")
    def extra_headers(self) -> pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]]:
        """
        Optional map of additional HTTP headers for LLM API requests.
        """
        return pulumi.get(self, "extra_headers")

    @extra_headers.setter
    def extra_headers(self, value: pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "extra_headers", value)

    @_builtins.property
    @pulumi.getter(name="projectPublicKey")
    def project_public_key(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The project public key used to authenticate API calls.
        """
        return pulumi.get(self, "project_public_key")

    @project_public_key.setter
    def project_public_key(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "project_public_key", value)

    @_builtins.property
    @pulumi.getter(name="projectSecretKey")
    def project_secret_key(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The project secret key used to authenticate API calls.
        """
        return pulumi.get(self, "project_secret_key")

    @project_secret_key.setter
    def project_secret_key(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "project_secret_key", value)

    @_builtins.property
    @pulumi.getter(name="providerName")
    def provider_name(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The unique name identifying this LLM connection within the project. Changing this value destroys and recreates the resource, as the provider name is the upsert key.
        """
        return pulumi.get(self, "provider_name")

    @provider_name.setter
    def provider_name(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "provider_name", value)

    @_builtins.property
    @pulumi.getter(name="secretKey")
    def secret_key(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The API authentication key for the LLM provider.
        """
        return pulumi.get(self, "secret_key")

    @secret_key.setter
    def secret_key(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "secret_key", value)

    @_builtins.property
    @pulumi.getter(name="withDefaultModels")
    def with_default_models(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        Whether to include default models. Defaults to true if not set.
        """
        return pulumi.get(self, "with_default_models")

    @with_default_models.setter
    def with_default_models(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "with_default_models", value)


@pulumi.type_token("langfuse:index/llmConnection:LlmConnection")
class LlmConnection(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 adapter: pulumi.Input[Optional[_builtins.str]] = None,
                 base_url: pulumi.Input[Optional[_builtins.str]] = None,
                 config: pulumi.Input[Optional[_builtins.str]] = None,
                 custom_models: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 extra_headers: pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 project_public_key: pulumi.Input[Optional[_builtins.str]] = None,
                 project_secret_key: pulumi.Input[Optional[_builtins.str]] = None,
                 provider_name: pulumi.Input[Optional[_builtins.str]] = None,
                 secret_key: pulumi.Input[Optional[_builtins.str]] = None,
                 with_default_models: pulumi.Input[Optional[_builtins.bool]] = None,
                 __props__=None):
        """
        Create a LlmConnection resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] adapter: The LLM service type. Valid values: anthropic, openai, azure, bedrock, google-vertex-ai, google-ai-studio.
        :param pulumi.Input[_builtins.str] base_url: Optional base URL override for the LLM provider API.
        :param pulumi.Input[_builtins.str] config: Adapter-specific configuration as a JSON string. Required for bedrock (`{"region": "<aws-region>"}`), optional for openai (`{"useResponsesApi": <bool>}`) and google-vertex-ai (`{"location": "<gcp-location>"}`), and unsupported for other adapters. Computed, because the API returns any config the connection holds and offers no way to unset one.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] custom_models: Optional list of custom model identifiers.
        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]] extra_headers: Optional map of additional HTTP headers for LLM API requests.
        :param pulumi.Input[_builtins.str] project_public_key: The project public key used to authenticate API calls.
        :param pulumi.Input[_builtins.str] project_secret_key: The project secret key used to authenticate API calls.
        :param pulumi.Input[_builtins.str] provider_name: The unique name identifying this LLM connection within the project. Changing this value destroys and recreates the resource, as the provider name is the upsert key.
        :param pulumi.Input[_builtins.str] secret_key: The API authentication key for the LLM provider.
        :param pulumi.Input[_builtins.bool] with_default_models: Whether to include default models. Defaults to true if not set.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: LlmConnectionArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Create a LlmConnection resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param LlmConnectionArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(LlmConnectionArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 adapter: pulumi.Input[Optional[_builtins.str]] = None,
                 base_url: pulumi.Input[Optional[_builtins.str]] = None,
                 config: pulumi.Input[Optional[_builtins.str]] = None,
                 custom_models: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 extra_headers: pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 project_public_key: pulumi.Input[Optional[_builtins.str]] = None,
                 project_secret_key: pulumi.Input[Optional[_builtins.str]] = None,
                 provider_name: pulumi.Input[Optional[_builtins.str]] = None,
                 secret_key: pulumi.Input[Optional[_builtins.str]] = None,
                 with_default_models: pulumi.Input[Optional[_builtins.bool]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = LlmConnectionArgs.__new__(LlmConnectionArgs)

            if adapter is None and not opts.urn:
                raise TypeError("Missing required property 'adapter'")
            __props__.__dict__["adapter"] = adapter
            __props__.__dict__["base_url"] = base_url
            __props__.__dict__["config"] = config
            __props__.__dict__["custom_models"] = custom_models
            __props__.__dict__["extra_headers"] = None if extra_headers is None else pulumi.Output.secret(extra_headers)
            if project_public_key is None and not opts.urn:
                raise TypeError("Missing required property 'project_public_key'")
            __props__.__dict__["project_public_key"] = None if project_public_key is None else pulumi.Output.secret(project_public_key)
            if project_secret_key is None and not opts.urn:
                raise TypeError("Missing required property 'project_secret_key'")
            __props__.__dict__["project_secret_key"] = None if project_secret_key is None else pulumi.Output.secret(project_secret_key)
            if provider_name is None and not opts.urn:
                raise TypeError("Missing required property 'provider_name'")
            __props__.__dict__["provider_name"] = provider_name
            if secret_key is None and not opts.urn:
                raise TypeError("Missing required property 'secret_key'")
            __props__.__dict__["secret_key"] = None if secret_key is None else pulumi.Output.secret(secret_key)
            __props__.__dict__["with_default_models"] = with_default_models
        secret_opts = pulumi.ResourceOptions(additional_secret_outputs=["extraHeaders", "projectPublicKey", "projectSecretKey", "secretKey"])
        opts = pulumi.ResourceOptions.merge(opts, secret_opts)
        super(LlmConnection, __self__).__init__(
            'langfuse:index/llmConnection:LlmConnection',
            resource_name,
            __props__,
            opts,
            package_ref=_utilities.get_package())

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            adapter: pulumi.Input[Optional[_builtins.str]] = None,
            base_url: pulumi.Input[Optional[_builtins.str]] = None,
            config: pulumi.Input[Optional[_builtins.str]] = None,
            custom_models: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
            extra_headers: pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
            project_public_key: pulumi.Input[Optional[_builtins.str]] = None,
            project_secret_key: pulumi.Input[Optional[_builtins.str]] = None,
            provider_name: pulumi.Input[Optional[_builtins.str]] = None,
            secret_key: pulumi.Input[Optional[_builtins.str]] = None,
            with_default_models: pulumi.Input[Optional[_builtins.bool]] = None) -> 'LlmConnection':
        """
        Get an existing LlmConnection resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] adapter: The LLM service type. Valid values: anthropic, openai, azure, bedrock, google-vertex-ai, google-ai-studio.
        :param pulumi.Input[_builtins.str] base_url: Optional base URL override for the LLM provider API.
        :param pulumi.Input[_builtins.str] config: Adapter-specific configuration as a JSON string. Required for bedrock (`{"region": "<aws-region>"}`), optional for openai (`{"useResponsesApi": <bool>}`) and google-vertex-ai (`{"location": "<gcp-location>"}`), and unsupported for other adapters. Computed, because the API returns any config the connection holds and offers no way to unset one.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] custom_models: Optional list of custom model identifiers.
        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]] extra_headers: Optional map of additional HTTP headers for LLM API requests.
        :param pulumi.Input[_builtins.str] project_public_key: The project public key used to authenticate API calls.
        :param pulumi.Input[_builtins.str] project_secret_key: The project secret key used to authenticate API calls.
        :param pulumi.Input[_builtins.str] provider_name: The unique name identifying this LLM connection within the project. Changing this value destroys and recreates the resource, as the provider name is the upsert key.
        :param pulumi.Input[_builtins.str] secret_key: The API authentication key for the LLM provider.
        :param pulumi.Input[_builtins.bool] with_default_models: Whether to include default models. Defaults to true if not set.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _LlmConnectionState.__new__(_LlmConnectionState)

        __props__.__dict__["adapter"] = adapter
        __props__.__dict__["base_url"] = base_url
        __props__.__dict__["config"] = config
        __props__.__dict__["custom_models"] = custom_models
        __props__.__dict__["extra_headers"] = extra_headers
        __props__.__dict__["project_public_key"] = project_public_key
        __props__.__dict__["project_secret_key"] = project_secret_key
        __props__.__dict__["provider_name"] = provider_name
        __props__.__dict__["secret_key"] = secret_key
        __props__.__dict__["with_default_models"] = with_default_models
        return LlmConnection(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter
    def adapter(self) -> pulumi.Output[_builtins.str]:
        """
        The LLM service type. Valid values: anthropic, openai, azure, bedrock, google-vertex-ai, google-ai-studio.
        """
        return pulumi.get(self, "adapter")

    @_builtins.property
    @pulumi.getter(name="baseUrl")
    def base_url(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Optional base URL override for the LLM provider API.
        """
        return pulumi.get(self, "base_url")

    @_builtins.property
    @pulumi.getter
    def config(self) -> pulumi.Output[_builtins.str]:
        """
        Adapter-specific configuration as a JSON string. Required for bedrock (`{"region": "<aws-region>"}`), optional for openai (`{"useResponsesApi": <bool>}`) and google-vertex-ai (`{"location": "<gcp-location>"}`), and unsupported for other adapters. Computed, because the API returns any config the connection holds and offers no way to unset one.
        """
        return pulumi.get(self, "config")

    @_builtins.property
    @pulumi.getter(name="customModels")
    def custom_models(self) -> pulumi.Output[Optional[Sequence[_builtins.str]]]:
        """
        Optional list of custom model identifiers.
        """
        return pulumi.get(self, "custom_models")

    @_builtins.property
    @pulumi.getter(name="extraHeaders")
    def extra_headers(self) -> pulumi.Output[Optional[Mapping[str, _builtins.str]]]:
        """
        Optional map of additional HTTP headers for LLM API requests.
        """
        return pulumi.get(self, "extra_headers")

    @_builtins.property
    @pulumi.getter(name="projectPublicKey")
    def project_public_key(self) -> pulumi.Output[_builtins.str]:
        """
        The project public key used to authenticate API calls.
        """
        return pulumi.get(self, "project_public_key")

    @_builtins.property
    @pulumi.getter(name="projectSecretKey")
    def project_secret_key(self) -> pulumi.Output[_builtins.str]:
        """
        The project secret key used to authenticate API calls.
        """
        return pulumi.get(self, "project_secret_key")

    @_builtins.property
    @pulumi.getter(name="providerName")
    def provider_name(self) -> pulumi.Output[_builtins.str]:
        """
        The unique name identifying this LLM connection within the project. Changing this value destroys and recreates the resource, as the provider name is the upsert key.
        """
        return pulumi.get(self, "provider_name")

    @_builtins.property
    @pulumi.getter(name="secretKey")
    def secret_key(self) -> pulumi.Output[_builtins.str]:
        """
        The API authentication key for the LLM provider.
        """
        return pulumi.get(self, "secret_key")

    @_builtins.property
    @pulumi.getter(name="withDefaultModels")
    def with_default_models(self) -> pulumi.Output[_builtins.bool]:
        """
        Whether to include default models. Defaults to true if not set.
        """
        return pulumi.get(self, "with_default_models")

