# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = ['OrganizationApiKeyArgs', 'OrganizationApiKey']

@pulumi.input_type
class OrganizationApiKeyArgs:
    def __init__(__self__, *,
                 organization_id: pulumi.Input[_builtins.str]):
        """
        The set of arguments for constructing a OrganizationApiKey resource.

        :param pulumi.Input[_builtins.str] organization_id: The Langfuse organization the key belongs to.
        """
        pulumi.set(__self__, "organization_id", organization_id)

    @_builtins.property
    @pulumi.getter(name="organizationId")
    def organization_id(self) -> pulumi.Input[_builtins.str]:
        """
        The Langfuse organization the key belongs to.
        """
        return pulumi.get(self, "organization_id")

    @organization_id.setter
    def organization_id(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "organization_id", value)


@pulumi.input_type
class _OrganizationApiKeyState:
    def __init__(__self__, *,
                 organization_id: pulumi.Input[Optional[_builtins.str]] = None,
                 public_key: pulumi.Input[Optional[_builtins.str]] = None,
                 secret_key: pulumi.Input[Optional[_builtins.str]] = None):
        """
        Input properties used for looking up and filtering OrganizationApiKey resources.

        :param pulumi.Input[_builtins.str] organization_id: The Langfuse organization the key belongs to.
        :param pulumi.Input[_builtins.str] public_key: The public value of the API key (only returned at creation time).
        :param pulumi.Input[_builtins.str] secret_key: The secret value of the API key (only returned at creation time).
        """
        if organization_id is not None:
            pulumi.set(__self__, "organization_id", organization_id)
        if public_key is not None:
            pulumi.set(__self__, "public_key", public_key)
        if secret_key is not None:
            pulumi.set(__self__, "secret_key", secret_key)

    @_builtins.property
    @pulumi.getter(name="organizationId")
    def organization_id(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The Langfuse organization the key belongs to.
        """
        return pulumi.get(self, "organization_id")

    @organization_id.setter
    def organization_id(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "organization_id", value)

    @_builtins.property
    @pulumi.getter(name="publicKey")
    def public_key(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The public value of the API key (only returned at creation time).
        """
        return pulumi.get(self, "public_key")

    @public_key.setter
    def public_key(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "public_key", value)

    @_builtins.property
    @pulumi.getter(name="secretKey")
    def secret_key(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The secret value of the API key (only returned at creation time).
        """
        return pulumi.get(self, "secret_key")

    @secret_key.setter
    def secret_key(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "secret_key", value)


@pulumi.type_token("langfuse:index/organizationApiKey:OrganizationApiKey")
class OrganizationApiKey(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 organization_id: pulumi.Input[Optional[_builtins.str]] = None,
                 __props__=None):
        """
        Create a OrganizationApiKey resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] organization_id: The Langfuse organization the key belongs to.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: OrganizationApiKeyArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Create a OrganizationApiKey resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param OrganizationApiKeyArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(OrganizationApiKeyArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 organization_id: pulumi.Input[Optional[_builtins.str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = OrganizationApiKeyArgs.__new__(OrganizationApiKeyArgs)

            if organization_id is None and not opts.urn:
                raise TypeError("Missing required property 'organization_id'")
            __props__.__dict__["organization_id"] = organization_id
            __props__.__dict__["public_key"] = None
            __props__.__dict__["secret_key"] = None
        secret_opts = pulumi.ResourceOptions(additional_secret_outputs=["publicKey", "secretKey"])
        opts = pulumi.ResourceOptions.merge(opts, secret_opts)
        super(OrganizationApiKey, __self__).__init__(
            'langfuse:index/organizationApiKey:OrganizationApiKey',
            resource_name,
            __props__,
            opts,
            package_ref=_utilities.get_package())

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            organization_id: pulumi.Input[Optional[_builtins.str]] = None,
            public_key: pulumi.Input[Optional[_builtins.str]] = None,
            secret_key: pulumi.Input[Optional[_builtins.str]] = None) -> 'OrganizationApiKey':
        """
        Get an existing OrganizationApiKey resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] organization_id: The Langfuse organization the key belongs to.
        :param pulumi.Input[_builtins.str] public_key: The public value of the API key (only returned at creation time).
        :param pulumi.Input[_builtins.str] secret_key: The secret value of the API key (only returned at creation time).
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _OrganizationApiKeyState.__new__(_OrganizationApiKeyState)

        __props__.__dict__["organization_id"] = organization_id
        __props__.__dict__["public_key"] = public_key
        __props__.__dict__["secret_key"] = secret_key
        return OrganizationApiKey(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter(name="organizationId")
    def organization_id(self) -> pulumi.Output[_builtins.str]:
        """
        The Langfuse organization the key belongs to.
        """
        return pulumi.get(self, "organization_id")

    @_builtins.property
    @pulumi.getter(name="publicKey")
    def public_key(self) -> pulumi.Output[_builtins.str]:
        """
        The public value of the API key (only returned at creation time).
        """
        return pulumi.get(self, "public_key")

    @_builtins.property
    @pulumi.getter(name="secretKey")
    def secret_key(self) -> pulumi.Output[_builtins.str]:
        """
        The secret value of the API key (only returned at creation time).
        """
        return pulumi.get(self, "secret_key")

