# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = ['OrganizationMembershipArgs', 'OrganizationMembership']

@pulumi.input_type
class OrganizationMembershipArgs:
    def __init__(__self__, *,
                 email: pulumi.Input[_builtins.str],
                 organization_private_key: pulumi.Input[_builtins.str],
                 organization_public_key: pulumi.Input[_builtins.str],
                 role: pulumi.Input[_builtins.str]):
        """
        The set of arguments for constructing a OrganizationMembership resource.

        :param pulumi.Input[_builtins.str] email: The email address of the user to invite.
        :param pulumi.Input[_builtins.str] organization_private_key: Organization private key to authenticate the call.
        :param pulumi.Input[_builtins.str] organization_public_key: Organization public key to authenticate the call.
        :param pulumi.Input[_builtins.str] role: The role to assign to the user. Valid values are: ADMIN, MEMBER, VIEWER.
        """
        pulumi.set(__self__, "email", email)
        pulumi.set(__self__, "organization_private_key", organization_private_key)
        pulumi.set(__self__, "organization_public_key", organization_public_key)
        pulumi.set(__self__, "role", role)

    @_builtins.property
    @pulumi.getter
    def email(self) -> pulumi.Input[_builtins.str]:
        """
        The email address of the user to invite.
        """
        return pulumi.get(self, "email")

    @email.setter
    def email(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "email", value)

    @_builtins.property
    @pulumi.getter(name="organizationPrivateKey")
    def organization_private_key(self) -> pulumi.Input[_builtins.str]:
        """
        Organization private key to authenticate the call.
        """
        return pulumi.get(self, "organization_private_key")

    @organization_private_key.setter
    def organization_private_key(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "organization_private_key", value)

    @_builtins.property
    @pulumi.getter(name="organizationPublicKey")
    def organization_public_key(self) -> pulumi.Input[_builtins.str]:
        """
        Organization public key to authenticate the call.
        """
        return pulumi.get(self, "organization_public_key")

    @organization_public_key.setter
    def organization_public_key(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "organization_public_key", value)

    @_builtins.property
    @pulumi.getter
    def role(self) -> pulumi.Input[_builtins.str]:
        """
        The role to assign to the user. Valid values are: ADMIN, MEMBER, VIEWER.
        """
        return pulumi.get(self, "role")

    @role.setter
    def role(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "role", value)


@pulumi.input_type
class _OrganizationMembershipState:
    def __init__(__self__, *,
                 email: pulumi.Input[Optional[_builtins.str]] = None,
                 organization_private_key: pulumi.Input[Optional[_builtins.str]] = None,
                 organization_public_key: pulumi.Input[Optional[_builtins.str]] = None,
                 role: pulumi.Input[Optional[_builtins.str]] = None,
                 status: pulumi.Input[Optional[_builtins.str]] = None,
                 user_id: pulumi.Input[Optional[_builtins.str]] = None,
                 username: pulumi.Input[Optional[_builtins.str]] = None):
        """
        Input properties used for looking up and filtering OrganizationMembership resources.

        :param pulumi.Input[_builtins.str] email: The email address of the user to invite.
        :param pulumi.Input[_builtins.str] organization_private_key: Organization private key to authenticate the call.
        :param pulumi.Input[_builtins.str] organization_public_key: Organization public key to authenticate the call.
        :param pulumi.Input[_builtins.str] role: The role to assign to the user. Valid values are: ADMIN, MEMBER, VIEWER.
        :param pulumi.Input[_builtins.str] status: The status of the membership invitation.
        :param pulumi.Input[_builtins.str] user_id: The unique identifier of the user.
        :param pulumi.Input[_builtins.str] username: The username of the user.
        """
        if email is not None:
            pulumi.set(__self__, "email", email)
        if organization_private_key is not None:
            pulumi.set(__self__, "organization_private_key", organization_private_key)
        if organization_public_key is not None:
            pulumi.set(__self__, "organization_public_key", organization_public_key)
        if role is not None:
            pulumi.set(__self__, "role", role)
        if status is not None:
            pulumi.set(__self__, "status", status)
        if user_id is not None:
            pulumi.set(__self__, "user_id", user_id)
        if username is not None:
            pulumi.set(__self__, "username", username)

    @_builtins.property
    @pulumi.getter
    def email(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The email address of the user to invite.
        """
        return pulumi.get(self, "email")

    @email.setter
    def email(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "email", value)

    @_builtins.property
    @pulumi.getter(name="organizationPrivateKey")
    def organization_private_key(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Organization private key to authenticate the call.
        """
        return pulumi.get(self, "organization_private_key")

    @organization_private_key.setter
    def organization_private_key(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "organization_private_key", value)

    @_builtins.property
    @pulumi.getter(name="organizationPublicKey")
    def organization_public_key(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Organization public key to authenticate the call.
        """
        return pulumi.get(self, "organization_public_key")

    @organization_public_key.setter
    def organization_public_key(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "organization_public_key", value)

    @_builtins.property
    @pulumi.getter
    def role(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The role to assign to the user. Valid values are: ADMIN, MEMBER, VIEWER.
        """
        return pulumi.get(self, "role")

    @role.setter
    def role(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "role", value)

    @_builtins.property
    @pulumi.getter
    def status(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The status of the membership invitation.
        """
        return pulumi.get(self, "status")

    @status.setter
    def status(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "status", value)

    @_builtins.property
    @pulumi.getter(name="userId")
    def user_id(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The unique identifier of the user.
        """
        return pulumi.get(self, "user_id")

    @user_id.setter
    def user_id(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "user_id", value)

    @_builtins.property
    @pulumi.getter
    def username(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The username of the user.
        """
        return pulumi.get(self, "username")

    @username.setter
    def username(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "username", value)


@pulumi.type_token("langfuse:index/organizationMembership:OrganizationMembership")
class OrganizationMembership(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 email: pulumi.Input[Optional[_builtins.str]] = None,
                 organization_private_key: pulumi.Input[Optional[_builtins.str]] = None,
                 organization_public_key: pulumi.Input[Optional[_builtins.str]] = None,
                 role: pulumi.Input[Optional[_builtins.str]] = None,
                 __props__=None):
        """
        Create a OrganizationMembership resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] email: The email address of the user to invite.
        :param pulumi.Input[_builtins.str] organization_private_key: Organization private key to authenticate the call.
        :param pulumi.Input[_builtins.str] organization_public_key: Organization public key to authenticate the call.
        :param pulumi.Input[_builtins.str] role: The role to assign to the user. Valid values are: ADMIN, MEMBER, VIEWER.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: OrganizationMembershipArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Create a OrganizationMembership resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param OrganizationMembershipArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(OrganizationMembershipArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 email: pulumi.Input[Optional[_builtins.str]] = None,
                 organization_private_key: pulumi.Input[Optional[_builtins.str]] = None,
                 organization_public_key: pulumi.Input[Optional[_builtins.str]] = None,
                 role: pulumi.Input[Optional[_builtins.str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = OrganizationMembershipArgs.__new__(OrganizationMembershipArgs)

            if email is None and not opts.urn:
                raise TypeError("Missing required property 'email'")
            __props__.__dict__["email"] = email
            if organization_private_key is None and not opts.urn:
                raise TypeError("Missing required property 'organization_private_key'")
            __props__.__dict__["organization_private_key"] = None if organization_private_key is None else pulumi.Output.secret(organization_private_key)
            if organization_public_key is None and not opts.urn:
                raise TypeError("Missing required property 'organization_public_key'")
            __props__.__dict__["organization_public_key"] = None if organization_public_key is None else pulumi.Output.secret(organization_public_key)
            if role is None and not opts.urn:
                raise TypeError("Missing required property 'role'")
            __props__.__dict__["role"] = role
            __props__.__dict__["status"] = None
            __props__.__dict__["user_id"] = None
            __props__.__dict__["username"] = None
        secret_opts = pulumi.ResourceOptions(additional_secret_outputs=["organizationPrivateKey", "organizationPublicKey"])
        opts = pulumi.ResourceOptions.merge(opts, secret_opts)
        super(OrganizationMembership, __self__).__init__(
            'langfuse:index/organizationMembership:OrganizationMembership',
            resource_name,
            __props__,
            opts,
            package_ref=_utilities.get_package())

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            email: pulumi.Input[Optional[_builtins.str]] = None,
            organization_private_key: pulumi.Input[Optional[_builtins.str]] = None,
            organization_public_key: pulumi.Input[Optional[_builtins.str]] = None,
            role: pulumi.Input[Optional[_builtins.str]] = None,
            status: pulumi.Input[Optional[_builtins.str]] = None,
            user_id: pulumi.Input[Optional[_builtins.str]] = None,
            username: pulumi.Input[Optional[_builtins.str]] = None) -> 'OrganizationMembership':
        """
        Get an existing OrganizationMembership resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] email: The email address of the user to invite.
        :param pulumi.Input[_builtins.str] organization_private_key: Organization private key to authenticate the call.
        :param pulumi.Input[_builtins.str] organization_public_key: Organization public key to authenticate the call.
        :param pulumi.Input[_builtins.str] role: The role to assign to the user. Valid values are: ADMIN, MEMBER, VIEWER.
        :param pulumi.Input[_builtins.str] status: The status of the membership invitation.
        :param pulumi.Input[_builtins.str] user_id: The unique identifier of the user.
        :param pulumi.Input[_builtins.str] username: The username of the user.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _OrganizationMembershipState.__new__(_OrganizationMembershipState)

        __props__.__dict__["email"] = email
        __props__.__dict__["organization_private_key"] = organization_private_key
        __props__.__dict__["organization_public_key"] = organization_public_key
        __props__.__dict__["role"] = role
        __props__.__dict__["status"] = status
        __props__.__dict__["user_id"] = user_id
        __props__.__dict__["username"] = username
        return OrganizationMembership(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter
    def email(self) -> pulumi.Output[_builtins.str]:
        """
        The email address of the user to invite.
        """
        return pulumi.get(self, "email")

    @_builtins.property
    @pulumi.getter(name="organizationPrivateKey")
    def organization_private_key(self) -> pulumi.Output[_builtins.str]:
        """
        Organization private key to authenticate the call.
        """
        return pulumi.get(self, "organization_private_key")

    @_builtins.property
    @pulumi.getter(name="organizationPublicKey")
    def organization_public_key(self) -> pulumi.Output[_builtins.str]:
        """
        Organization public key to authenticate the call.
        """
        return pulumi.get(self, "organization_public_key")

    @_builtins.property
    @pulumi.getter
    def role(self) -> pulumi.Output[_builtins.str]:
        """
        The role to assign to the user. Valid values are: ADMIN, MEMBER, VIEWER.
        """
        return pulumi.get(self, "role")

    @_builtins.property
    @pulumi.getter
    def status(self) -> pulumi.Output[_builtins.str]:
        """
        The status of the membership invitation.
        """
        return pulumi.get(self, "status")

    @_builtins.property
    @pulumi.getter(name="userId")
    def user_id(self) -> pulumi.Output[_builtins.str]:
        """
        The unique identifier of the user.
        """
        return pulumi.get(self, "user_id")

    @_builtins.property
    @pulumi.getter
    def username(self) -> pulumi.Output[_builtins.str]:
        """
        The username of the user.
        """
        return pulumi.get(self, "username")

