# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = ['ProjectMembershipArgs', 'ProjectMembership']

@pulumi.input_type
class ProjectMembershipArgs:
    def __init__(__self__, *,
                 email: pulumi.Input[_builtins.str],
                 organization_private_key: pulumi.Input[_builtins.str],
                 organization_public_key: pulumi.Input[_builtins.str],
                 project_id: pulumi.Input[_builtins.str],
                 role: pulumi.Input[_builtins.str]):
        """
        The set of arguments for constructing a ProjectMembership resource.

        :param pulumi.Input[_builtins.str] email: The email address of the user to add to the project.
        :param pulumi.Input[_builtins.str] organization_private_key: Organization private key to authenticate the call.
        :param pulumi.Input[_builtins.str] organization_public_key: Organization public key to authenticate the call.
        :param pulumi.Input[_builtins.str] project_id: The ID of the project.
        :param pulumi.Input[_builtins.str] role: The role to assign to the user. Valid values are: OWNER, ADMIN, MEMBER, VIEWER, NONE.
        """
        pulumi.set(__self__, "email", email)
        pulumi.set(__self__, "organization_private_key", organization_private_key)
        pulumi.set(__self__, "organization_public_key", organization_public_key)
        pulumi.set(__self__, "project_id", project_id)
        pulumi.set(__self__, "role", role)

    @_builtins.property
    @pulumi.getter
    def email(self) -> pulumi.Input[_builtins.str]:
        """
        The email address of the user to add to the project.
        """
        return pulumi.get(self, "email")

    @email.setter
    def email(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "email", value)

    @_builtins.property
    @pulumi.getter(name="organizationPrivateKey")
    def organization_private_key(self) -> pulumi.Input[_builtins.str]:
        """
        Organization private key to authenticate the call.
        """
        return pulumi.get(self, "organization_private_key")

    @organization_private_key.setter
    def organization_private_key(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "organization_private_key", value)

    @_builtins.property
    @pulumi.getter(name="organizationPublicKey")
    def organization_public_key(self) -> pulumi.Input[_builtins.str]:
        """
        Organization public key to authenticate the call.
        """
        return pulumi.get(self, "organization_public_key")

    @organization_public_key.setter
    def organization_public_key(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "organization_public_key", value)

    @_builtins.property
    @pulumi.getter(name="projectId")
    def project_id(self) -> pulumi.Input[_builtins.str]:
        """
        The ID of the project.
        """
        return pulumi.get(self, "project_id")

    @project_id.setter
    def project_id(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "project_id", value)

    @_builtins.property
    @pulumi.getter
    def role(self) -> pulumi.Input[_builtins.str]:
        """
        The role to assign to the user. Valid values are: OWNER, ADMIN, MEMBER, VIEWER, NONE.
        """
        return pulumi.get(self, "role")

    @role.setter
    def role(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "role", value)


@pulumi.input_type
class _ProjectMembershipState:
    def __init__(__self__, *,
                 email: pulumi.Input[Optional[_builtins.str]] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 organization_private_key: pulumi.Input[Optional[_builtins.str]] = None,
                 organization_public_key: pulumi.Input[Optional[_builtins.str]] = None,
                 project_id: pulumi.Input[Optional[_builtins.str]] = None,
                 role: pulumi.Input[Optional[_builtins.str]] = None,
                 user_id: pulumi.Input[Optional[_builtins.str]] = None):
        """
        Input properties used for looking up and filtering ProjectMembership resources.

        :param pulumi.Input[_builtins.str] email: The email address of the user to add to the project.
        :param pulumi.Input[_builtins.str] name: The name of the user.
        :param pulumi.Input[_builtins.str] organization_private_key: Organization private key to authenticate the call.
        :param pulumi.Input[_builtins.str] organization_public_key: Organization public key to authenticate the call.
        :param pulumi.Input[_builtins.str] project_id: The ID of the project.
        :param pulumi.Input[_builtins.str] role: The role to assign to the user. Valid values are: OWNER, ADMIN, MEMBER, VIEWER, NONE.
        :param pulumi.Input[_builtins.str] user_id: The unique identifier of the user.
        """
        if email is not None:
            pulumi.set(__self__, "email", email)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if organization_private_key is not None:
            pulumi.set(__self__, "organization_private_key", organization_private_key)
        if organization_public_key is not None:
            pulumi.set(__self__, "organization_public_key", organization_public_key)
        if project_id is not None:
            pulumi.set(__self__, "project_id", project_id)
        if role is not None:
            pulumi.set(__self__, "role", role)
        if user_id is not None:
            pulumi.set(__self__, "user_id", user_id)

    @_builtins.property
    @pulumi.getter
    def email(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The email address of the user to add to the project.
        """
        return pulumi.get(self, "email")

    @email.setter
    def email(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "email", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The name of the user.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter(name="organizationPrivateKey")
    def organization_private_key(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Organization private key to authenticate the call.
        """
        return pulumi.get(self, "organization_private_key")

    @organization_private_key.setter
    def organization_private_key(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "organization_private_key", value)

    @_builtins.property
    @pulumi.getter(name="organizationPublicKey")
    def organization_public_key(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Organization public key to authenticate the call.
        """
        return pulumi.get(self, "organization_public_key")

    @organization_public_key.setter
    def organization_public_key(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "organization_public_key", value)

    @_builtins.property
    @pulumi.getter(name="projectId")
    def project_id(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The ID of the project.
        """
        return pulumi.get(self, "project_id")

    @project_id.setter
    def project_id(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "project_id", value)

    @_builtins.property
    @pulumi.getter
    def role(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The role to assign to the user. Valid values are: OWNER, ADMIN, MEMBER, VIEWER, NONE.
        """
        return pulumi.get(self, "role")

    @role.setter
    def role(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "role", value)

    @_builtins.property
    @pulumi.getter(name="userId")
    def user_id(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The unique identifier of the user.
        """
        return pulumi.get(self, "user_id")

    @user_id.setter
    def user_id(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "user_id", value)


@pulumi.type_token("langfuse:index/projectMembership:ProjectMembership")
class ProjectMembership(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 email: pulumi.Input[Optional[_builtins.str]] = None,
                 organization_private_key: pulumi.Input[Optional[_builtins.str]] = None,
                 organization_public_key: pulumi.Input[Optional[_builtins.str]] = None,
                 project_id: pulumi.Input[Optional[_builtins.str]] = None,
                 role: pulumi.Input[Optional[_builtins.str]] = None,
                 __props__=None):
        """
        Create a ProjectMembership resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] email: The email address of the user to add to the project.
        :param pulumi.Input[_builtins.str] organization_private_key: Organization private key to authenticate the call.
        :param pulumi.Input[_builtins.str] organization_public_key: Organization public key to authenticate the call.
        :param pulumi.Input[_builtins.str] project_id: The ID of the project.
        :param pulumi.Input[_builtins.str] role: The role to assign to the user. Valid values are: OWNER, ADMIN, MEMBER, VIEWER, NONE.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: ProjectMembershipArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Create a ProjectMembership resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param ProjectMembershipArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(ProjectMembershipArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 email: pulumi.Input[Optional[_builtins.str]] = None,
                 organization_private_key: pulumi.Input[Optional[_builtins.str]] = None,
                 organization_public_key: pulumi.Input[Optional[_builtins.str]] = None,
                 project_id: pulumi.Input[Optional[_builtins.str]] = None,
                 role: pulumi.Input[Optional[_builtins.str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = ProjectMembershipArgs.__new__(ProjectMembershipArgs)

            if email is None and not opts.urn:
                raise TypeError("Missing required property 'email'")
            __props__.__dict__["email"] = email
            if organization_private_key is None and not opts.urn:
                raise TypeError("Missing required property 'organization_private_key'")
            __props__.__dict__["organization_private_key"] = None if organization_private_key is None else pulumi.Output.secret(organization_private_key)
            if organization_public_key is None and not opts.urn:
                raise TypeError("Missing required property 'organization_public_key'")
            __props__.__dict__["organization_public_key"] = None if organization_public_key is None else pulumi.Output.secret(organization_public_key)
            if project_id is None and not opts.urn:
                raise TypeError("Missing required property 'project_id'")
            __props__.__dict__["project_id"] = project_id
            if role is None and not opts.urn:
                raise TypeError("Missing required property 'role'")
            __props__.__dict__["role"] = role
            __props__.__dict__["name"] = None
            __props__.__dict__["user_id"] = None
        secret_opts = pulumi.ResourceOptions(additional_secret_outputs=["organizationPrivateKey", "organizationPublicKey"])
        opts = pulumi.ResourceOptions.merge(opts, secret_opts)
        super(ProjectMembership, __self__).__init__(
            'langfuse:index/projectMembership:ProjectMembership',
            resource_name,
            __props__,
            opts,
            package_ref=_utilities.get_package())

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            email: pulumi.Input[Optional[_builtins.str]] = None,
            name: pulumi.Input[Optional[_builtins.str]] = None,
            organization_private_key: pulumi.Input[Optional[_builtins.str]] = None,
            organization_public_key: pulumi.Input[Optional[_builtins.str]] = None,
            project_id: pulumi.Input[Optional[_builtins.str]] = None,
            role: pulumi.Input[Optional[_builtins.str]] = None,
            user_id: pulumi.Input[Optional[_builtins.str]] = None) -> 'ProjectMembership':
        """
        Get an existing ProjectMembership resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] email: The email address of the user to add to the project.
        :param pulumi.Input[_builtins.str] name: The name of the user.
        :param pulumi.Input[_builtins.str] organization_private_key: Organization private key to authenticate the call.
        :param pulumi.Input[_builtins.str] organization_public_key: Organization public key to authenticate the call.
        :param pulumi.Input[_builtins.str] project_id: The ID of the project.
        :param pulumi.Input[_builtins.str] role: The role to assign to the user. Valid values are: OWNER, ADMIN, MEMBER, VIEWER, NONE.
        :param pulumi.Input[_builtins.str] user_id: The unique identifier of the user.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _ProjectMembershipState.__new__(_ProjectMembershipState)

        __props__.__dict__["email"] = email
        __props__.__dict__["name"] = name
        __props__.__dict__["organization_private_key"] = organization_private_key
        __props__.__dict__["organization_public_key"] = organization_public_key
        __props__.__dict__["project_id"] = project_id
        __props__.__dict__["role"] = role
        __props__.__dict__["user_id"] = user_id
        return ProjectMembership(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter
    def email(self) -> pulumi.Output[_builtins.str]:
        """
        The email address of the user to add to the project.
        """
        return pulumi.get(self, "email")

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Output[_builtins.str]:
        """
        The name of the user.
        """
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter(name="organizationPrivateKey")
    def organization_private_key(self) -> pulumi.Output[_builtins.str]:
        """
        Organization private key to authenticate the call.
        """
        return pulumi.get(self, "organization_private_key")

    @_builtins.property
    @pulumi.getter(name="organizationPublicKey")
    def organization_public_key(self) -> pulumi.Output[_builtins.str]:
        """
        Organization public key to authenticate the call.
        """
        return pulumi.get(self, "organization_public_key")

    @_builtins.property
    @pulumi.getter(name="projectId")
    def project_id(self) -> pulumi.Output[_builtins.str]:
        """
        The ID of the project.
        """
        return pulumi.get(self, "project_id")

    @_builtins.property
    @pulumi.getter
    def role(self) -> pulumi.Output[_builtins.str]:
        """
        The role to assign to the user. Valid values are: OWNER, ADMIN, MEMBER, VIEWER, NONE.
        """
        return pulumi.get(self, "role")

    @_builtins.property
    @pulumi.getter(name="userId")
    def user_id(self) -> pulumi.Output[_builtins.str]:
        """
        The unique identifier of the user.
        """
        return pulumi.get(self, "user_id")

