# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = ['ProjectArgs', 'Project']

@pulumi.input_type
class ProjectArgs:
    def __init__(__self__, *,
                 organization_id: pulumi.Input[_builtins.str],
                 organization_private_key: pulumi.Input[_builtins.str],
                 organization_public_key: pulumi.Input[_builtins.str],
                 metadata: pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 retention_days: pulumi.Input[Optional[_builtins.float]] = None):
        """
        The set of arguments for constructing a Project resource.

        :param pulumi.Input[_builtins.str] organization_id: The ID of the organization that owns this project.
        :param pulumi.Input[_builtins.str] organization_private_key: Organization private key to authenticate the call.
        :param pulumi.Input[_builtins.str] organization_public_key: Organization public key to authenticate the call.
        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]] metadata: Metadata for the project as key-value pairs.
        :param pulumi.Input[_builtins.str] name: The display name of the project.
        :param pulumi.Input[_builtins.float] retention_days: The retention period for the project in days. If not set, or set with a value of 0, data will be stored indefinitely.
        """
        pulumi.set(__self__, "organization_id", organization_id)
        pulumi.set(__self__, "organization_private_key", organization_private_key)
        pulumi.set(__self__, "organization_public_key", organization_public_key)
        if metadata is not None:
            pulumi.set(__self__, "metadata", metadata)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if retention_days is not None:
            pulumi.set(__self__, "retention_days", retention_days)

    @_builtins.property
    @pulumi.getter(name="organizationId")
    def organization_id(self) -> pulumi.Input[_builtins.str]:
        """
        The ID of the organization that owns this project.
        """
        return pulumi.get(self, "organization_id")

    @organization_id.setter
    def organization_id(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "organization_id", value)

    @_builtins.property
    @pulumi.getter(name="organizationPrivateKey")
    def organization_private_key(self) -> pulumi.Input[_builtins.str]:
        """
        Organization private key to authenticate the call.
        """
        return pulumi.get(self, "organization_private_key")

    @organization_private_key.setter
    def organization_private_key(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "organization_private_key", value)

    @_builtins.property
    @pulumi.getter(name="organizationPublicKey")
    def organization_public_key(self) -> pulumi.Input[_builtins.str]:
        """
        Organization public key to authenticate the call.
        """
        return pulumi.get(self, "organization_public_key")

    @organization_public_key.setter
    def organization_public_key(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "organization_public_key", value)

    @_builtins.property
    @pulumi.getter
    def metadata(self) -> pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]]:
        """
        Metadata for the project as key-value pairs.
        """
        return pulumi.get(self, "metadata")

    @metadata.setter
    def metadata(self, value: pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "metadata", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The display name of the project.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter(name="retentionDays")
    def retention_days(self) -> pulumi.Input[Optional[_builtins.float]]:
        """
        The retention period for the project in days. If not set, or set with a value of 0, data will be stored indefinitely.
        """
        return pulumi.get(self, "retention_days")

    @retention_days.setter
    def retention_days(self, value: pulumi.Input[Optional[_builtins.float]]):
        pulumi.set(self, "retention_days", value)


@pulumi.input_type
class _ProjectState:
    def __init__(__self__, *,
                 metadata: pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 organization_id: pulumi.Input[Optional[_builtins.str]] = None,
                 organization_private_key: pulumi.Input[Optional[_builtins.str]] = None,
                 organization_public_key: pulumi.Input[Optional[_builtins.str]] = None,
                 retention_days: pulumi.Input[Optional[_builtins.float]] = None):
        """
        Input properties used for looking up and filtering Project resources.

        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]] metadata: Metadata for the project as key-value pairs.
        :param pulumi.Input[_builtins.str] name: The display name of the project.
        :param pulumi.Input[_builtins.str] organization_id: The ID of the organization that owns this project.
        :param pulumi.Input[_builtins.str] organization_private_key: Organization private key to authenticate the call.
        :param pulumi.Input[_builtins.str] organization_public_key: Organization public key to authenticate the call.
        :param pulumi.Input[_builtins.float] retention_days: The retention period for the project in days. If not set, or set with a value of 0, data will be stored indefinitely.
        """
        if metadata is not None:
            pulumi.set(__self__, "metadata", metadata)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if organization_id is not None:
            pulumi.set(__self__, "organization_id", organization_id)
        if organization_private_key is not None:
            pulumi.set(__self__, "organization_private_key", organization_private_key)
        if organization_public_key is not None:
            pulumi.set(__self__, "organization_public_key", organization_public_key)
        if retention_days is not None:
            pulumi.set(__self__, "retention_days", retention_days)

    @_builtins.property
    @pulumi.getter
    def metadata(self) -> pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]]:
        """
        Metadata for the project as key-value pairs.
        """
        return pulumi.get(self, "metadata")

    @metadata.setter
    def metadata(self, value: pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "metadata", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The display name of the project.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter(name="organizationId")
    def organization_id(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The ID of the organization that owns this project.
        """
        return pulumi.get(self, "organization_id")

    @organization_id.setter
    def organization_id(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "organization_id", value)

    @_builtins.property
    @pulumi.getter(name="organizationPrivateKey")
    def organization_private_key(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Organization private key to authenticate the call.
        """
        return pulumi.get(self, "organization_private_key")

    @organization_private_key.setter
    def organization_private_key(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "organization_private_key", value)

    @_builtins.property
    @pulumi.getter(name="organizationPublicKey")
    def organization_public_key(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Organization public key to authenticate the call.
        """
        return pulumi.get(self, "organization_public_key")

    @organization_public_key.setter
    def organization_public_key(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "organization_public_key", value)

    @_builtins.property
    @pulumi.getter(name="retentionDays")
    def retention_days(self) -> pulumi.Input[Optional[_builtins.float]]:
        """
        The retention period for the project in days. If not set, or set with a value of 0, data will be stored indefinitely.
        """
        return pulumi.get(self, "retention_days")

    @retention_days.setter
    def retention_days(self, value: pulumi.Input[Optional[_builtins.float]]):
        pulumi.set(self, "retention_days", value)


@pulumi.type_token("langfuse:index/project:Project")
class Project(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 metadata: pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 organization_id: pulumi.Input[Optional[_builtins.str]] = None,
                 organization_private_key: pulumi.Input[Optional[_builtins.str]] = None,
                 organization_public_key: pulumi.Input[Optional[_builtins.str]] = None,
                 retention_days: pulumi.Input[Optional[_builtins.float]] = None,
                 __props__=None):
        """
        Create a Project resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]] metadata: Metadata for the project as key-value pairs.
        :param pulumi.Input[_builtins.str] name: The display name of the project.
        :param pulumi.Input[_builtins.str] organization_id: The ID of the organization that owns this project.
        :param pulumi.Input[_builtins.str] organization_private_key: Organization private key to authenticate the call.
        :param pulumi.Input[_builtins.str] organization_public_key: Organization public key to authenticate the call.
        :param pulumi.Input[_builtins.float] retention_days: The retention period for the project in days. If not set, or set with a value of 0, data will be stored indefinitely.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: ProjectArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Create a Project resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param ProjectArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(ProjectArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 metadata: pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 organization_id: pulumi.Input[Optional[_builtins.str]] = None,
                 organization_private_key: pulumi.Input[Optional[_builtins.str]] = None,
                 organization_public_key: pulumi.Input[Optional[_builtins.str]] = None,
                 retention_days: pulumi.Input[Optional[_builtins.float]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = ProjectArgs.__new__(ProjectArgs)

            __props__.__dict__["metadata"] = metadata
            __props__.__dict__["name"] = name
            if organization_id is None and not opts.urn:
                raise TypeError("Missing required property 'organization_id'")
            __props__.__dict__["organization_id"] = organization_id
            if organization_private_key is None and not opts.urn:
                raise TypeError("Missing required property 'organization_private_key'")
            __props__.__dict__["organization_private_key"] = None if organization_private_key is None else pulumi.Output.secret(organization_private_key)
            if organization_public_key is None and not opts.urn:
                raise TypeError("Missing required property 'organization_public_key'")
            __props__.__dict__["organization_public_key"] = None if organization_public_key is None else pulumi.Output.secret(organization_public_key)
            __props__.__dict__["retention_days"] = retention_days
        secret_opts = pulumi.ResourceOptions(additional_secret_outputs=["organizationPrivateKey", "organizationPublicKey"])
        opts = pulumi.ResourceOptions.merge(opts, secret_opts)
        super(Project, __self__).__init__(
            'langfuse:index/project:Project',
            resource_name,
            __props__,
            opts,
            package_ref=_utilities.get_package())

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            metadata: pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
            name: pulumi.Input[Optional[_builtins.str]] = None,
            organization_id: pulumi.Input[Optional[_builtins.str]] = None,
            organization_private_key: pulumi.Input[Optional[_builtins.str]] = None,
            organization_public_key: pulumi.Input[Optional[_builtins.str]] = None,
            retention_days: pulumi.Input[Optional[_builtins.float]] = None) -> 'Project':
        """
        Get an existing Project resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]] metadata: Metadata for the project as key-value pairs.
        :param pulumi.Input[_builtins.str] name: The display name of the project.
        :param pulumi.Input[_builtins.str] organization_id: The ID of the organization that owns this project.
        :param pulumi.Input[_builtins.str] organization_private_key: Organization private key to authenticate the call.
        :param pulumi.Input[_builtins.str] organization_public_key: Organization public key to authenticate the call.
        :param pulumi.Input[_builtins.float] retention_days: The retention period for the project in days. If not set, or set with a value of 0, data will be stored indefinitely.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _ProjectState.__new__(_ProjectState)

        __props__.__dict__["metadata"] = metadata
        __props__.__dict__["name"] = name
        __props__.__dict__["organization_id"] = organization_id
        __props__.__dict__["organization_private_key"] = organization_private_key
        __props__.__dict__["organization_public_key"] = organization_public_key
        __props__.__dict__["retention_days"] = retention_days
        return Project(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter
    def metadata(self) -> pulumi.Output[Optional[Mapping[str, _builtins.str]]]:
        """
        Metadata for the project as key-value pairs.
        """
        return pulumi.get(self, "metadata")

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Output[_builtins.str]:
        """
        The display name of the project.
        """
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter(name="organizationId")
    def organization_id(self) -> pulumi.Output[_builtins.str]:
        """
        The ID of the organization that owns this project.
        """
        return pulumi.get(self, "organization_id")

    @_builtins.property
    @pulumi.getter(name="organizationPrivateKey")
    def organization_private_key(self) -> pulumi.Output[_builtins.str]:
        """
        Organization private key to authenticate the call.
        """
        return pulumi.get(self, "organization_private_key")

    @_builtins.property
    @pulumi.getter(name="organizationPublicKey")
    def organization_public_key(self) -> pulumi.Output[_builtins.str]:
        """
        Organization public key to authenticate the call.
        """
        return pulumi.get(self, "organization_public_key")

    @_builtins.property
    @pulumi.getter(name="retentionDays")
    def retention_days(self) -> pulumi.Output[_builtins.float]:
        """
        The retention period for the project in days. If not set, or set with a value of 0, data will be stored indefinitely.
        """
        return pulumi.get(self, "retention_days")

