# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = ['ProjectApiKeyArgs', 'ProjectApiKey']

@pulumi.input_type
class ProjectApiKeyArgs:
    def __init__(__self__, *,
                 organization_private_key: pulumi.Input[_builtins.str],
                 organization_public_key: pulumi.Input[_builtins.str],
                 project_id: pulumi.Input[_builtins.str],
                 note: pulumi.Input[Optional[_builtins.str]] = None):
        """
        The set of arguments for constructing a ProjectApiKey resource.

        :param pulumi.Input[_builtins.str] organization_private_key: Organization private key to authenticate the call.
        :param pulumi.Input[_builtins.str] organization_public_key: Organization public key to authenticate the call.
        :param pulumi.Input[_builtins.str] project_id: The ID of the project the key belongs to.
        :param pulumi.Input[_builtins.str] note: Optional note for the API key (POST /api/public/projects/{projectId}/apiKeys). Because the Langfuse public API only accepts a note at creation time, changing this attribute forces replacement: the old key is deleted and a new one is created (new id and credentials).
        """
        pulumi.set(__self__, "organization_private_key", organization_private_key)
        pulumi.set(__self__, "organization_public_key", organization_public_key)
        pulumi.set(__self__, "project_id", project_id)
        if note is not None:
            pulumi.set(__self__, "note", note)

    @_builtins.property
    @pulumi.getter(name="organizationPrivateKey")
    def organization_private_key(self) -> pulumi.Input[_builtins.str]:
        """
        Organization private key to authenticate the call.
        """
        return pulumi.get(self, "organization_private_key")

    @organization_private_key.setter
    def organization_private_key(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "organization_private_key", value)

    @_builtins.property
    @pulumi.getter(name="organizationPublicKey")
    def organization_public_key(self) -> pulumi.Input[_builtins.str]:
        """
        Organization public key to authenticate the call.
        """
        return pulumi.get(self, "organization_public_key")

    @organization_public_key.setter
    def organization_public_key(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "organization_public_key", value)

    @_builtins.property
    @pulumi.getter(name="projectId")
    def project_id(self) -> pulumi.Input[_builtins.str]:
        """
        The ID of the project the key belongs to.
        """
        return pulumi.get(self, "project_id")

    @project_id.setter
    def project_id(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "project_id", value)

    @_builtins.property
    @pulumi.getter
    def note(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Optional note for the API key (POST /api/public/projects/{projectId}/apiKeys). Because the Langfuse public API only accepts a note at creation time, changing this attribute forces replacement: the old key is deleted and a new one is created (new id and credentials).
        """
        return pulumi.get(self, "note")

    @note.setter
    def note(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "note", value)


@pulumi.input_type
class _ProjectApiKeyState:
    def __init__(__self__, *,
                 note: pulumi.Input[Optional[_builtins.str]] = None,
                 organization_private_key: pulumi.Input[Optional[_builtins.str]] = None,
                 organization_public_key: pulumi.Input[Optional[_builtins.str]] = None,
                 project_id: pulumi.Input[Optional[_builtins.str]] = None,
                 public_key: pulumi.Input[Optional[_builtins.str]] = None,
                 secret_key: pulumi.Input[Optional[_builtins.str]] = None):
        """
        Input properties used for looking up and filtering ProjectApiKey resources.

        :param pulumi.Input[_builtins.str] note: Optional note for the API key (POST /api/public/projects/{projectId}/apiKeys). Because the Langfuse public API only accepts a note at creation time, changing this attribute forces replacement: the old key is deleted and a new one is created (new id and credentials).
        :param pulumi.Input[_builtins.str] organization_private_key: Organization private key to authenticate the call.
        :param pulumi.Input[_builtins.str] organization_public_key: Organization public key to authenticate the call.
        :param pulumi.Input[_builtins.str] project_id: The ID of the project the key belongs to.
        :param pulumi.Input[_builtins.str] public_key: The public value of the API key (only returned at creation time).
        :param pulumi.Input[_builtins.str] secret_key: The secret value of the API key (only returned at creation time).
        """
        if note is not None:
            pulumi.set(__self__, "note", note)
        if organization_private_key is not None:
            pulumi.set(__self__, "organization_private_key", organization_private_key)
        if organization_public_key is not None:
            pulumi.set(__self__, "organization_public_key", organization_public_key)
        if project_id is not None:
            pulumi.set(__self__, "project_id", project_id)
        if public_key is not None:
            pulumi.set(__self__, "public_key", public_key)
        if secret_key is not None:
            pulumi.set(__self__, "secret_key", secret_key)

    @_builtins.property
    @pulumi.getter
    def note(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Optional note for the API key (POST /api/public/projects/{projectId}/apiKeys). Because the Langfuse public API only accepts a note at creation time, changing this attribute forces replacement: the old key is deleted and a new one is created (new id and credentials).
        """
        return pulumi.get(self, "note")

    @note.setter
    def note(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "note", value)

    @_builtins.property
    @pulumi.getter(name="organizationPrivateKey")
    def organization_private_key(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Organization private key to authenticate the call.
        """
        return pulumi.get(self, "organization_private_key")

    @organization_private_key.setter
    def organization_private_key(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "organization_private_key", value)

    @_builtins.property
    @pulumi.getter(name="organizationPublicKey")
    def organization_public_key(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Organization public key to authenticate the call.
        """
        return pulumi.get(self, "organization_public_key")

    @organization_public_key.setter
    def organization_public_key(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "organization_public_key", value)

    @_builtins.property
    @pulumi.getter(name="projectId")
    def project_id(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The ID of the project the key belongs to.
        """
        return pulumi.get(self, "project_id")

    @project_id.setter
    def project_id(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "project_id", value)

    @_builtins.property
    @pulumi.getter(name="publicKey")
    def public_key(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The public value of the API key (only returned at creation time).
        """
        return pulumi.get(self, "public_key")

    @public_key.setter
    def public_key(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "public_key", value)

    @_builtins.property
    @pulumi.getter(name="secretKey")
    def secret_key(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The secret value of the API key (only returned at creation time).
        """
        return pulumi.get(self, "secret_key")

    @secret_key.setter
    def secret_key(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "secret_key", value)


@pulumi.type_token("langfuse:index/projectApiKey:ProjectApiKey")
class ProjectApiKey(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 note: pulumi.Input[Optional[_builtins.str]] = None,
                 organization_private_key: pulumi.Input[Optional[_builtins.str]] = None,
                 organization_public_key: pulumi.Input[Optional[_builtins.str]] = None,
                 project_id: pulumi.Input[Optional[_builtins.str]] = None,
                 __props__=None):
        """
        Create a ProjectApiKey resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] note: Optional note for the API key (POST /api/public/projects/{projectId}/apiKeys). Because the Langfuse public API only accepts a note at creation time, changing this attribute forces replacement: the old key is deleted and a new one is created (new id and credentials).
        :param pulumi.Input[_builtins.str] organization_private_key: Organization private key to authenticate the call.
        :param pulumi.Input[_builtins.str] organization_public_key: Organization public key to authenticate the call.
        :param pulumi.Input[_builtins.str] project_id: The ID of the project the key belongs to.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: ProjectApiKeyArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Create a ProjectApiKey resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param ProjectApiKeyArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(ProjectApiKeyArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 note: pulumi.Input[Optional[_builtins.str]] = None,
                 organization_private_key: pulumi.Input[Optional[_builtins.str]] = None,
                 organization_public_key: pulumi.Input[Optional[_builtins.str]] = None,
                 project_id: pulumi.Input[Optional[_builtins.str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = ProjectApiKeyArgs.__new__(ProjectApiKeyArgs)

            __props__.__dict__["note"] = note
            if organization_private_key is None and not opts.urn:
                raise TypeError("Missing required property 'organization_private_key'")
            __props__.__dict__["organization_private_key"] = None if organization_private_key is None else pulumi.Output.secret(organization_private_key)
            if organization_public_key is None and not opts.urn:
                raise TypeError("Missing required property 'organization_public_key'")
            __props__.__dict__["organization_public_key"] = organization_public_key
            if project_id is None and not opts.urn:
                raise TypeError("Missing required property 'project_id'")
            __props__.__dict__["project_id"] = project_id
            __props__.__dict__["public_key"] = None
            __props__.__dict__["secret_key"] = None
        secret_opts = pulumi.ResourceOptions(additional_secret_outputs=["organizationPrivateKey", "publicKey", "secretKey"])
        opts = pulumi.ResourceOptions.merge(opts, secret_opts)
        super(ProjectApiKey, __self__).__init__(
            'langfuse:index/projectApiKey:ProjectApiKey',
            resource_name,
            __props__,
            opts,
            package_ref=_utilities.get_package())

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            note: pulumi.Input[Optional[_builtins.str]] = None,
            organization_private_key: pulumi.Input[Optional[_builtins.str]] = None,
            organization_public_key: pulumi.Input[Optional[_builtins.str]] = None,
            project_id: pulumi.Input[Optional[_builtins.str]] = None,
            public_key: pulumi.Input[Optional[_builtins.str]] = None,
            secret_key: pulumi.Input[Optional[_builtins.str]] = None) -> 'ProjectApiKey':
        """
        Get an existing ProjectApiKey resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] note: Optional note for the API key (POST /api/public/projects/{projectId}/apiKeys). Because the Langfuse public API only accepts a note at creation time, changing this attribute forces replacement: the old key is deleted and a new one is created (new id and credentials).
        :param pulumi.Input[_builtins.str] organization_private_key: Organization private key to authenticate the call.
        :param pulumi.Input[_builtins.str] organization_public_key: Organization public key to authenticate the call.
        :param pulumi.Input[_builtins.str] project_id: The ID of the project the key belongs to.
        :param pulumi.Input[_builtins.str] public_key: The public value of the API key (only returned at creation time).
        :param pulumi.Input[_builtins.str] secret_key: The secret value of the API key (only returned at creation time).
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _ProjectApiKeyState.__new__(_ProjectApiKeyState)

        __props__.__dict__["note"] = note
        __props__.__dict__["organization_private_key"] = organization_private_key
        __props__.__dict__["organization_public_key"] = organization_public_key
        __props__.__dict__["project_id"] = project_id
        __props__.__dict__["public_key"] = public_key
        __props__.__dict__["secret_key"] = secret_key
        return ProjectApiKey(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter
    def note(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Optional note for the API key (POST /api/public/projects/{projectId}/apiKeys). Because the Langfuse public API only accepts a note at creation time, changing this attribute forces replacement: the old key is deleted and a new one is created (new id and credentials).
        """
        return pulumi.get(self, "note")

    @_builtins.property
    @pulumi.getter(name="organizationPrivateKey")
    def organization_private_key(self) -> pulumi.Output[_builtins.str]:
        """
        Organization private key to authenticate the call.
        """
        return pulumi.get(self, "organization_private_key")

    @_builtins.property
    @pulumi.getter(name="organizationPublicKey")
    def organization_public_key(self) -> pulumi.Output[_builtins.str]:
        """
        Organization public key to authenticate the call.
        """
        return pulumi.get(self, "organization_public_key")

    @_builtins.property
    @pulumi.getter(name="projectId")
    def project_id(self) -> pulumi.Output[_builtins.str]:
        """
        The ID of the project the key belongs to.
        """
        return pulumi.get(self, "project_id")

    @_builtins.property
    @pulumi.getter(name="publicKey")
    def public_key(self) -> pulumi.Output[_builtins.str]:
        """
        The public value of the API key (only returned at creation time).
        """
        return pulumi.get(self, "public_key")

    @_builtins.property
    @pulumi.getter(name="secretKey")
    def secret_key(self) -> pulumi.Output[_builtins.str]:
        """
        The secret value of the API key (only returned at creation time).
        """
        return pulumi.get(self, "secret_key")

