// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package langfuse

import (
	"fmt"

	"github.com/blang/semver"
	"github.com/gvtlabs/pulumi-langfuse/sdks/go/langfuse/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type module struct {
	version semver.Version
}

func (m *module) Version() semver.Version {
	return m.version
}

func (m *module) Construct(ctx *pulumi.Context, name, typ, urn string) (r pulumi.Resource, err error) {
	switch typ {
	case "langfuse:index/llmConnection:LlmConnection":
		r = &LlmConnection{}
	case "langfuse:index/organization:Organization":
		r = &Organization{}
	case "langfuse:index/organizationApiKey:OrganizationApiKey":
		r = &OrganizationApiKey{}
	case "langfuse:index/organizationMembership:OrganizationMembership":
		r = &OrganizationMembership{}
	case "langfuse:index/project:Project":
		r = &Project{}
	case "langfuse:index/projectApiKey:ProjectApiKey":
		r = &ProjectApiKey{}
	case "langfuse:index/projectMembership:ProjectMembership":
		r = &ProjectMembership{}
	default:
		return nil, fmt.Errorf("unknown resource type: %s", typ)
	}

	err = ctx.RegisterResource(typ, name, nil, r, pulumi.URN_(urn))
	return
}

type pkg struct {
	version semver.Version
}

func (p *pkg) Version() semver.Version {
	return p.version
}

func (p *pkg) ConstructProvider(ctx *pulumi.Context, name, typ, urn string) (pulumi.ProviderResource, error) {
	if typ != "pulumi:providers:langfuse" {
		return nil, fmt.Errorf("unknown provider type: %s", typ)
	}

	r := &Provider{}
	err := ctx.RegisterResource(typ, name, nil, r, pulumi.URN_(urn))
	return r, err
}

func init() {
	version, err := internal.PkgVersion()
	if err != nil {
		version = semver.Version{Major: 1}
	}
	pulumi.RegisterResourceModule(
		"langfuse",
		"index/llmConnection",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"langfuse",
		"index/organization",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"langfuse",
		"index/organizationApiKey",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"langfuse",
		"index/organizationMembership",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"langfuse",
		"index/project",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"langfuse",
		"index/projectApiKey",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"langfuse",
		"index/projectMembership",
		&module{version},
	)
	pulumi.RegisterResourcePackage(
		"langfuse",
		&pkg{version},
	)
}
