// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package langfuse

import (
	"context"
	"reflect"

	"errors"
	"github.com/gvtlabs/pulumi-langfuse/sdks/go/langfuse/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type LlmConnection struct {
	pulumi.CustomResourceState

	// The LLM service type. Valid values: anthropic, openai, azure, bedrock, google-vertex-ai, google-ai-studio.
	Adapter pulumi.StringOutput `pulumi:"adapter"`
	// Optional base URL override for the LLM provider API.
	BaseUrl pulumi.StringPtrOutput `pulumi:"baseUrl"`
	// Adapter-specific configuration as a JSON string.
	Config pulumi.StringPtrOutput `pulumi:"config"`
	// Optional list of custom model identifiers.
	CustomModels pulumi.StringArrayOutput `pulumi:"customModels"`
	// Optional map of additional HTTP headers for LLM API requests.
	ExtraHeaders pulumi.StringMapOutput `pulumi:"extraHeaders"`
	// The project public key used to authenticate API calls.
	ProjectPublicKey pulumi.StringOutput `pulumi:"projectPublicKey"`
	// The project secret key used to authenticate API calls.
	ProjectSecretKey pulumi.StringOutput `pulumi:"projectSecretKey"`
	// The unique name identifying this LLM connection within the project. Changing this value destroys and recreates the resource, as the provider name is the upsert key.
	ProviderName pulumi.StringOutput `pulumi:"providerName"`
	// The API authentication key for the LLM provider.
	SecretKey pulumi.StringOutput `pulumi:"secretKey"`
	// Whether to include default models. Defaults to true if not set.
	WithDefaultModels pulumi.BoolOutput `pulumi:"withDefaultModels"`
}

// NewLlmConnection registers a new resource with the given unique name, arguments, and options.
func NewLlmConnection(ctx *pulumi.Context,
	name string, args *LlmConnectionArgs, opts ...pulumi.ResourceOption) (*LlmConnection, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Adapter == nil {
		return nil, errors.New("invalid value for required argument 'Adapter'")
	}
	if args.ProjectPublicKey == nil {
		return nil, errors.New("invalid value for required argument 'ProjectPublicKey'")
	}
	if args.ProjectSecretKey == nil {
		return nil, errors.New("invalid value for required argument 'ProjectSecretKey'")
	}
	if args.ProviderName == nil {
		return nil, errors.New("invalid value for required argument 'ProviderName'")
	}
	if args.SecretKey == nil {
		return nil, errors.New("invalid value for required argument 'SecretKey'")
	}
	if args.ExtraHeaders != nil {
		args.ExtraHeaders = pulumi.ToSecret(args.ExtraHeaders).(pulumi.StringMapInput)
	}
	if args.ProjectPublicKey != nil {
		args.ProjectPublicKey = pulumi.ToSecret(args.ProjectPublicKey).(pulumi.StringInput)
	}
	if args.ProjectSecretKey != nil {
		args.ProjectSecretKey = pulumi.ToSecret(args.ProjectSecretKey).(pulumi.StringInput)
	}
	if args.SecretKey != nil {
		args.SecretKey = pulumi.ToSecret(args.SecretKey).(pulumi.StringInput)
	}
	secrets := pulumi.AdditionalSecretOutputs([]string{
		"extraHeaders",
		"projectPublicKey",
		"projectSecretKey",
		"secretKey",
	})
	opts = append(opts, secrets)
	opts = internal.PkgResourceDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var resource LlmConnection
	err = ctx.RegisterPackageResource("langfuse:index/llmConnection:LlmConnection", name, args, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetLlmConnection gets an existing LlmConnection resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetLlmConnection(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *LlmConnectionState, opts ...pulumi.ResourceOption) (*LlmConnection, error) {
	var resource LlmConnection
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	err = ctx.ReadPackageResource("langfuse:index/llmConnection:LlmConnection", name, id, state, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering LlmConnection resources.
type llmConnectionState struct {
	// The LLM service type. Valid values: anthropic, openai, azure, bedrock, google-vertex-ai, google-ai-studio.
	Adapter *string `pulumi:"adapter"`
	// Optional base URL override for the LLM provider API.
	BaseUrl *string `pulumi:"baseUrl"`
	// Adapter-specific configuration as a JSON string.
	Config *string `pulumi:"config"`
	// Optional list of custom model identifiers.
	CustomModels []string `pulumi:"customModels"`
	// Optional map of additional HTTP headers for LLM API requests.
	ExtraHeaders map[string]string `pulumi:"extraHeaders"`
	// The project public key used to authenticate API calls.
	ProjectPublicKey *string `pulumi:"projectPublicKey"`
	// The project secret key used to authenticate API calls.
	ProjectSecretKey *string `pulumi:"projectSecretKey"`
	// The unique name identifying this LLM connection within the project. Changing this value destroys and recreates the resource, as the provider name is the upsert key.
	ProviderName *string `pulumi:"providerName"`
	// The API authentication key for the LLM provider.
	SecretKey *string `pulumi:"secretKey"`
	// Whether to include default models. Defaults to true if not set.
	WithDefaultModels *bool `pulumi:"withDefaultModels"`
}

type LlmConnectionState struct {
	// The LLM service type. Valid values: anthropic, openai, azure, bedrock, google-vertex-ai, google-ai-studio.
	Adapter pulumi.StringPtrInput
	// Optional base URL override for the LLM provider API.
	BaseUrl pulumi.StringPtrInput
	// Adapter-specific configuration as a JSON string.
	Config pulumi.StringPtrInput
	// Optional list of custom model identifiers.
	CustomModels pulumi.StringArrayInput
	// Optional map of additional HTTP headers for LLM API requests.
	ExtraHeaders pulumi.StringMapInput
	// The project public key used to authenticate API calls.
	ProjectPublicKey pulumi.StringPtrInput
	// The project secret key used to authenticate API calls.
	ProjectSecretKey pulumi.StringPtrInput
	// The unique name identifying this LLM connection within the project. Changing this value destroys and recreates the resource, as the provider name is the upsert key.
	ProviderName pulumi.StringPtrInput
	// The API authentication key for the LLM provider.
	SecretKey pulumi.StringPtrInput
	// Whether to include default models. Defaults to true if not set.
	WithDefaultModels pulumi.BoolPtrInput
}

func (LlmConnectionState) ElementType() reflect.Type {
	return reflect.TypeOf((*llmConnectionState)(nil)).Elem()
}

type llmConnectionArgs struct {
	// The LLM service type. Valid values: anthropic, openai, azure, bedrock, google-vertex-ai, google-ai-studio.
	Adapter string `pulumi:"adapter"`
	// Optional base URL override for the LLM provider API.
	BaseUrl *string `pulumi:"baseUrl"`
	// Adapter-specific configuration as a JSON string.
	Config *string `pulumi:"config"`
	// Optional list of custom model identifiers.
	CustomModels []string `pulumi:"customModels"`
	// Optional map of additional HTTP headers for LLM API requests.
	ExtraHeaders map[string]string `pulumi:"extraHeaders"`
	// The project public key used to authenticate API calls.
	ProjectPublicKey string `pulumi:"projectPublicKey"`
	// The project secret key used to authenticate API calls.
	ProjectSecretKey string `pulumi:"projectSecretKey"`
	// The unique name identifying this LLM connection within the project. Changing this value destroys and recreates the resource, as the provider name is the upsert key.
	ProviderName string `pulumi:"providerName"`
	// The API authentication key for the LLM provider.
	SecretKey string `pulumi:"secretKey"`
	// Whether to include default models. Defaults to true if not set.
	WithDefaultModels *bool `pulumi:"withDefaultModels"`
}

// The set of arguments for constructing a LlmConnection resource.
type LlmConnectionArgs struct {
	// The LLM service type. Valid values: anthropic, openai, azure, bedrock, google-vertex-ai, google-ai-studio.
	Adapter pulumi.StringInput
	// Optional base URL override for the LLM provider API.
	BaseUrl pulumi.StringPtrInput
	// Adapter-specific configuration as a JSON string.
	Config pulumi.StringPtrInput
	// Optional list of custom model identifiers.
	CustomModels pulumi.StringArrayInput
	// Optional map of additional HTTP headers for LLM API requests.
	ExtraHeaders pulumi.StringMapInput
	// The project public key used to authenticate API calls.
	ProjectPublicKey pulumi.StringInput
	// The project secret key used to authenticate API calls.
	ProjectSecretKey pulumi.StringInput
	// The unique name identifying this LLM connection within the project. Changing this value destroys and recreates the resource, as the provider name is the upsert key.
	ProviderName pulumi.StringInput
	// The API authentication key for the LLM provider.
	SecretKey pulumi.StringInput
	// Whether to include default models. Defaults to true if not set.
	WithDefaultModels pulumi.BoolPtrInput
}

func (LlmConnectionArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*llmConnectionArgs)(nil)).Elem()
}

type LlmConnectionInput interface {
	pulumi.Input

	ToLlmConnectionOutput() LlmConnectionOutput
	ToLlmConnectionOutputWithContext(ctx context.Context) LlmConnectionOutput
}

func (*LlmConnection) ElementType() reflect.Type {
	return reflect.TypeOf((**LlmConnection)(nil)).Elem()
}

func (i *LlmConnection) ToLlmConnectionOutput() LlmConnectionOutput {
	return i.ToLlmConnectionOutputWithContext(context.Background())
}

func (i *LlmConnection) ToLlmConnectionOutputWithContext(ctx context.Context) LlmConnectionOutput {
	return pulumi.ToOutputWithContext(ctx, i).(LlmConnectionOutput)
}

type LlmConnectionOutput struct{ *pulumi.OutputState }

func (LlmConnectionOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**LlmConnection)(nil)).Elem()
}

func (o LlmConnectionOutput) ToLlmConnectionOutput() LlmConnectionOutput {
	return o
}

func (o LlmConnectionOutput) ToLlmConnectionOutputWithContext(ctx context.Context) LlmConnectionOutput {
	return o
}

// The LLM service type. Valid values: anthropic, openai, azure, bedrock, google-vertex-ai, google-ai-studio.
func (o LlmConnectionOutput) Adapter() pulumi.StringOutput {
	return o.ApplyT(func(v *LlmConnection) pulumi.StringOutput { return v.Adapter }).(pulumi.StringOutput)
}

// Optional base URL override for the LLM provider API.
func (o LlmConnectionOutput) BaseUrl() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *LlmConnection) pulumi.StringPtrOutput { return v.BaseUrl }).(pulumi.StringPtrOutput)
}

// Adapter-specific configuration as a JSON string.
func (o LlmConnectionOutput) Config() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *LlmConnection) pulumi.StringPtrOutput { return v.Config }).(pulumi.StringPtrOutput)
}

// Optional list of custom model identifiers.
func (o LlmConnectionOutput) CustomModels() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *LlmConnection) pulumi.StringArrayOutput { return v.CustomModels }).(pulumi.StringArrayOutput)
}

// Optional map of additional HTTP headers for LLM API requests.
func (o LlmConnectionOutput) ExtraHeaders() pulumi.StringMapOutput {
	return o.ApplyT(func(v *LlmConnection) pulumi.StringMapOutput { return v.ExtraHeaders }).(pulumi.StringMapOutput)
}

// The project public key used to authenticate API calls.
func (o LlmConnectionOutput) ProjectPublicKey() pulumi.StringOutput {
	return o.ApplyT(func(v *LlmConnection) pulumi.StringOutput { return v.ProjectPublicKey }).(pulumi.StringOutput)
}

// The project secret key used to authenticate API calls.
func (o LlmConnectionOutput) ProjectSecretKey() pulumi.StringOutput {
	return o.ApplyT(func(v *LlmConnection) pulumi.StringOutput { return v.ProjectSecretKey }).(pulumi.StringOutput)
}

// The unique name identifying this LLM connection within the project. Changing this value destroys and recreates the resource, as the provider name is the upsert key.
func (o LlmConnectionOutput) ProviderName() pulumi.StringOutput {
	return o.ApplyT(func(v *LlmConnection) pulumi.StringOutput { return v.ProviderName }).(pulumi.StringOutput)
}

// The API authentication key for the LLM provider.
func (o LlmConnectionOutput) SecretKey() pulumi.StringOutput {
	return o.ApplyT(func(v *LlmConnection) pulumi.StringOutput { return v.SecretKey }).(pulumi.StringOutput)
}

// Whether to include default models. Defaults to true if not set.
func (o LlmConnectionOutput) WithDefaultModels() pulumi.BoolOutput {
	return o.ApplyT(func(v *LlmConnection) pulumi.BoolOutput { return v.WithDefaultModels }).(pulumi.BoolOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*LlmConnectionInput)(nil)).Elem(), &LlmConnection{})
	pulumi.RegisterOutputType(LlmConnectionOutput{})
}
