// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package langfuse

import (
	"context"
	"reflect"

	"errors"
	"github.com/gvtlabs/pulumi-langfuse/sdks/go/langfuse/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type OrganizationMembership struct {
	pulumi.CustomResourceState

	// The email address of the user to invite.
	Email pulumi.StringOutput `pulumi:"email"`
	// Organization private key to authenticate the call.
	OrganizationPrivateKey pulumi.StringOutput `pulumi:"organizationPrivateKey"`
	// Organization public key to authenticate the call.
	OrganizationPublicKey pulumi.StringOutput `pulumi:"organizationPublicKey"`
	// The role to assign to the user. Valid values are: ADMIN, MEMBER, VIEWER.
	Role pulumi.StringOutput `pulumi:"role"`
	// The status of the membership invitation.
	Status pulumi.StringOutput `pulumi:"status"`
	// The unique identifier of the user.
	UserId pulumi.StringOutput `pulumi:"userId"`
	// The username of the user.
	Username pulumi.StringOutput `pulumi:"username"`
}

// NewOrganizationMembership registers a new resource with the given unique name, arguments, and options.
func NewOrganizationMembership(ctx *pulumi.Context,
	name string, args *OrganizationMembershipArgs, opts ...pulumi.ResourceOption) (*OrganizationMembership, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Email == nil {
		return nil, errors.New("invalid value for required argument 'Email'")
	}
	if args.OrganizationPrivateKey == nil {
		return nil, errors.New("invalid value for required argument 'OrganizationPrivateKey'")
	}
	if args.OrganizationPublicKey == nil {
		return nil, errors.New("invalid value for required argument 'OrganizationPublicKey'")
	}
	if args.Role == nil {
		return nil, errors.New("invalid value for required argument 'Role'")
	}
	if args.OrganizationPrivateKey != nil {
		args.OrganizationPrivateKey = pulumi.ToSecret(args.OrganizationPrivateKey).(pulumi.StringInput)
	}
	if args.OrganizationPublicKey != nil {
		args.OrganizationPublicKey = pulumi.ToSecret(args.OrganizationPublicKey).(pulumi.StringInput)
	}
	secrets := pulumi.AdditionalSecretOutputs([]string{
		"organizationPrivateKey",
		"organizationPublicKey",
	})
	opts = append(opts, secrets)
	opts = internal.PkgResourceDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var resource OrganizationMembership
	err = ctx.RegisterPackageResource("langfuse:index/organizationMembership:OrganizationMembership", name, args, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetOrganizationMembership gets an existing OrganizationMembership resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetOrganizationMembership(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *OrganizationMembershipState, opts ...pulumi.ResourceOption) (*OrganizationMembership, error) {
	var resource OrganizationMembership
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	err = ctx.ReadPackageResource("langfuse:index/organizationMembership:OrganizationMembership", name, id, state, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering OrganizationMembership resources.
type organizationMembershipState struct {
	// The email address of the user to invite.
	Email *string `pulumi:"email"`
	// Organization private key to authenticate the call.
	OrganizationPrivateKey *string `pulumi:"organizationPrivateKey"`
	// Organization public key to authenticate the call.
	OrganizationPublicKey *string `pulumi:"organizationPublicKey"`
	// The role to assign to the user. Valid values are: ADMIN, MEMBER, VIEWER.
	Role *string `pulumi:"role"`
	// The status of the membership invitation.
	Status *string `pulumi:"status"`
	// The unique identifier of the user.
	UserId *string `pulumi:"userId"`
	// The username of the user.
	Username *string `pulumi:"username"`
}

type OrganizationMembershipState struct {
	// The email address of the user to invite.
	Email pulumi.StringPtrInput
	// Organization private key to authenticate the call.
	OrganizationPrivateKey pulumi.StringPtrInput
	// Organization public key to authenticate the call.
	OrganizationPublicKey pulumi.StringPtrInput
	// The role to assign to the user. Valid values are: ADMIN, MEMBER, VIEWER.
	Role pulumi.StringPtrInput
	// The status of the membership invitation.
	Status pulumi.StringPtrInput
	// The unique identifier of the user.
	UserId pulumi.StringPtrInput
	// The username of the user.
	Username pulumi.StringPtrInput
}

func (OrganizationMembershipState) ElementType() reflect.Type {
	return reflect.TypeOf((*organizationMembershipState)(nil)).Elem()
}

type organizationMembershipArgs struct {
	// The email address of the user to invite.
	Email string `pulumi:"email"`
	// Organization private key to authenticate the call.
	OrganizationPrivateKey string `pulumi:"organizationPrivateKey"`
	// Organization public key to authenticate the call.
	OrganizationPublicKey string `pulumi:"organizationPublicKey"`
	// The role to assign to the user. Valid values are: ADMIN, MEMBER, VIEWER.
	Role string `pulumi:"role"`
}

// The set of arguments for constructing a OrganizationMembership resource.
type OrganizationMembershipArgs struct {
	// The email address of the user to invite.
	Email pulumi.StringInput
	// Organization private key to authenticate the call.
	OrganizationPrivateKey pulumi.StringInput
	// Organization public key to authenticate the call.
	OrganizationPublicKey pulumi.StringInput
	// The role to assign to the user. Valid values are: ADMIN, MEMBER, VIEWER.
	Role pulumi.StringInput
}

func (OrganizationMembershipArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*organizationMembershipArgs)(nil)).Elem()
}

type OrganizationMembershipInput interface {
	pulumi.Input

	ToOrganizationMembershipOutput() OrganizationMembershipOutput
	ToOrganizationMembershipOutputWithContext(ctx context.Context) OrganizationMembershipOutput
}

func (*OrganizationMembership) ElementType() reflect.Type {
	return reflect.TypeOf((**OrganizationMembership)(nil)).Elem()
}

func (i *OrganizationMembership) ToOrganizationMembershipOutput() OrganizationMembershipOutput {
	return i.ToOrganizationMembershipOutputWithContext(context.Background())
}

func (i *OrganizationMembership) ToOrganizationMembershipOutputWithContext(ctx context.Context) OrganizationMembershipOutput {
	return pulumi.ToOutputWithContext(ctx, i).(OrganizationMembershipOutput)
}

type OrganizationMembershipOutput struct{ *pulumi.OutputState }

func (OrganizationMembershipOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**OrganizationMembership)(nil)).Elem()
}

func (o OrganizationMembershipOutput) ToOrganizationMembershipOutput() OrganizationMembershipOutput {
	return o
}

func (o OrganizationMembershipOutput) ToOrganizationMembershipOutputWithContext(ctx context.Context) OrganizationMembershipOutput {
	return o
}

// The email address of the user to invite.
func (o OrganizationMembershipOutput) Email() pulumi.StringOutput {
	return o.ApplyT(func(v *OrganizationMembership) pulumi.StringOutput { return v.Email }).(pulumi.StringOutput)
}

// Organization private key to authenticate the call.
func (o OrganizationMembershipOutput) OrganizationPrivateKey() pulumi.StringOutput {
	return o.ApplyT(func(v *OrganizationMembership) pulumi.StringOutput { return v.OrganizationPrivateKey }).(pulumi.StringOutput)
}

// Organization public key to authenticate the call.
func (o OrganizationMembershipOutput) OrganizationPublicKey() pulumi.StringOutput {
	return o.ApplyT(func(v *OrganizationMembership) pulumi.StringOutput { return v.OrganizationPublicKey }).(pulumi.StringOutput)
}

// The role to assign to the user. Valid values are: ADMIN, MEMBER, VIEWER.
func (o OrganizationMembershipOutput) Role() pulumi.StringOutput {
	return o.ApplyT(func(v *OrganizationMembership) pulumi.StringOutput { return v.Role }).(pulumi.StringOutput)
}

// The status of the membership invitation.
func (o OrganizationMembershipOutput) Status() pulumi.StringOutput {
	return o.ApplyT(func(v *OrganizationMembership) pulumi.StringOutput { return v.Status }).(pulumi.StringOutput)
}

// The unique identifier of the user.
func (o OrganizationMembershipOutput) UserId() pulumi.StringOutput {
	return o.ApplyT(func(v *OrganizationMembership) pulumi.StringOutput { return v.UserId }).(pulumi.StringOutput)
}

// The username of the user.
func (o OrganizationMembershipOutput) Username() pulumi.StringOutput {
	return o.ApplyT(func(v *OrganizationMembership) pulumi.StringOutput { return v.Username }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*OrganizationMembershipInput)(nil)).Elem(), &OrganizationMembership{})
	pulumi.RegisterOutputType(OrganizationMembershipOutput{})
}
