// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package langfuse

import (
	"context"
	"reflect"

	"errors"
	"github.com/gvtlabs/pulumi-langfuse/sdks/go/langfuse/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type OrganizationApiKey struct {
	pulumi.CustomResourceState

	// The Langfuse organization the key belongs to.
	OrganizationId pulumi.StringOutput `pulumi:"organizationId"`
	// The public value of the API key (only returned at creation time).
	PublicKey pulumi.StringOutput `pulumi:"publicKey"`
	// The secret value of the API key (only returned at creation time).
	SecretKey pulumi.StringOutput `pulumi:"secretKey"`
}

// NewOrganizationApiKey registers a new resource with the given unique name, arguments, and options.
func NewOrganizationApiKey(ctx *pulumi.Context,
	name string, args *OrganizationApiKeyArgs, opts ...pulumi.ResourceOption) (*OrganizationApiKey, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.OrganizationId == nil {
		return nil, errors.New("invalid value for required argument 'OrganizationId'")
	}
	secrets := pulumi.AdditionalSecretOutputs([]string{
		"publicKey",
		"secretKey",
	})
	opts = append(opts, secrets)
	opts = internal.PkgResourceDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var resource OrganizationApiKey
	err = ctx.RegisterPackageResource("langfuse:index/organizationApiKey:OrganizationApiKey", name, args, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetOrganizationApiKey gets an existing OrganizationApiKey resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetOrganizationApiKey(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *OrganizationApiKeyState, opts ...pulumi.ResourceOption) (*OrganizationApiKey, error) {
	var resource OrganizationApiKey
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	err = ctx.ReadPackageResource("langfuse:index/organizationApiKey:OrganizationApiKey", name, id, state, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering OrganizationApiKey resources.
type organizationApiKeyState struct {
	// The Langfuse organization the key belongs to.
	OrganizationId *string `pulumi:"organizationId"`
	// The public value of the API key (only returned at creation time).
	PublicKey *string `pulumi:"publicKey"`
	// The secret value of the API key (only returned at creation time).
	SecretKey *string `pulumi:"secretKey"`
}

type OrganizationApiKeyState struct {
	// The Langfuse organization the key belongs to.
	OrganizationId pulumi.StringPtrInput
	// The public value of the API key (only returned at creation time).
	PublicKey pulumi.StringPtrInput
	// The secret value of the API key (only returned at creation time).
	SecretKey pulumi.StringPtrInput
}

func (OrganizationApiKeyState) ElementType() reflect.Type {
	return reflect.TypeOf((*organizationApiKeyState)(nil)).Elem()
}

type organizationApiKeyArgs struct {
	// The Langfuse organization the key belongs to.
	OrganizationId string `pulumi:"organizationId"`
}

// The set of arguments for constructing a OrganizationApiKey resource.
type OrganizationApiKeyArgs struct {
	// The Langfuse organization the key belongs to.
	OrganizationId pulumi.StringInput
}

func (OrganizationApiKeyArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*organizationApiKeyArgs)(nil)).Elem()
}

type OrganizationApiKeyInput interface {
	pulumi.Input

	ToOrganizationApiKeyOutput() OrganizationApiKeyOutput
	ToOrganizationApiKeyOutputWithContext(ctx context.Context) OrganizationApiKeyOutput
}

func (*OrganizationApiKey) ElementType() reflect.Type {
	return reflect.TypeOf((**OrganizationApiKey)(nil)).Elem()
}

func (i *OrganizationApiKey) ToOrganizationApiKeyOutput() OrganizationApiKeyOutput {
	return i.ToOrganizationApiKeyOutputWithContext(context.Background())
}

func (i *OrganizationApiKey) ToOrganizationApiKeyOutputWithContext(ctx context.Context) OrganizationApiKeyOutput {
	return pulumi.ToOutputWithContext(ctx, i).(OrganizationApiKeyOutput)
}

type OrganizationApiKeyOutput struct{ *pulumi.OutputState }

func (OrganizationApiKeyOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**OrganizationApiKey)(nil)).Elem()
}

func (o OrganizationApiKeyOutput) ToOrganizationApiKeyOutput() OrganizationApiKeyOutput {
	return o
}

func (o OrganizationApiKeyOutput) ToOrganizationApiKeyOutputWithContext(ctx context.Context) OrganizationApiKeyOutput {
	return o
}

// The Langfuse organization the key belongs to.
func (o OrganizationApiKeyOutput) OrganizationId() pulumi.StringOutput {
	return o.ApplyT(func(v *OrganizationApiKey) pulumi.StringOutput { return v.OrganizationId }).(pulumi.StringOutput)
}

// The public value of the API key (only returned at creation time).
func (o OrganizationApiKeyOutput) PublicKey() pulumi.StringOutput {
	return o.ApplyT(func(v *OrganizationApiKey) pulumi.StringOutput { return v.PublicKey }).(pulumi.StringOutput)
}

// The secret value of the API key (only returned at creation time).
func (o OrganizationApiKeyOutput) SecretKey() pulumi.StringOutput {
	return o.ApplyT(func(v *OrganizationApiKey) pulumi.StringOutput { return v.SecretKey }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*OrganizationApiKeyInput)(nil)).Elem(), &OrganizationApiKey{})
	pulumi.RegisterOutputType(OrganizationApiKeyOutput{})
}
