// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package langfuse

import (
	"context"
	"reflect"

	"errors"
	"github.com/gvtlabs/pulumi-langfuse/sdks/go/langfuse/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type Project struct {
	pulumi.CustomResourceState

	// Metadata for the project as key-value pairs.
	Metadata pulumi.StringMapOutput `pulumi:"metadata"`
	// The display name of the project.
	Name pulumi.StringOutput `pulumi:"name"`
	// The ID of the organization that owns this project.
	OrganizationId pulumi.StringOutput `pulumi:"organizationId"`
	// Organization private key to authenticate the call.
	OrganizationPrivateKey pulumi.StringOutput `pulumi:"organizationPrivateKey"`
	// Organization public key to authenticate the call.
	OrganizationPublicKey pulumi.StringOutput `pulumi:"organizationPublicKey"`
	// The retention period for the project in days. If not set, or set with a value of 0, data will be stored indefinitely.
	RetentionDays pulumi.Float64Output `pulumi:"retentionDays"`
}

// NewProject registers a new resource with the given unique name, arguments, and options.
func NewProject(ctx *pulumi.Context,
	name string, args *ProjectArgs, opts ...pulumi.ResourceOption) (*Project, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.OrganizationId == nil {
		return nil, errors.New("invalid value for required argument 'OrganizationId'")
	}
	if args.OrganizationPrivateKey == nil {
		return nil, errors.New("invalid value for required argument 'OrganizationPrivateKey'")
	}
	if args.OrganizationPublicKey == nil {
		return nil, errors.New("invalid value for required argument 'OrganizationPublicKey'")
	}
	if args.OrganizationPrivateKey != nil {
		args.OrganizationPrivateKey = pulumi.ToSecret(args.OrganizationPrivateKey).(pulumi.StringInput)
	}
	if args.OrganizationPublicKey != nil {
		args.OrganizationPublicKey = pulumi.ToSecret(args.OrganizationPublicKey).(pulumi.StringInput)
	}
	secrets := pulumi.AdditionalSecretOutputs([]string{
		"organizationPrivateKey",
		"organizationPublicKey",
	})
	opts = append(opts, secrets)
	opts = internal.PkgResourceDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var resource Project
	err = ctx.RegisterPackageResource("langfuse:index/project:Project", name, args, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetProject gets an existing Project resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetProject(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *ProjectState, opts ...pulumi.ResourceOption) (*Project, error) {
	var resource Project
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	err = ctx.ReadPackageResource("langfuse:index/project:Project", name, id, state, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering Project resources.
type projectState struct {
	// Metadata for the project as key-value pairs.
	Metadata map[string]string `pulumi:"metadata"`
	// The display name of the project.
	Name *string `pulumi:"name"`
	// The ID of the organization that owns this project.
	OrganizationId *string `pulumi:"organizationId"`
	// Organization private key to authenticate the call.
	OrganizationPrivateKey *string `pulumi:"organizationPrivateKey"`
	// Organization public key to authenticate the call.
	OrganizationPublicKey *string `pulumi:"organizationPublicKey"`
	// The retention period for the project in days. If not set, or set with a value of 0, data will be stored indefinitely.
	RetentionDays *float64 `pulumi:"retentionDays"`
}

type ProjectState struct {
	// Metadata for the project as key-value pairs.
	Metadata pulumi.StringMapInput
	// The display name of the project.
	Name pulumi.StringPtrInput
	// The ID of the organization that owns this project.
	OrganizationId pulumi.StringPtrInput
	// Organization private key to authenticate the call.
	OrganizationPrivateKey pulumi.StringPtrInput
	// Organization public key to authenticate the call.
	OrganizationPublicKey pulumi.StringPtrInput
	// The retention period for the project in days. If not set, or set with a value of 0, data will be stored indefinitely.
	RetentionDays pulumi.Float64PtrInput
}

func (ProjectState) ElementType() reflect.Type {
	return reflect.TypeOf((*projectState)(nil)).Elem()
}

type projectArgs struct {
	// Metadata for the project as key-value pairs.
	Metadata map[string]string `pulumi:"metadata"`
	// The display name of the project.
	Name *string `pulumi:"name"`
	// The ID of the organization that owns this project.
	OrganizationId string `pulumi:"organizationId"`
	// Organization private key to authenticate the call.
	OrganizationPrivateKey string `pulumi:"organizationPrivateKey"`
	// Organization public key to authenticate the call.
	OrganizationPublicKey string `pulumi:"organizationPublicKey"`
	// The retention period for the project in days. If not set, or set with a value of 0, data will be stored indefinitely.
	RetentionDays *float64 `pulumi:"retentionDays"`
}

// The set of arguments for constructing a Project resource.
type ProjectArgs struct {
	// Metadata for the project as key-value pairs.
	Metadata pulumi.StringMapInput
	// The display name of the project.
	Name pulumi.StringPtrInput
	// The ID of the organization that owns this project.
	OrganizationId pulumi.StringInput
	// Organization private key to authenticate the call.
	OrganizationPrivateKey pulumi.StringInput
	// Organization public key to authenticate the call.
	OrganizationPublicKey pulumi.StringInput
	// The retention period for the project in days. If not set, or set with a value of 0, data will be stored indefinitely.
	RetentionDays pulumi.Float64PtrInput
}

func (ProjectArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*projectArgs)(nil)).Elem()
}

type ProjectInput interface {
	pulumi.Input

	ToProjectOutput() ProjectOutput
	ToProjectOutputWithContext(ctx context.Context) ProjectOutput
}

func (*Project) ElementType() reflect.Type {
	return reflect.TypeOf((**Project)(nil)).Elem()
}

func (i *Project) ToProjectOutput() ProjectOutput {
	return i.ToProjectOutputWithContext(context.Background())
}

func (i *Project) ToProjectOutputWithContext(ctx context.Context) ProjectOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ProjectOutput)
}

type ProjectOutput struct{ *pulumi.OutputState }

func (ProjectOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Project)(nil)).Elem()
}

func (o ProjectOutput) ToProjectOutput() ProjectOutput {
	return o
}

func (o ProjectOutput) ToProjectOutputWithContext(ctx context.Context) ProjectOutput {
	return o
}

// Metadata for the project as key-value pairs.
func (o ProjectOutput) Metadata() pulumi.StringMapOutput {
	return o.ApplyT(func(v *Project) pulumi.StringMapOutput { return v.Metadata }).(pulumi.StringMapOutput)
}

// The display name of the project.
func (o ProjectOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *Project) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// The ID of the organization that owns this project.
func (o ProjectOutput) OrganizationId() pulumi.StringOutput {
	return o.ApplyT(func(v *Project) pulumi.StringOutput { return v.OrganizationId }).(pulumi.StringOutput)
}

// Organization private key to authenticate the call.
func (o ProjectOutput) OrganizationPrivateKey() pulumi.StringOutput {
	return o.ApplyT(func(v *Project) pulumi.StringOutput { return v.OrganizationPrivateKey }).(pulumi.StringOutput)
}

// Organization public key to authenticate the call.
func (o ProjectOutput) OrganizationPublicKey() pulumi.StringOutput {
	return o.ApplyT(func(v *Project) pulumi.StringOutput { return v.OrganizationPublicKey }).(pulumi.StringOutput)
}

// The retention period for the project in days. If not set, or set with a value of 0, data will be stored indefinitely.
func (o ProjectOutput) RetentionDays() pulumi.Float64Output {
	return o.ApplyT(func(v *Project) pulumi.Float64Output { return v.RetentionDays }).(pulumi.Float64Output)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*ProjectInput)(nil)).Elem(), &Project{})
	pulumi.RegisterOutputType(ProjectOutput{})
}
