// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package langfuse

import (
	"context"
	"reflect"

	"errors"
	"github.com/gvtlabs/pulumi-langfuse/sdks/go/langfuse/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type ProjectApiKey struct {
	pulumi.CustomResourceState

	// Optional note for the API key (POST /api/public/projects/{projectId}/apiKeys). Because the Langfuse public API only accepts a note at creation time, changing this attribute forces replacement: the old key is deleted and a new one is created (new id and credentials).
	Note pulumi.StringPtrOutput `pulumi:"note"`
	// Organization private key to authenticate the call.
	OrganizationPrivateKey pulumi.StringOutput `pulumi:"organizationPrivateKey"`
	// Organization public key to authenticate the call.
	OrganizationPublicKey pulumi.StringOutput `pulumi:"organizationPublicKey"`
	// The ID of the project the key belongs to.
	ProjectId pulumi.StringOutput `pulumi:"projectId"`
	// The public value of the API key (only returned at creation time).
	PublicKey pulumi.StringOutput `pulumi:"publicKey"`
	// The secret value of the API key (only returned at creation time).
	SecretKey pulumi.StringOutput `pulumi:"secretKey"`
}

// NewProjectApiKey registers a new resource with the given unique name, arguments, and options.
func NewProjectApiKey(ctx *pulumi.Context,
	name string, args *ProjectApiKeyArgs, opts ...pulumi.ResourceOption) (*ProjectApiKey, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.OrganizationPrivateKey == nil {
		return nil, errors.New("invalid value for required argument 'OrganizationPrivateKey'")
	}
	if args.OrganizationPublicKey == nil {
		return nil, errors.New("invalid value for required argument 'OrganizationPublicKey'")
	}
	if args.ProjectId == nil {
		return nil, errors.New("invalid value for required argument 'ProjectId'")
	}
	if args.OrganizationPrivateKey != nil {
		args.OrganizationPrivateKey = pulumi.ToSecret(args.OrganizationPrivateKey).(pulumi.StringInput)
	}
	secrets := pulumi.AdditionalSecretOutputs([]string{
		"organizationPrivateKey",
		"publicKey",
		"secretKey",
	})
	opts = append(opts, secrets)
	opts = internal.PkgResourceDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var resource ProjectApiKey
	err = ctx.RegisterPackageResource("langfuse:index/projectApiKey:ProjectApiKey", name, args, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetProjectApiKey gets an existing ProjectApiKey resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetProjectApiKey(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *ProjectApiKeyState, opts ...pulumi.ResourceOption) (*ProjectApiKey, error) {
	var resource ProjectApiKey
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	err = ctx.ReadPackageResource("langfuse:index/projectApiKey:ProjectApiKey", name, id, state, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering ProjectApiKey resources.
type projectApiKeyState struct {
	// Optional note for the API key (POST /api/public/projects/{projectId}/apiKeys). Because the Langfuse public API only accepts a note at creation time, changing this attribute forces replacement: the old key is deleted and a new one is created (new id and credentials).
	Note *string `pulumi:"note"`
	// Organization private key to authenticate the call.
	OrganizationPrivateKey *string `pulumi:"organizationPrivateKey"`
	// Organization public key to authenticate the call.
	OrganizationPublicKey *string `pulumi:"organizationPublicKey"`
	// The ID of the project the key belongs to.
	ProjectId *string `pulumi:"projectId"`
	// The public value of the API key (only returned at creation time).
	PublicKey *string `pulumi:"publicKey"`
	// The secret value of the API key (only returned at creation time).
	SecretKey *string `pulumi:"secretKey"`
}

type ProjectApiKeyState struct {
	// Optional note for the API key (POST /api/public/projects/{projectId}/apiKeys). Because the Langfuse public API only accepts a note at creation time, changing this attribute forces replacement: the old key is deleted and a new one is created (new id and credentials).
	Note pulumi.StringPtrInput
	// Organization private key to authenticate the call.
	OrganizationPrivateKey pulumi.StringPtrInput
	// Organization public key to authenticate the call.
	OrganizationPublicKey pulumi.StringPtrInput
	// The ID of the project the key belongs to.
	ProjectId pulumi.StringPtrInput
	// The public value of the API key (only returned at creation time).
	PublicKey pulumi.StringPtrInput
	// The secret value of the API key (only returned at creation time).
	SecretKey pulumi.StringPtrInput
}

func (ProjectApiKeyState) ElementType() reflect.Type {
	return reflect.TypeOf((*projectApiKeyState)(nil)).Elem()
}

type projectApiKeyArgs struct {
	// Optional note for the API key (POST /api/public/projects/{projectId}/apiKeys). Because the Langfuse public API only accepts a note at creation time, changing this attribute forces replacement: the old key is deleted and a new one is created (new id and credentials).
	Note *string `pulumi:"note"`
	// Organization private key to authenticate the call.
	OrganizationPrivateKey string `pulumi:"organizationPrivateKey"`
	// Organization public key to authenticate the call.
	OrganizationPublicKey string `pulumi:"organizationPublicKey"`
	// The ID of the project the key belongs to.
	ProjectId string `pulumi:"projectId"`
}

// The set of arguments for constructing a ProjectApiKey resource.
type ProjectApiKeyArgs struct {
	// Optional note for the API key (POST /api/public/projects/{projectId}/apiKeys). Because the Langfuse public API only accepts a note at creation time, changing this attribute forces replacement: the old key is deleted and a new one is created (new id and credentials).
	Note pulumi.StringPtrInput
	// Organization private key to authenticate the call.
	OrganizationPrivateKey pulumi.StringInput
	// Organization public key to authenticate the call.
	OrganizationPublicKey pulumi.StringInput
	// The ID of the project the key belongs to.
	ProjectId pulumi.StringInput
}

func (ProjectApiKeyArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*projectApiKeyArgs)(nil)).Elem()
}

type ProjectApiKeyInput interface {
	pulumi.Input

	ToProjectApiKeyOutput() ProjectApiKeyOutput
	ToProjectApiKeyOutputWithContext(ctx context.Context) ProjectApiKeyOutput
}

func (*ProjectApiKey) ElementType() reflect.Type {
	return reflect.TypeOf((**ProjectApiKey)(nil)).Elem()
}

func (i *ProjectApiKey) ToProjectApiKeyOutput() ProjectApiKeyOutput {
	return i.ToProjectApiKeyOutputWithContext(context.Background())
}

func (i *ProjectApiKey) ToProjectApiKeyOutputWithContext(ctx context.Context) ProjectApiKeyOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ProjectApiKeyOutput)
}

type ProjectApiKeyOutput struct{ *pulumi.OutputState }

func (ProjectApiKeyOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**ProjectApiKey)(nil)).Elem()
}

func (o ProjectApiKeyOutput) ToProjectApiKeyOutput() ProjectApiKeyOutput {
	return o
}

func (o ProjectApiKeyOutput) ToProjectApiKeyOutputWithContext(ctx context.Context) ProjectApiKeyOutput {
	return o
}

// Optional note for the API key (POST /api/public/projects/{projectId}/apiKeys). Because the Langfuse public API only accepts a note at creation time, changing this attribute forces replacement: the old key is deleted and a new one is created (new id and credentials).
func (o ProjectApiKeyOutput) Note() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *ProjectApiKey) pulumi.StringPtrOutput { return v.Note }).(pulumi.StringPtrOutput)
}

// Organization private key to authenticate the call.
func (o ProjectApiKeyOutput) OrganizationPrivateKey() pulumi.StringOutput {
	return o.ApplyT(func(v *ProjectApiKey) pulumi.StringOutput { return v.OrganizationPrivateKey }).(pulumi.StringOutput)
}

// Organization public key to authenticate the call.
func (o ProjectApiKeyOutput) OrganizationPublicKey() pulumi.StringOutput {
	return o.ApplyT(func(v *ProjectApiKey) pulumi.StringOutput { return v.OrganizationPublicKey }).(pulumi.StringOutput)
}

// The ID of the project the key belongs to.
func (o ProjectApiKeyOutput) ProjectId() pulumi.StringOutput {
	return o.ApplyT(func(v *ProjectApiKey) pulumi.StringOutput { return v.ProjectId }).(pulumi.StringOutput)
}

// The public value of the API key (only returned at creation time).
func (o ProjectApiKeyOutput) PublicKey() pulumi.StringOutput {
	return o.ApplyT(func(v *ProjectApiKey) pulumi.StringOutput { return v.PublicKey }).(pulumi.StringOutput)
}

// The secret value of the API key (only returned at creation time).
func (o ProjectApiKeyOutput) SecretKey() pulumi.StringOutput {
	return o.ApplyT(func(v *ProjectApiKey) pulumi.StringOutput { return v.SecretKey }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*ProjectApiKeyInput)(nil)).Elem(), &ProjectApiKey{})
	pulumi.RegisterOutputType(ProjectApiKeyOutput{})
}
