// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package langfuse

import (
	"context"
	"reflect"

	"errors"
	"github.com/gvtlabs/pulumi-langfuse/sdks/go/langfuse/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type ProjectMembership struct {
	pulumi.CustomResourceState

	// The email address of the user to add to the project.
	Email pulumi.StringOutput `pulumi:"email"`
	// The name of the user.
	Name pulumi.StringOutput `pulumi:"name"`
	// Organization private key to authenticate the call.
	OrganizationPrivateKey pulumi.StringOutput `pulumi:"organizationPrivateKey"`
	// Organization public key to authenticate the call.
	OrganizationPublicKey pulumi.StringOutput `pulumi:"organizationPublicKey"`
	// The ID of the project.
	ProjectId pulumi.StringOutput `pulumi:"projectId"`
	// The role to assign to the user. Valid values are: OWNER, ADMIN, MEMBER, VIEWER, NONE.
	Role pulumi.StringOutput `pulumi:"role"`
	// The unique identifier of the user.
	UserId pulumi.StringOutput `pulumi:"userId"`
}

// NewProjectMembership registers a new resource with the given unique name, arguments, and options.
func NewProjectMembership(ctx *pulumi.Context,
	name string, args *ProjectMembershipArgs, opts ...pulumi.ResourceOption) (*ProjectMembership, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Email == nil {
		return nil, errors.New("invalid value for required argument 'Email'")
	}
	if args.OrganizationPrivateKey == nil {
		return nil, errors.New("invalid value for required argument 'OrganizationPrivateKey'")
	}
	if args.OrganizationPublicKey == nil {
		return nil, errors.New("invalid value for required argument 'OrganizationPublicKey'")
	}
	if args.ProjectId == nil {
		return nil, errors.New("invalid value for required argument 'ProjectId'")
	}
	if args.Role == nil {
		return nil, errors.New("invalid value for required argument 'Role'")
	}
	if args.OrganizationPrivateKey != nil {
		args.OrganizationPrivateKey = pulumi.ToSecret(args.OrganizationPrivateKey).(pulumi.StringInput)
	}
	if args.OrganizationPublicKey != nil {
		args.OrganizationPublicKey = pulumi.ToSecret(args.OrganizationPublicKey).(pulumi.StringInput)
	}
	secrets := pulumi.AdditionalSecretOutputs([]string{
		"organizationPrivateKey",
		"organizationPublicKey",
	})
	opts = append(opts, secrets)
	opts = internal.PkgResourceDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var resource ProjectMembership
	err = ctx.RegisterPackageResource("langfuse:index/projectMembership:ProjectMembership", name, args, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetProjectMembership gets an existing ProjectMembership resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetProjectMembership(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *ProjectMembershipState, opts ...pulumi.ResourceOption) (*ProjectMembership, error) {
	var resource ProjectMembership
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	err = ctx.ReadPackageResource("langfuse:index/projectMembership:ProjectMembership", name, id, state, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering ProjectMembership resources.
type projectMembershipState struct {
	// The email address of the user to add to the project.
	Email *string `pulumi:"email"`
	// The name of the user.
	Name *string `pulumi:"name"`
	// Organization private key to authenticate the call.
	OrganizationPrivateKey *string `pulumi:"organizationPrivateKey"`
	// Organization public key to authenticate the call.
	OrganizationPublicKey *string `pulumi:"organizationPublicKey"`
	// The ID of the project.
	ProjectId *string `pulumi:"projectId"`
	// The role to assign to the user. Valid values are: OWNER, ADMIN, MEMBER, VIEWER, NONE.
	Role *string `pulumi:"role"`
	// The unique identifier of the user.
	UserId *string `pulumi:"userId"`
}

type ProjectMembershipState struct {
	// The email address of the user to add to the project.
	Email pulumi.StringPtrInput
	// The name of the user.
	Name pulumi.StringPtrInput
	// Organization private key to authenticate the call.
	OrganizationPrivateKey pulumi.StringPtrInput
	// Organization public key to authenticate the call.
	OrganizationPublicKey pulumi.StringPtrInput
	// The ID of the project.
	ProjectId pulumi.StringPtrInput
	// The role to assign to the user. Valid values are: OWNER, ADMIN, MEMBER, VIEWER, NONE.
	Role pulumi.StringPtrInput
	// The unique identifier of the user.
	UserId pulumi.StringPtrInput
}

func (ProjectMembershipState) ElementType() reflect.Type {
	return reflect.TypeOf((*projectMembershipState)(nil)).Elem()
}

type projectMembershipArgs struct {
	// The email address of the user to add to the project.
	Email string `pulumi:"email"`
	// Organization private key to authenticate the call.
	OrganizationPrivateKey string `pulumi:"organizationPrivateKey"`
	// Organization public key to authenticate the call.
	OrganizationPublicKey string `pulumi:"organizationPublicKey"`
	// The ID of the project.
	ProjectId string `pulumi:"projectId"`
	// The role to assign to the user. Valid values are: OWNER, ADMIN, MEMBER, VIEWER, NONE.
	Role string `pulumi:"role"`
}

// The set of arguments for constructing a ProjectMembership resource.
type ProjectMembershipArgs struct {
	// The email address of the user to add to the project.
	Email pulumi.StringInput
	// Organization private key to authenticate the call.
	OrganizationPrivateKey pulumi.StringInput
	// Organization public key to authenticate the call.
	OrganizationPublicKey pulumi.StringInput
	// The ID of the project.
	ProjectId pulumi.StringInput
	// The role to assign to the user. Valid values are: OWNER, ADMIN, MEMBER, VIEWER, NONE.
	Role pulumi.StringInput
}

func (ProjectMembershipArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*projectMembershipArgs)(nil)).Elem()
}

type ProjectMembershipInput interface {
	pulumi.Input

	ToProjectMembershipOutput() ProjectMembershipOutput
	ToProjectMembershipOutputWithContext(ctx context.Context) ProjectMembershipOutput
}

func (*ProjectMembership) ElementType() reflect.Type {
	return reflect.TypeOf((**ProjectMembership)(nil)).Elem()
}

func (i *ProjectMembership) ToProjectMembershipOutput() ProjectMembershipOutput {
	return i.ToProjectMembershipOutputWithContext(context.Background())
}

func (i *ProjectMembership) ToProjectMembershipOutputWithContext(ctx context.Context) ProjectMembershipOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ProjectMembershipOutput)
}

type ProjectMembershipOutput struct{ *pulumi.OutputState }

func (ProjectMembershipOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**ProjectMembership)(nil)).Elem()
}

func (o ProjectMembershipOutput) ToProjectMembershipOutput() ProjectMembershipOutput {
	return o
}

func (o ProjectMembershipOutput) ToProjectMembershipOutputWithContext(ctx context.Context) ProjectMembershipOutput {
	return o
}

// The email address of the user to add to the project.
func (o ProjectMembershipOutput) Email() pulumi.StringOutput {
	return o.ApplyT(func(v *ProjectMembership) pulumi.StringOutput { return v.Email }).(pulumi.StringOutput)
}

// The name of the user.
func (o ProjectMembershipOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *ProjectMembership) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// Organization private key to authenticate the call.
func (o ProjectMembershipOutput) OrganizationPrivateKey() pulumi.StringOutput {
	return o.ApplyT(func(v *ProjectMembership) pulumi.StringOutput { return v.OrganizationPrivateKey }).(pulumi.StringOutput)
}

// Organization public key to authenticate the call.
func (o ProjectMembershipOutput) OrganizationPublicKey() pulumi.StringOutput {
	return o.ApplyT(func(v *ProjectMembership) pulumi.StringOutput { return v.OrganizationPublicKey }).(pulumi.StringOutput)
}

// The ID of the project.
func (o ProjectMembershipOutput) ProjectId() pulumi.StringOutput {
	return o.ApplyT(func(v *ProjectMembership) pulumi.StringOutput { return v.ProjectId }).(pulumi.StringOutput)
}

// The role to assign to the user. Valid values are: OWNER, ADMIN, MEMBER, VIEWER, NONE.
func (o ProjectMembershipOutput) Role() pulumi.StringOutput {
	return o.ApplyT(func(v *ProjectMembership) pulumi.StringOutput { return v.Role }).(pulumi.StringOutput)
}

// The unique identifier of the user.
func (o ProjectMembershipOutput) UserId() pulumi.StringOutput {
	return o.ApplyT(func(v *ProjectMembership) pulumi.StringOutput { return v.UserId }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*ProjectMembershipInput)(nil)).Elem(), &ProjectMembership{})
	pulumi.RegisterOutputType(ProjectMembershipOutput{})
}
