// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package langfuse

import (
	"context"
	"reflect"

	"github.com/gvtlabs/pulumi-langfuse/sdks/go/langfuse/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// The provider type for the langfuse package. By default, resources use package-wide configuration
// settings, however an explicit `Provider` instance may be created and passed during resource
// construction to achieve fine-grained programmatic control over provider settings. See the
// [documentation](https://www.pulumi.com/docs/reference/programming-model/#providers) for more information.
type Provider struct {
	pulumi.ProviderResourceState

	// Admin API key. Only needed when managing organizations. Can also come from LANGFUSE_ADMIN_KEY.
	AdminApiKey pulumi.StringPtrOutput `pulumi:"adminApiKey"`
	// Base URI of the Langfuse instance (defaults to https://app.langfuse.com).
	Host pulumi.StringPtrOutput `pulumi:"host"`
	// Hostname to verify the TLS certificate against, also sent as the SNI value. Set this when the instance is reached through a port forward or tunnel, where the host above (typically localhost) cannot match the certificate. Certificate verification remains enabled.
	TlsServerName pulumi.StringPtrOutput `pulumi:"tlsServerName"`
}

// NewProvider registers a new resource with the given unique name, arguments, and options.
func NewProvider(ctx *pulumi.Context,
	name string, args *ProviderArgs, opts ...pulumi.ResourceOption) (*Provider, error) {
	if args == nil {
		args = &ProviderArgs{}
	}

	if args.AdminApiKey != nil {
		args.AdminApiKey = pulumi.ToSecret(args.AdminApiKey).(pulumi.StringPtrInput)
	}
	secrets := pulumi.AdditionalSecretOutputs([]string{
		"adminApiKey",
	})
	opts = append(opts, secrets)
	opts = internal.PkgResourceDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var resource Provider
	err = ctx.RegisterPackageResource("pulumi:providers:langfuse", name, args, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

type providerArgs struct {
	// Admin API key. Only needed when managing organizations. Can also come from LANGFUSE_ADMIN_KEY.
	AdminApiKey *string `pulumi:"adminApiKey"`
	// Base URI of the Langfuse instance (defaults to https://app.langfuse.com).
	Host *string `pulumi:"host"`
	// Hostname to verify the TLS certificate against, also sent as the SNI value. Set this when the instance is reached through a port forward or tunnel, where the host above (typically localhost) cannot match the certificate. Certificate verification remains enabled.
	TlsServerName *string `pulumi:"tlsServerName"`
}

// The set of arguments for constructing a Provider resource.
type ProviderArgs struct {
	// Admin API key. Only needed when managing organizations. Can also come from LANGFUSE_ADMIN_KEY.
	AdminApiKey pulumi.StringPtrInput
	// Base URI of the Langfuse instance (defaults to https://app.langfuse.com).
	Host pulumi.StringPtrInput
	// Hostname to verify the TLS certificate against, also sent as the SNI value. Set this when the instance is reached through a port forward or tunnel, where the host above (typically localhost) cannot match the certificate. Certificate verification remains enabled.
	TlsServerName pulumi.StringPtrInput
}

func (ProviderArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*providerArgs)(nil)).Elem()
}

// This function returns a Terraform config object with terraform-namecased keys,to be used with the Terraform Module Provider.
func (r *Provider) TerraformConfig(ctx *pulumi.Context) (pulumi.MapOutput, error) {
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return pulumi.MapOutput{}, err
	}
	out, err := ctx.CallPackage("pulumi:providers:langfuse/terraformConfig", nil, providerTerraformConfigResultOutput{}, r, ref)
	if err != nil {
		return pulumi.MapOutput{}, err
	}
	return out.(providerTerraformConfigResultOutput).Result(), nil
}

type providerTerraformConfigResult struct {
	Result map[string]interface{} `pulumi:"result"`
}

type providerTerraformConfigResultOutput struct{ *pulumi.OutputState }

func (providerTerraformConfigResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*providerTerraformConfigResult)(nil)).Elem()
}

func (o providerTerraformConfigResultOutput) Result() pulumi.MapOutput {
	return o.ApplyT(func(v providerTerraformConfigResult) map[string]interface{} { return v.Result }).(pulumi.MapOutput)
}

type ProviderInput interface {
	pulumi.Input

	ToProviderOutput() ProviderOutput
	ToProviderOutputWithContext(ctx context.Context) ProviderOutput
}

func (*Provider) ElementType() reflect.Type {
	return reflect.TypeOf((**Provider)(nil)).Elem()
}

func (i *Provider) ToProviderOutput() ProviderOutput {
	return i.ToProviderOutputWithContext(context.Background())
}

func (i *Provider) ToProviderOutputWithContext(ctx context.Context) ProviderOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ProviderOutput)
}

type ProviderOutput struct{ *pulumi.OutputState }

func (ProviderOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Provider)(nil)).Elem()
}

func (o ProviderOutput) ToProviderOutput() ProviderOutput {
	return o
}

func (o ProviderOutput) ToProviderOutputWithContext(ctx context.Context) ProviderOutput {
	return o
}

// Admin API key. Only needed when managing organizations. Can also come from LANGFUSE_ADMIN_KEY.
func (o ProviderOutput) AdminApiKey() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Provider) pulumi.StringPtrOutput { return v.AdminApiKey }).(pulumi.StringPtrOutput)
}

// Base URI of the Langfuse instance (defaults to https://app.langfuse.com).
func (o ProviderOutput) Host() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Provider) pulumi.StringPtrOutput { return v.Host }).(pulumi.StringPtrOutput)
}

// Hostname to verify the TLS certificate against, also sent as the SNI value. Set this when the instance is reached through a port forward or tunnel, where the host above (typically localhost) cannot match the certificate. Certificate verification remains enabled.
func (o ProviderOutput) TlsServerName() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Provider) pulumi.StringPtrOutput { return v.TlsServerName }).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*ProviderInput)(nil)).Elem(), &Provider{})
	pulumi.RegisterOutputType(ProviderOutput{})
	pulumi.RegisterOutputType(providerTerraformConfigResultOutput{})
}
