// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.langfuse.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.Boolean;
import java.lang.String;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class LlmConnectionState extends com.pulumi.resources.ResourceArgs {

    public static final LlmConnectionState Empty = new LlmConnectionState();

    /**
     * The LLM service type. Valid values: anthropic, openai, azure, bedrock, google-vertex-ai, google-ai-studio.
     * 
     */
    @Import(name="adapter")
    private @Nullable Output<String> adapter;

    /**
     * @return The LLM service type. Valid values: anthropic, openai, azure, bedrock, google-vertex-ai, google-ai-studio.
     * 
     */
    public Optional<Output<String>> adapter() {
        return Optional.ofNullable(this.adapter);
    }

    /**
     * Optional base URL override for the LLM provider API.
     * 
     */
    @Import(name="baseUrl")
    private @Nullable Output<String> baseUrl;

    /**
     * @return Optional base URL override for the LLM provider API.
     * 
     */
    public Optional<Output<String>> baseUrl() {
        return Optional.ofNullable(this.baseUrl);
    }

    /**
     * Adapter-specific configuration as a JSON string. Required for bedrock (`{&#34;region&#34;: &#34;&lt;aws-region&gt;&#34;}`), optional for openai (`{&#34;useResponsesApi&#34;: &lt;bool&gt;}`) and google-vertex-ai (`{&#34;location&#34;: &#34;&lt;gcp-location&gt;&#34;}`), and unsupported for other adapters. Computed, because the API returns any config the connection holds and offers no way to unset one.
     * 
     */
    @Import(name="config")
    private @Nullable Output<String> config;

    /**
     * @return Adapter-specific configuration as a JSON string. Required for bedrock (`{&#34;region&#34;: &#34;&lt;aws-region&gt;&#34;}`), optional for openai (`{&#34;useResponsesApi&#34;: &lt;bool&gt;}`) and google-vertex-ai (`{&#34;location&#34;: &#34;&lt;gcp-location&gt;&#34;}`), and unsupported for other adapters. Computed, because the API returns any config the connection holds and offers no way to unset one.
     * 
     */
    public Optional<Output<String>> config() {
        return Optional.ofNullable(this.config);
    }

    /**
     * Optional list of custom model identifiers.
     * 
     */
    @Import(name="customModels")
    private @Nullable Output<List<String>> customModels;

    /**
     * @return Optional list of custom model identifiers.
     * 
     */
    public Optional<Output<List<String>>> customModels() {
        return Optional.ofNullable(this.customModels);
    }

    /**
     * Optional map of additional HTTP headers for LLM API requests.
     * 
     */
    @Import(name="extraHeaders")
    private @Nullable Output<Map<String,String>> extraHeaders;

    /**
     * @return Optional map of additional HTTP headers for LLM API requests.
     * 
     */
    public Optional<Output<Map<String,String>>> extraHeaders() {
        return Optional.ofNullable(this.extraHeaders);
    }

    /**
     * The project public key used to authenticate API calls.
     * 
     */
    @Import(name="projectPublicKey")
    private @Nullable Output<String> projectPublicKey;

    /**
     * @return The project public key used to authenticate API calls.
     * 
     */
    public Optional<Output<String>> projectPublicKey() {
        return Optional.ofNullable(this.projectPublicKey);
    }

    /**
     * The project secret key used to authenticate API calls.
     * 
     */
    @Import(name="projectSecretKey")
    private @Nullable Output<String> projectSecretKey;

    /**
     * @return The project secret key used to authenticate API calls.
     * 
     */
    public Optional<Output<String>> projectSecretKey() {
        return Optional.ofNullable(this.projectSecretKey);
    }

    /**
     * The unique name identifying this LLM connection within the project. Changing this value destroys and recreates the resource, as the provider name is the upsert key.
     * 
     */
    @Import(name="providerName")
    private @Nullable Output<String> providerName;

    /**
     * @return The unique name identifying this LLM connection within the project. Changing this value destroys and recreates the resource, as the provider name is the upsert key.
     * 
     */
    public Optional<Output<String>> providerName() {
        return Optional.ofNullable(this.providerName);
    }

    /**
     * The API authentication key for the LLM provider.
     * 
     */
    @Import(name="secretKey")
    private @Nullable Output<String> secretKey;

    /**
     * @return The API authentication key for the LLM provider.
     * 
     */
    public Optional<Output<String>> secretKey() {
        return Optional.ofNullable(this.secretKey);
    }

    /**
     * Whether to include default models. Defaults to true if not set.
     * 
     */
    @Import(name="withDefaultModels")
    private @Nullable Output<Boolean> withDefaultModels;

    /**
     * @return Whether to include default models. Defaults to true if not set.
     * 
     */
    public Optional<Output<Boolean>> withDefaultModels() {
        return Optional.ofNullable(this.withDefaultModels);
    }

    private LlmConnectionState() {}

    private LlmConnectionState(LlmConnectionState $) {
        this.adapter = $.adapter;
        this.baseUrl = $.baseUrl;
        this.config = $.config;
        this.customModels = $.customModels;
        this.extraHeaders = $.extraHeaders;
        this.projectPublicKey = $.projectPublicKey;
        this.projectSecretKey = $.projectSecretKey;
        this.providerName = $.providerName;
        this.secretKey = $.secretKey;
        this.withDefaultModels = $.withDefaultModels;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(LlmConnectionState defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private LlmConnectionState $;

        public Builder() {
            $ = new LlmConnectionState();
        }

        public Builder(LlmConnectionState defaults) {
            $ = new LlmConnectionState(Objects.requireNonNull(defaults));
        }

        /**
         * @param adapter The LLM service type. Valid values: anthropic, openai, azure, bedrock, google-vertex-ai, google-ai-studio.
         * 
         * @return builder
         * 
         */
        public Builder adapter(@Nullable Output<String> adapter) {
            $.adapter = adapter;
            return this;
        }

        /**
         * @param adapter The LLM service type. Valid values: anthropic, openai, azure, bedrock, google-vertex-ai, google-ai-studio.
         * 
         * @return builder
         * 
         */
        public Builder adapter(String adapter) {
            return adapter(Output.of(adapter));
        }

        /**
         * @param baseUrl Optional base URL override for the LLM provider API.
         * 
         * @return builder
         * 
         */
        public Builder baseUrl(@Nullable Output<String> baseUrl) {
            $.baseUrl = baseUrl;
            return this;
        }

        /**
         * @param baseUrl Optional base URL override for the LLM provider API.
         * 
         * @return builder
         * 
         */
        public Builder baseUrl(String baseUrl) {
            return baseUrl(Output.of(baseUrl));
        }

        /**
         * @param config Adapter-specific configuration as a JSON string. Required for bedrock (`{&#34;region&#34;: &#34;&lt;aws-region&gt;&#34;}`), optional for openai (`{&#34;useResponsesApi&#34;: &lt;bool&gt;}`) and google-vertex-ai (`{&#34;location&#34;: &#34;&lt;gcp-location&gt;&#34;}`), and unsupported for other adapters. Computed, because the API returns any config the connection holds and offers no way to unset one.
         * 
         * @return builder
         * 
         */
        public Builder config(@Nullable Output<String> config) {
            $.config = config;
            return this;
        }

        /**
         * @param config Adapter-specific configuration as a JSON string. Required for bedrock (`{&#34;region&#34;: &#34;&lt;aws-region&gt;&#34;}`), optional for openai (`{&#34;useResponsesApi&#34;: &lt;bool&gt;}`) and google-vertex-ai (`{&#34;location&#34;: &#34;&lt;gcp-location&gt;&#34;}`), and unsupported for other adapters. Computed, because the API returns any config the connection holds and offers no way to unset one.
         * 
         * @return builder
         * 
         */
        public Builder config(String config) {
            return config(Output.of(config));
        }

        /**
         * @param customModels Optional list of custom model identifiers.
         * 
         * @return builder
         * 
         */
        public Builder customModels(@Nullable Output<List<String>> customModels) {
            $.customModels = customModels;
            return this;
        }

        /**
         * @param customModels Optional list of custom model identifiers.
         * 
         * @return builder
         * 
         */
        public Builder customModels(List<String> customModels) {
            return customModels(Output.of(customModels));
        }

        /**
         * @param customModels Optional list of custom model identifiers.
         * 
         * @return builder
         * 
         */
        public Builder customModels(String... customModels) {
            return customModels(List.of(customModels));
        }

        /**
         * @param extraHeaders Optional map of additional HTTP headers for LLM API requests.
         * 
         * @return builder
         * 
         */
        public Builder extraHeaders(@Nullable Output<Map<String,String>> extraHeaders) {
            $.extraHeaders = extraHeaders;
            return this;
        }

        /**
         * @param extraHeaders Optional map of additional HTTP headers for LLM API requests.
         * 
         * @return builder
         * 
         */
        public Builder extraHeaders(Map<String,String> extraHeaders) {
            return extraHeaders(Output.of(extraHeaders));
        }

        /**
         * @param projectPublicKey The project public key used to authenticate API calls.
         * 
         * @return builder
         * 
         */
        public Builder projectPublicKey(@Nullable Output<String> projectPublicKey) {
            $.projectPublicKey = projectPublicKey;
            return this;
        }

        /**
         * @param projectPublicKey The project public key used to authenticate API calls.
         * 
         * @return builder
         * 
         */
        public Builder projectPublicKey(String projectPublicKey) {
            return projectPublicKey(Output.of(projectPublicKey));
        }

        /**
         * @param projectSecretKey The project secret key used to authenticate API calls.
         * 
         * @return builder
         * 
         */
        public Builder projectSecretKey(@Nullable Output<String> projectSecretKey) {
            $.projectSecretKey = projectSecretKey;
            return this;
        }

        /**
         * @param projectSecretKey The project secret key used to authenticate API calls.
         * 
         * @return builder
         * 
         */
        public Builder projectSecretKey(String projectSecretKey) {
            return projectSecretKey(Output.of(projectSecretKey));
        }

        /**
         * @param providerName The unique name identifying this LLM connection within the project. Changing this value destroys and recreates the resource, as the provider name is the upsert key.
         * 
         * @return builder
         * 
         */
        public Builder providerName(@Nullable Output<String> providerName) {
            $.providerName = providerName;
            return this;
        }

        /**
         * @param providerName The unique name identifying this LLM connection within the project. Changing this value destroys and recreates the resource, as the provider name is the upsert key.
         * 
         * @return builder
         * 
         */
        public Builder providerName(String providerName) {
            return providerName(Output.of(providerName));
        }

        /**
         * @param secretKey The API authentication key for the LLM provider.
         * 
         * @return builder
         * 
         */
        public Builder secretKey(@Nullable Output<String> secretKey) {
            $.secretKey = secretKey;
            return this;
        }

        /**
         * @param secretKey The API authentication key for the LLM provider.
         * 
         * @return builder
         * 
         */
        public Builder secretKey(String secretKey) {
            return secretKey(Output.of(secretKey));
        }

        /**
         * @param withDefaultModels Whether to include default models. Defaults to true if not set.
         * 
         * @return builder
         * 
         */
        public Builder withDefaultModels(@Nullable Output<Boolean> withDefaultModels) {
            $.withDefaultModels = withDefaultModels;
            return this;
        }

        /**
         * @param withDefaultModels Whether to include default models. Defaults to true if not set.
         * 
         * @return builder
         * 
         */
        public Builder withDefaultModels(Boolean withDefaultModels) {
            return withDefaultModels(Output.of(withDefaultModels));
        }

        public LlmConnectionState build() {
            return $;
        }
    }

}
