// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.langfuse.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class OrganizationMembershipState extends com.pulumi.resources.ResourceArgs {

    public static final OrganizationMembershipState Empty = new OrganizationMembershipState();

    /**
     * The email address of the user to invite.
     * 
     */
    @Import(name="email")
    private @Nullable Output<String> email;

    /**
     * @return The email address of the user to invite.
     * 
     */
    public Optional<Output<String>> email() {
        return Optional.ofNullable(this.email);
    }

    /**
     * Organization private key to authenticate the call.
     * 
     */
    @Import(name="organizationPrivateKey")
    private @Nullable Output<String> organizationPrivateKey;

    /**
     * @return Organization private key to authenticate the call.
     * 
     */
    public Optional<Output<String>> organizationPrivateKey() {
        return Optional.ofNullable(this.organizationPrivateKey);
    }

    /**
     * Organization public key to authenticate the call.
     * 
     */
    @Import(name="organizationPublicKey")
    private @Nullable Output<String> organizationPublicKey;

    /**
     * @return Organization public key to authenticate the call.
     * 
     */
    public Optional<Output<String>> organizationPublicKey() {
        return Optional.ofNullable(this.organizationPublicKey);
    }

    /**
     * The role to assign to the user. Valid values are: ADMIN, MEMBER, VIEWER.
     * 
     */
    @Import(name="role")
    private @Nullable Output<String> role;

    /**
     * @return The role to assign to the user. Valid values are: ADMIN, MEMBER, VIEWER.
     * 
     */
    public Optional<Output<String>> role() {
        return Optional.ofNullable(this.role);
    }

    /**
     * The status of the membership invitation.
     * 
     */
    @Import(name="status")
    private @Nullable Output<String> status;

    /**
     * @return The status of the membership invitation.
     * 
     */
    public Optional<Output<String>> status() {
        return Optional.ofNullable(this.status);
    }

    /**
     * The unique identifier of the user.
     * 
     */
    @Import(name="userId")
    private @Nullable Output<String> userId;

    /**
     * @return The unique identifier of the user.
     * 
     */
    public Optional<Output<String>> userId() {
        return Optional.ofNullable(this.userId);
    }

    /**
     * The username of the user.
     * 
     */
    @Import(name="username")
    private @Nullable Output<String> username;

    /**
     * @return The username of the user.
     * 
     */
    public Optional<Output<String>> username() {
        return Optional.ofNullable(this.username);
    }

    private OrganizationMembershipState() {}

    private OrganizationMembershipState(OrganizationMembershipState $) {
        this.email = $.email;
        this.organizationPrivateKey = $.organizationPrivateKey;
        this.organizationPublicKey = $.organizationPublicKey;
        this.role = $.role;
        this.status = $.status;
        this.userId = $.userId;
        this.username = $.username;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(OrganizationMembershipState defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private OrganizationMembershipState $;

        public Builder() {
            $ = new OrganizationMembershipState();
        }

        public Builder(OrganizationMembershipState defaults) {
            $ = new OrganizationMembershipState(Objects.requireNonNull(defaults));
        }

        /**
         * @param email The email address of the user to invite.
         * 
         * @return builder
         * 
         */
        public Builder email(@Nullable Output<String> email) {
            $.email = email;
            return this;
        }

        /**
         * @param email The email address of the user to invite.
         * 
         * @return builder
         * 
         */
        public Builder email(String email) {
            return email(Output.of(email));
        }

        /**
         * @param organizationPrivateKey Organization private key to authenticate the call.
         * 
         * @return builder
         * 
         */
        public Builder organizationPrivateKey(@Nullable Output<String> organizationPrivateKey) {
            $.organizationPrivateKey = organizationPrivateKey;
            return this;
        }

        /**
         * @param organizationPrivateKey Organization private key to authenticate the call.
         * 
         * @return builder
         * 
         */
        public Builder organizationPrivateKey(String organizationPrivateKey) {
            return organizationPrivateKey(Output.of(organizationPrivateKey));
        }

        /**
         * @param organizationPublicKey Organization public key to authenticate the call.
         * 
         * @return builder
         * 
         */
        public Builder organizationPublicKey(@Nullable Output<String> organizationPublicKey) {
            $.organizationPublicKey = organizationPublicKey;
            return this;
        }

        /**
         * @param organizationPublicKey Organization public key to authenticate the call.
         * 
         * @return builder
         * 
         */
        public Builder organizationPublicKey(String organizationPublicKey) {
            return organizationPublicKey(Output.of(organizationPublicKey));
        }

        /**
         * @param role The role to assign to the user. Valid values are: ADMIN, MEMBER, VIEWER.
         * 
         * @return builder
         * 
         */
        public Builder role(@Nullable Output<String> role) {
            $.role = role;
            return this;
        }

        /**
         * @param role The role to assign to the user. Valid values are: ADMIN, MEMBER, VIEWER.
         * 
         * @return builder
         * 
         */
        public Builder role(String role) {
            return role(Output.of(role));
        }

        /**
         * @param status The status of the membership invitation.
         * 
         * @return builder
         * 
         */
        public Builder status(@Nullable Output<String> status) {
            $.status = status;
            return this;
        }

        /**
         * @param status The status of the membership invitation.
         * 
         * @return builder
         * 
         */
        public Builder status(String status) {
            return status(Output.of(status));
        }

        /**
         * @param userId The unique identifier of the user.
         * 
         * @return builder
         * 
         */
        public Builder userId(@Nullable Output<String> userId) {
            $.userId = userId;
            return this;
        }

        /**
         * @param userId The unique identifier of the user.
         * 
         * @return builder
         * 
         */
        public Builder userId(String userId) {
            return userId(Output.of(userId));
        }

        /**
         * @param username The username of the user.
         * 
         * @return builder
         * 
         */
        public Builder username(@Nullable Output<String> username) {
            $.username = username;
            return this;
        }

        /**
         * @param username The username of the user.
         * 
         * @return builder
         * 
         */
        public Builder username(String username) {
            return username(Output.of(username));
        }

        public OrganizationMembershipState build() {
            return $;
        }
    }

}
