// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.langfuse.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class OrganizationApiKeyState extends com.pulumi.resources.ResourceArgs {

    public static final OrganizationApiKeyState Empty = new OrganizationApiKeyState();

    /**
     * The Langfuse organization the key belongs to.
     * 
     */
    @Import(name="organizationId")
    private @Nullable Output<String> organizationId;

    /**
     * @return The Langfuse organization the key belongs to.
     * 
     */
    public Optional<Output<String>> organizationId() {
        return Optional.ofNullable(this.organizationId);
    }

    /**
     * The public value of the API key (only returned at creation time).
     * 
     */
    @Import(name="publicKey")
    private @Nullable Output<String> publicKey;

    /**
     * @return The public value of the API key (only returned at creation time).
     * 
     */
    public Optional<Output<String>> publicKey() {
        return Optional.ofNullable(this.publicKey);
    }

    /**
     * The secret value of the API key (only returned at creation time).
     * 
     */
    @Import(name="secretKey")
    private @Nullable Output<String> secretKey;

    /**
     * @return The secret value of the API key (only returned at creation time).
     * 
     */
    public Optional<Output<String>> secretKey() {
        return Optional.ofNullable(this.secretKey);
    }

    private OrganizationApiKeyState() {}

    private OrganizationApiKeyState(OrganizationApiKeyState $) {
        this.organizationId = $.organizationId;
        this.publicKey = $.publicKey;
        this.secretKey = $.secretKey;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(OrganizationApiKeyState defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private OrganizationApiKeyState $;

        public Builder() {
            $ = new OrganizationApiKeyState();
        }

        public Builder(OrganizationApiKeyState defaults) {
            $ = new OrganizationApiKeyState(Objects.requireNonNull(defaults));
        }

        /**
         * @param organizationId The Langfuse organization the key belongs to.
         * 
         * @return builder
         * 
         */
        public Builder organizationId(@Nullable Output<String> organizationId) {
            $.organizationId = organizationId;
            return this;
        }

        /**
         * @param organizationId The Langfuse organization the key belongs to.
         * 
         * @return builder
         * 
         */
        public Builder organizationId(String organizationId) {
            return organizationId(Output.of(organizationId));
        }

        /**
         * @param publicKey The public value of the API key (only returned at creation time).
         * 
         * @return builder
         * 
         */
        public Builder publicKey(@Nullable Output<String> publicKey) {
            $.publicKey = publicKey;
            return this;
        }

        /**
         * @param publicKey The public value of the API key (only returned at creation time).
         * 
         * @return builder
         * 
         */
        public Builder publicKey(String publicKey) {
            return publicKey(Output.of(publicKey));
        }

        /**
         * @param secretKey The secret value of the API key (only returned at creation time).
         * 
         * @return builder
         * 
         */
        public Builder secretKey(@Nullable Output<String> secretKey) {
            $.secretKey = secretKey;
            return this;
        }

        /**
         * @param secretKey The secret value of the API key (only returned at creation time).
         * 
         * @return builder
         * 
         */
        public Builder secretKey(String secretKey) {
            return secretKey(Output.of(secretKey));
        }

        public OrganizationApiKeyState build() {
            return $;
        }
    }

}
