// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.langfuse.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class ProjectApiKeyState extends com.pulumi.resources.ResourceArgs {

    public static final ProjectApiKeyState Empty = new ProjectApiKeyState();

    /**
     * Optional note for the API key (POST /api/public/projects/{projectId}/apiKeys). Because the Langfuse public API only accepts a note at creation time, changing this attribute forces replacement: the old key is deleted and a new one is created (new id and credentials).
     * 
     */
    @Import(name="note")
    private @Nullable Output<String> note;

    /**
     * @return Optional note for the API key (POST /api/public/projects/{projectId}/apiKeys). Because the Langfuse public API only accepts a note at creation time, changing this attribute forces replacement: the old key is deleted and a new one is created (new id and credentials).
     * 
     */
    public Optional<Output<String>> note() {
        return Optional.ofNullable(this.note);
    }

    /**
     * Organization private key to authenticate the call.
     * 
     */
    @Import(name="organizationPrivateKey")
    private @Nullable Output<String> organizationPrivateKey;

    /**
     * @return Organization private key to authenticate the call.
     * 
     */
    public Optional<Output<String>> organizationPrivateKey() {
        return Optional.ofNullable(this.organizationPrivateKey);
    }

    /**
     * Organization public key to authenticate the call.
     * 
     */
    @Import(name="organizationPublicKey")
    private @Nullable Output<String> organizationPublicKey;

    /**
     * @return Organization public key to authenticate the call.
     * 
     */
    public Optional<Output<String>> organizationPublicKey() {
        return Optional.ofNullable(this.organizationPublicKey);
    }

    /**
     * The ID of the project the key belongs to.
     * 
     */
    @Import(name="projectId")
    private @Nullable Output<String> projectId;

    /**
     * @return The ID of the project the key belongs to.
     * 
     */
    public Optional<Output<String>> projectId() {
        return Optional.ofNullable(this.projectId);
    }

    /**
     * The public value of the API key (only returned at creation time).
     * 
     */
    @Import(name="publicKey")
    private @Nullable Output<String> publicKey;

    /**
     * @return The public value of the API key (only returned at creation time).
     * 
     */
    public Optional<Output<String>> publicKey() {
        return Optional.ofNullable(this.publicKey);
    }

    /**
     * The secret value of the API key (only returned at creation time).
     * 
     */
    @Import(name="secretKey")
    private @Nullable Output<String> secretKey;

    /**
     * @return The secret value of the API key (only returned at creation time).
     * 
     */
    public Optional<Output<String>> secretKey() {
        return Optional.ofNullable(this.secretKey);
    }

    private ProjectApiKeyState() {}

    private ProjectApiKeyState(ProjectApiKeyState $) {
        this.note = $.note;
        this.organizationPrivateKey = $.organizationPrivateKey;
        this.organizationPublicKey = $.organizationPublicKey;
        this.projectId = $.projectId;
        this.publicKey = $.publicKey;
        this.secretKey = $.secretKey;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(ProjectApiKeyState defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private ProjectApiKeyState $;

        public Builder() {
            $ = new ProjectApiKeyState();
        }

        public Builder(ProjectApiKeyState defaults) {
            $ = new ProjectApiKeyState(Objects.requireNonNull(defaults));
        }

        /**
         * @param note Optional note for the API key (POST /api/public/projects/{projectId}/apiKeys). Because the Langfuse public API only accepts a note at creation time, changing this attribute forces replacement: the old key is deleted and a new one is created (new id and credentials).
         * 
         * @return builder
         * 
         */
        public Builder note(@Nullable Output<String> note) {
            $.note = note;
            return this;
        }

        /**
         * @param note Optional note for the API key (POST /api/public/projects/{projectId}/apiKeys). Because the Langfuse public API only accepts a note at creation time, changing this attribute forces replacement: the old key is deleted and a new one is created (new id and credentials).
         * 
         * @return builder
         * 
         */
        public Builder note(String note) {
            return note(Output.of(note));
        }

        /**
         * @param organizationPrivateKey Organization private key to authenticate the call.
         * 
         * @return builder
         * 
         */
        public Builder organizationPrivateKey(@Nullable Output<String> organizationPrivateKey) {
            $.organizationPrivateKey = organizationPrivateKey;
            return this;
        }

        /**
         * @param organizationPrivateKey Organization private key to authenticate the call.
         * 
         * @return builder
         * 
         */
        public Builder organizationPrivateKey(String organizationPrivateKey) {
            return organizationPrivateKey(Output.of(organizationPrivateKey));
        }

        /**
         * @param organizationPublicKey Organization public key to authenticate the call.
         * 
         * @return builder
         * 
         */
        public Builder organizationPublicKey(@Nullable Output<String> organizationPublicKey) {
            $.organizationPublicKey = organizationPublicKey;
            return this;
        }

        /**
         * @param organizationPublicKey Organization public key to authenticate the call.
         * 
         * @return builder
         * 
         */
        public Builder organizationPublicKey(String organizationPublicKey) {
            return organizationPublicKey(Output.of(organizationPublicKey));
        }

        /**
         * @param projectId The ID of the project the key belongs to.
         * 
         * @return builder
         * 
         */
        public Builder projectId(@Nullable Output<String> projectId) {
            $.projectId = projectId;
            return this;
        }

        /**
         * @param projectId The ID of the project the key belongs to.
         * 
         * @return builder
         * 
         */
        public Builder projectId(String projectId) {
            return projectId(Output.of(projectId));
        }

        /**
         * @param publicKey The public value of the API key (only returned at creation time).
         * 
         * @return builder
         * 
         */
        public Builder publicKey(@Nullable Output<String> publicKey) {
            $.publicKey = publicKey;
            return this;
        }

        /**
         * @param publicKey The public value of the API key (only returned at creation time).
         * 
         * @return builder
         * 
         */
        public Builder publicKey(String publicKey) {
            return publicKey(Output.of(publicKey));
        }

        /**
         * @param secretKey The secret value of the API key (only returned at creation time).
         * 
         * @return builder
         * 
         */
        public Builder secretKey(@Nullable Output<String> secretKey) {
            $.secretKey = secretKey;
            return this;
        }

        /**
         * @param secretKey The secret value of the API key (only returned at creation time).
         * 
         * @return builder
         * 
         */
        public Builder secretKey(String secretKey) {
            return secretKey(Output.of(secretKey));
        }

        public ProjectApiKeyState build() {
            return $;
        }
    }

}
