// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.langfuse;

import com.pulumi.core.internal.Codegen;
import java.lang.String;
import java.util.Optional;

public final class Config {

    private static final com.pulumi.Config config = com.pulumi.Config.of("langfuse");
/**
 * Admin API key. Only needed when managing organizations. Can also come from LANGFUSE_ADMIN_KEY.
 * 
 */
    public Optional<String> adminApiKey() {
        return Codegen.stringProp("adminApiKey").config(config).get();
    }
/**
 * Base URI of the Langfuse instance (defaults to https://app.langfuse.com).
 * 
 */
    public Optional<String> host() {
        return Codegen.stringProp("host").config(config).get();
    }
/**
 * Hostname to verify the TLS certificate against, also sent as the SNI value. Set this when the instance is reached through a port forward or tunnel, where the host above (typically localhost) cannot match the certificate. Certificate verification remains enabled.
 * 
 */
    public Optional<String> tlsServerName() {
        return Codegen.stringProp("tlsServerName").config(config).get();
    }
}
