// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.langfuse;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import com.pulumi.langfuse.LlmConnectionArgs;
import com.pulumi.langfuse.Utilities;
import com.pulumi.langfuse.inputs.LlmConnectionState;
import java.lang.Boolean;
import java.lang.String;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import javax.annotation.Nullable;

@ResourceType(type="langfuse:index/llmConnection:LlmConnection")
public class LlmConnection extends com.pulumi.resources.CustomResource {
    /**
     * The LLM service type. Valid values: anthropic, openai, azure, bedrock, google-vertex-ai, google-ai-studio.
     * 
     */
    @Export(name="adapter", refs={String.class}, tree="[0]")
    private Output<String> adapter;

    /**
     * @return The LLM service type. Valid values: anthropic, openai, azure, bedrock, google-vertex-ai, google-ai-studio.
     * 
     */
    public Output<String> adapter() {
        return this.adapter;
    }
    /**
     * Optional base URL override for the LLM provider API.
     * 
     */
    @Export(name="baseUrl", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> baseUrl;

    /**
     * @return Optional base URL override for the LLM provider API.
     * 
     */
    public Output<Optional<String>> baseUrl() {
        return Codegen.optional(this.baseUrl);
    }
    /**
     * Adapter-specific configuration as a JSON string. Required for bedrock (`{&#34;region&#34;: &#34;&lt;aws-region&gt;&#34;}`), optional for openai (`{&#34;useResponsesApi&#34;: &lt;bool&gt;}`) and google-vertex-ai (`{&#34;location&#34;: &#34;&lt;gcp-location&gt;&#34;}`), and unsupported for other adapters. Computed, because the API returns any config the connection holds and offers no way to unset one.
     * 
     */
    @Export(name="config", refs={String.class}, tree="[0]")
    private Output<String> config;

    /**
     * @return Adapter-specific configuration as a JSON string. Required for bedrock (`{&#34;region&#34;: &#34;&lt;aws-region&gt;&#34;}`), optional for openai (`{&#34;useResponsesApi&#34;: &lt;bool&gt;}`) and google-vertex-ai (`{&#34;location&#34;: &#34;&lt;gcp-location&gt;&#34;}`), and unsupported for other adapters. Computed, because the API returns any config the connection holds and offers no way to unset one.
     * 
     */
    public Output<String> config() {
        return this.config;
    }
    /**
     * Optional list of custom model identifiers.
     * 
     */
    @Export(name="customModels", refs={List.class,String.class}, tree="[0,1]")
    private Output</* @Nullable */ List<String>> customModels;

    /**
     * @return Optional list of custom model identifiers.
     * 
     */
    public Output<Optional<List<String>>> customModels() {
        return Codegen.optional(this.customModels);
    }
    /**
     * Optional map of additional HTTP headers for LLM API requests.
     * 
     */
    @Export(name="extraHeaders", refs={Map.class,String.class}, tree="[0,1,1]")
    private Output</* @Nullable */ Map<String,String>> extraHeaders;

    /**
     * @return Optional map of additional HTTP headers for LLM API requests.
     * 
     */
    public Output<Optional<Map<String,String>>> extraHeaders() {
        return Codegen.optional(this.extraHeaders);
    }
    /**
     * The project public key used to authenticate API calls.
     * 
     */
    @Export(name="projectPublicKey", refs={String.class}, tree="[0]")
    private Output<String> projectPublicKey;

    /**
     * @return The project public key used to authenticate API calls.
     * 
     */
    public Output<String> projectPublicKey() {
        return this.projectPublicKey;
    }
    /**
     * The project secret key used to authenticate API calls.
     * 
     */
    @Export(name="projectSecretKey", refs={String.class}, tree="[0]")
    private Output<String> projectSecretKey;

    /**
     * @return The project secret key used to authenticate API calls.
     * 
     */
    public Output<String> projectSecretKey() {
        return this.projectSecretKey;
    }
    /**
     * The unique name identifying this LLM connection within the project. Changing this value destroys and recreates the resource, as the provider name is the upsert key.
     * 
     */
    @Export(name="providerName", refs={String.class}, tree="[0]")
    private Output<String> providerName;

    /**
     * @return The unique name identifying this LLM connection within the project. Changing this value destroys and recreates the resource, as the provider name is the upsert key.
     * 
     */
    public Output<String> providerName() {
        return this.providerName;
    }
    /**
     * The API authentication key for the LLM provider.
     * 
     */
    @Export(name="secretKey", refs={String.class}, tree="[0]")
    private Output<String> secretKey;

    /**
     * @return The API authentication key for the LLM provider.
     * 
     */
    public Output<String> secretKey() {
        return this.secretKey;
    }
    /**
     * Whether to include default models. Defaults to true if not set.
     * 
     */
    @Export(name="withDefaultModels", refs={Boolean.class}, tree="[0]")
    private Output<Boolean> withDefaultModels;

    /**
     * @return Whether to include default models. Defaults to true if not set.
     * 
     */
    public Output<Boolean> withDefaultModels() {
        return this.withDefaultModels;
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public LlmConnection(java.lang.String name) {
        this(name, LlmConnectionArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public LlmConnection(java.lang.String name, LlmConnectionArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public LlmConnection(java.lang.String name, LlmConnectionArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("langfuse:index/llmConnection:LlmConnection", name, makeArgs(args, options), makeResourceOptions(options, Codegen.empty()), false, Utilities.getPackageRef());
    }

    private LlmConnection(java.lang.String name, Output<java.lang.String> id, @Nullable LlmConnectionState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("langfuse:index/llmConnection:LlmConnection", name, state, makeResourceOptions(options, id), false, Utilities.getPackageRef());
    }

    private static LlmConnectionArgs makeArgs(LlmConnectionArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        if (options != null && options.getUrn().isPresent()) {
            return null;
        }
        return args == null ? LlmConnectionArgs.Empty : args;
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<java.lang.String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .additionalSecretOutputs(List.of(
                "extraHeaders",
                "projectPublicKey",
                "projectSecretKey",
                "secretKey"
            ))
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static LlmConnection get(java.lang.String name, Output<java.lang.String> id, @Nullable LlmConnectionState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new LlmConnection(name, id, state, options);
    }
}
