// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.langfuse;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import com.pulumi.langfuse.OrganizationMembershipArgs;
import com.pulumi.langfuse.Utilities;
import com.pulumi.langfuse.inputs.OrganizationMembershipState;
import java.lang.String;
import java.util.List;
import javax.annotation.Nullable;

@ResourceType(type="langfuse:index/organizationMembership:OrganizationMembership")
public class OrganizationMembership extends com.pulumi.resources.CustomResource {
    /**
     * The email address of the user to invite.
     * 
     */
    @Export(name="email", refs={String.class}, tree="[0]")
    private Output<String> email;

    /**
     * @return The email address of the user to invite.
     * 
     */
    public Output<String> email() {
        return this.email;
    }
    /**
     * Organization private key to authenticate the call.
     * 
     */
    @Export(name="organizationPrivateKey", refs={String.class}, tree="[0]")
    private Output<String> organizationPrivateKey;

    /**
     * @return Organization private key to authenticate the call.
     * 
     */
    public Output<String> organizationPrivateKey() {
        return this.organizationPrivateKey;
    }
    /**
     * Organization public key to authenticate the call.
     * 
     */
    @Export(name="organizationPublicKey", refs={String.class}, tree="[0]")
    private Output<String> organizationPublicKey;

    /**
     * @return Organization public key to authenticate the call.
     * 
     */
    public Output<String> organizationPublicKey() {
        return this.organizationPublicKey;
    }
    /**
     * The role to assign to the user. Valid values are: ADMIN, MEMBER, VIEWER.
     * 
     */
    @Export(name="role", refs={String.class}, tree="[0]")
    private Output<String> role;

    /**
     * @return The role to assign to the user. Valid values are: ADMIN, MEMBER, VIEWER.
     * 
     */
    public Output<String> role() {
        return this.role;
    }
    /**
     * The status of the membership invitation.
     * 
     */
    @Export(name="status", refs={String.class}, tree="[0]")
    private Output<String> status;

    /**
     * @return The status of the membership invitation.
     * 
     */
    public Output<String> status() {
        return this.status;
    }
    /**
     * The unique identifier of the user.
     * 
     */
    @Export(name="userId", refs={String.class}, tree="[0]")
    private Output<String> userId;

    /**
     * @return The unique identifier of the user.
     * 
     */
    public Output<String> userId() {
        return this.userId;
    }
    /**
     * The username of the user.
     * 
     */
    @Export(name="username", refs={String.class}, tree="[0]")
    private Output<String> username;

    /**
     * @return The username of the user.
     * 
     */
    public Output<String> username() {
        return this.username;
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public OrganizationMembership(java.lang.String name) {
        this(name, OrganizationMembershipArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public OrganizationMembership(java.lang.String name, OrganizationMembershipArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public OrganizationMembership(java.lang.String name, OrganizationMembershipArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("langfuse:index/organizationMembership:OrganizationMembership", name, makeArgs(args, options), makeResourceOptions(options, Codegen.empty()), false, Utilities.getPackageRef());
    }

    private OrganizationMembership(java.lang.String name, Output<java.lang.String> id, @Nullable OrganizationMembershipState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("langfuse:index/organizationMembership:OrganizationMembership", name, state, makeResourceOptions(options, id), false, Utilities.getPackageRef());
    }

    private static OrganizationMembershipArgs makeArgs(OrganizationMembershipArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        if (options != null && options.getUrn().isPresent()) {
            return null;
        }
        return args == null ? OrganizationMembershipArgs.Empty : args;
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<java.lang.String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .additionalSecretOutputs(List.of(
                "organizationPrivateKey",
                "organizationPublicKey"
            ))
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static OrganizationMembership get(java.lang.String name, Output<java.lang.String> id, @Nullable OrganizationMembershipState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new OrganizationMembership(name, id, state, options);
    }
}
