// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.langfuse;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;


public final class OrganizationMembershipArgs extends com.pulumi.resources.ResourceArgs {

    public static final OrganizationMembershipArgs Empty = new OrganizationMembershipArgs();

    /**
     * The email address of the user to invite.
     * 
     */
    @Import(name="email", required=true)
    private Output<String> email;

    /**
     * @return The email address of the user to invite.
     * 
     */
    public Output<String> email() {
        return this.email;
    }

    /**
     * Organization private key to authenticate the call.
     * 
     */
    @Import(name="organizationPrivateKey", required=true)
    private Output<String> organizationPrivateKey;

    /**
     * @return Organization private key to authenticate the call.
     * 
     */
    public Output<String> organizationPrivateKey() {
        return this.organizationPrivateKey;
    }

    /**
     * Organization public key to authenticate the call.
     * 
     */
    @Import(name="organizationPublicKey", required=true)
    private Output<String> organizationPublicKey;

    /**
     * @return Organization public key to authenticate the call.
     * 
     */
    public Output<String> organizationPublicKey() {
        return this.organizationPublicKey;
    }

    /**
     * The role to assign to the user. Valid values are: ADMIN, MEMBER, VIEWER.
     * 
     */
    @Import(name="role", required=true)
    private Output<String> role;

    /**
     * @return The role to assign to the user. Valid values are: ADMIN, MEMBER, VIEWER.
     * 
     */
    public Output<String> role() {
        return this.role;
    }

    private OrganizationMembershipArgs() {}

    private OrganizationMembershipArgs(OrganizationMembershipArgs $) {
        this.email = $.email;
        this.organizationPrivateKey = $.organizationPrivateKey;
        this.organizationPublicKey = $.organizationPublicKey;
        this.role = $.role;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(OrganizationMembershipArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private OrganizationMembershipArgs $;

        public Builder() {
            $ = new OrganizationMembershipArgs();
        }

        public Builder(OrganizationMembershipArgs defaults) {
            $ = new OrganizationMembershipArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param email The email address of the user to invite.
         * 
         * @return builder
         * 
         */
        public Builder email(Output<String> email) {
            $.email = email;
            return this;
        }

        /**
         * @param email The email address of the user to invite.
         * 
         * @return builder
         * 
         */
        public Builder email(String email) {
            return email(Output.of(email));
        }

        /**
         * @param organizationPrivateKey Organization private key to authenticate the call.
         * 
         * @return builder
         * 
         */
        public Builder organizationPrivateKey(Output<String> organizationPrivateKey) {
            $.organizationPrivateKey = organizationPrivateKey;
            return this;
        }

        /**
         * @param organizationPrivateKey Organization private key to authenticate the call.
         * 
         * @return builder
         * 
         */
        public Builder organizationPrivateKey(String organizationPrivateKey) {
            return organizationPrivateKey(Output.of(organizationPrivateKey));
        }

        /**
         * @param organizationPublicKey Organization public key to authenticate the call.
         * 
         * @return builder
         * 
         */
        public Builder organizationPublicKey(Output<String> organizationPublicKey) {
            $.organizationPublicKey = organizationPublicKey;
            return this;
        }

        /**
         * @param organizationPublicKey Organization public key to authenticate the call.
         * 
         * @return builder
         * 
         */
        public Builder organizationPublicKey(String organizationPublicKey) {
            return organizationPublicKey(Output.of(organizationPublicKey));
        }

        /**
         * @param role The role to assign to the user. Valid values are: ADMIN, MEMBER, VIEWER.
         * 
         * @return builder
         * 
         */
        public Builder role(Output<String> role) {
            $.role = role;
            return this;
        }

        /**
         * @param role The role to assign to the user. Valid values are: ADMIN, MEMBER, VIEWER.
         * 
         * @return builder
         * 
         */
        public Builder role(String role) {
            return role(Output.of(role));
        }

        public OrganizationMembershipArgs build() {
            if ($.email == null) {
                throw new MissingRequiredPropertyException("OrganizationMembershipArgs", "email");
            }
            if ($.organizationPrivateKey == null) {
                throw new MissingRequiredPropertyException("OrganizationMembershipArgs", "organizationPrivateKey");
            }
            if ($.organizationPublicKey == null) {
                throw new MissingRequiredPropertyException("OrganizationMembershipArgs", "organizationPublicKey");
            }
            if ($.role == null) {
                throw new MissingRequiredPropertyException("OrganizationMembershipArgs", "role");
            }
            return $;
        }
    }

}
