// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.langfuse;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;


public final class OrganizationApiKeyArgs extends com.pulumi.resources.ResourceArgs {

    public static final OrganizationApiKeyArgs Empty = new OrganizationApiKeyArgs();

    /**
     * The Langfuse organization the key belongs to.
     * 
     */
    @Import(name="organizationId", required=true)
    private Output<String> organizationId;

    /**
     * @return The Langfuse organization the key belongs to.
     * 
     */
    public Output<String> organizationId() {
        return this.organizationId;
    }

    private OrganizationApiKeyArgs() {}

    private OrganizationApiKeyArgs(OrganizationApiKeyArgs $) {
        this.organizationId = $.organizationId;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(OrganizationApiKeyArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private OrganizationApiKeyArgs $;

        public Builder() {
            $ = new OrganizationApiKeyArgs();
        }

        public Builder(OrganizationApiKeyArgs defaults) {
            $ = new OrganizationApiKeyArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param organizationId The Langfuse organization the key belongs to.
         * 
         * @return builder
         * 
         */
        public Builder organizationId(Output<String> organizationId) {
            $.organizationId = organizationId;
            return this;
        }

        /**
         * @param organizationId The Langfuse organization the key belongs to.
         * 
         * @return builder
         * 
         */
        public Builder organizationId(String organizationId) {
            return organizationId(Output.of(organizationId));
        }

        public OrganizationApiKeyArgs build() {
            if ($.organizationId == null) {
                throw new MissingRequiredPropertyException("OrganizationApiKeyArgs", "organizationId");
            }
            return $;
        }
    }

}
