// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.langfuse;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import com.pulumi.langfuse.OrganizationApiKeyArgs;
import com.pulumi.langfuse.Utilities;
import com.pulumi.langfuse.inputs.OrganizationApiKeyState;
import java.lang.String;
import java.util.List;
import javax.annotation.Nullable;

@ResourceType(type="langfuse:index/organizationApiKey:OrganizationApiKey")
public class OrganizationApiKey extends com.pulumi.resources.CustomResource {
    /**
     * The Langfuse organization the key belongs to.
     * 
     */
    @Export(name="organizationId", refs={String.class}, tree="[0]")
    private Output<String> organizationId;

    /**
     * @return The Langfuse organization the key belongs to.
     * 
     */
    public Output<String> organizationId() {
        return this.organizationId;
    }
    /**
     * The public value of the API key (only returned at creation time).
     * 
     */
    @Export(name="publicKey", refs={String.class}, tree="[0]")
    private Output<String> publicKey;

    /**
     * @return The public value of the API key (only returned at creation time).
     * 
     */
    public Output<String> publicKey() {
        return this.publicKey;
    }
    /**
     * The secret value of the API key (only returned at creation time).
     * 
     */
    @Export(name="secretKey", refs={String.class}, tree="[0]")
    private Output<String> secretKey;

    /**
     * @return The secret value of the API key (only returned at creation time).
     * 
     */
    public Output<String> secretKey() {
        return this.secretKey;
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public OrganizationApiKey(java.lang.String name) {
        this(name, OrganizationApiKeyArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public OrganizationApiKey(java.lang.String name, OrganizationApiKeyArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public OrganizationApiKey(java.lang.String name, OrganizationApiKeyArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("langfuse:index/organizationApiKey:OrganizationApiKey", name, makeArgs(args, options), makeResourceOptions(options, Codegen.empty()), false, Utilities.getPackageRef());
    }

    private OrganizationApiKey(java.lang.String name, Output<java.lang.String> id, @Nullable OrganizationApiKeyState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("langfuse:index/organizationApiKey:OrganizationApiKey", name, state, makeResourceOptions(options, id), false, Utilities.getPackageRef());
    }

    private static OrganizationApiKeyArgs makeArgs(OrganizationApiKeyArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        if (options != null && options.getUrn().isPresent()) {
            return null;
        }
        return args == null ? OrganizationApiKeyArgs.Empty : args;
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<java.lang.String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .additionalSecretOutputs(List.of(
                "publicKey",
                "secretKey"
            ))
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static OrganizationApiKey get(java.lang.String name, Output<java.lang.String> id, @Nullable OrganizationApiKeyState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new OrganizationApiKey(name, id, state, options);
    }
}
