// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.langfuse;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class ProjectApiKeyArgs extends com.pulumi.resources.ResourceArgs {

    public static final ProjectApiKeyArgs Empty = new ProjectApiKeyArgs();

    /**
     * Optional note for the API key (POST /api/public/projects/{projectId}/apiKeys). Because the Langfuse public API only accepts a note at creation time, changing this attribute forces replacement: the old key is deleted and a new one is created (new id and credentials).
     * 
     */
    @Import(name="note")
    private @Nullable Output<String> note;

    /**
     * @return Optional note for the API key (POST /api/public/projects/{projectId}/apiKeys). Because the Langfuse public API only accepts a note at creation time, changing this attribute forces replacement: the old key is deleted and a new one is created (new id and credentials).
     * 
     */
    public Optional<Output<String>> note() {
        return Optional.ofNullable(this.note);
    }

    /**
     * Organization private key to authenticate the call.
     * 
     */
    @Import(name="organizationPrivateKey", required=true)
    private Output<String> organizationPrivateKey;

    /**
     * @return Organization private key to authenticate the call.
     * 
     */
    public Output<String> organizationPrivateKey() {
        return this.organizationPrivateKey;
    }

    /**
     * Organization public key to authenticate the call.
     * 
     */
    @Import(name="organizationPublicKey", required=true)
    private Output<String> organizationPublicKey;

    /**
     * @return Organization public key to authenticate the call.
     * 
     */
    public Output<String> organizationPublicKey() {
        return this.organizationPublicKey;
    }

    /**
     * The ID of the project the key belongs to.
     * 
     */
    @Import(name="projectId", required=true)
    private Output<String> projectId;

    /**
     * @return The ID of the project the key belongs to.
     * 
     */
    public Output<String> projectId() {
        return this.projectId;
    }

    private ProjectApiKeyArgs() {}

    private ProjectApiKeyArgs(ProjectApiKeyArgs $) {
        this.note = $.note;
        this.organizationPrivateKey = $.organizationPrivateKey;
        this.organizationPublicKey = $.organizationPublicKey;
        this.projectId = $.projectId;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(ProjectApiKeyArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private ProjectApiKeyArgs $;

        public Builder() {
            $ = new ProjectApiKeyArgs();
        }

        public Builder(ProjectApiKeyArgs defaults) {
            $ = new ProjectApiKeyArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param note Optional note for the API key (POST /api/public/projects/{projectId}/apiKeys). Because the Langfuse public API only accepts a note at creation time, changing this attribute forces replacement: the old key is deleted and a new one is created (new id and credentials).
         * 
         * @return builder
         * 
         */
        public Builder note(@Nullable Output<String> note) {
            $.note = note;
            return this;
        }

        /**
         * @param note Optional note for the API key (POST /api/public/projects/{projectId}/apiKeys). Because the Langfuse public API only accepts a note at creation time, changing this attribute forces replacement: the old key is deleted and a new one is created (new id and credentials).
         * 
         * @return builder
         * 
         */
        public Builder note(String note) {
            return note(Output.of(note));
        }

        /**
         * @param organizationPrivateKey Organization private key to authenticate the call.
         * 
         * @return builder
         * 
         */
        public Builder organizationPrivateKey(Output<String> organizationPrivateKey) {
            $.organizationPrivateKey = organizationPrivateKey;
            return this;
        }

        /**
         * @param organizationPrivateKey Organization private key to authenticate the call.
         * 
         * @return builder
         * 
         */
        public Builder organizationPrivateKey(String organizationPrivateKey) {
            return organizationPrivateKey(Output.of(organizationPrivateKey));
        }

        /**
         * @param organizationPublicKey Organization public key to authenticate the call.
         * 
         * @return builder
         * 
         */
        public Builder organizationPublicKey(Output<String> organizationPublicKey) {
            $.organizationPublicKey = organizationPublicKey;
            return this;
        }

        /**
         * @param organizationPublicKey Organization public key to authenticate the call.
         * 
         * @return builder
         * 
         */
        public Builder organizationPublicKey(String organizationPublicKey) {
            return organizationPublicKey(Output.of(organizationPublicKey));
        }

        /**
         * @param projectId The ID of the project the key belongs to.
         * 
         * @return builder
         * 
         */
        public Builder projectId(Output<String> projectId) {
            $.projectId = projectId;
            return this;
        }

        /**
         * @param projectId The ID of the project the key belongs to.
         * 
         * @return builder
         * 
         */
        public Builder projectId(String projectId) {
            return projectId(Output.of(projectId));
        }

        public ProjectApiKeyArgs build() {
            if ($.organizationPrivateKey == null) {
                throw new MissingRequiredPropertyException("ProjectApiKeyArgs", "organizationPrivateKey");
            }
            if ($.organizationPublicKey == null) {
                throw new MissingRequiredPropertyException("ProjectApiKeyArgs", "organizationPublicKey");
            }
            if ($.projectId == null) {
                throw new MissingRequiredPropertyException("ProjectApiKeyArgs", "projectId");
            }
            return $;
        }
    }

}
