// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.langfuse;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Double;
import java.lang.String;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class ProjectArgs extends com.pulumi.resources.ResourceArgs {

    public static final ProjectArgs Empty = new ProjectArgs();

    /**
     * Metadata for the project as key-value pairs.
     * 
     */
    @Import(name="metadata")
    private @Nullable Output<Map<String,String>> metadata;

    /**
     * @return Metadata for the project as key-value pairs.
     * 
     */
    public Optional<Output<Map<String,String>>> metadata() {
        return Optional.ofNullable(this.metadata);
    }

    /**
     * The display name of the project.
     * 
     */
    @Import(name="name")
    private @Nullable Output<String> name;

    /**
     * @return The display name of the project.
     * 
     */
    public Optional<Output<String>> name() {
        return Optional.ofNullable(this.name);
    }

    /**
     * The ID of the organization that owns this project.
     * 
     */
    @Import(name="organizationId", required=true)
    private Output<String> organizationId;

    /**
     * @return The ID of the organization that owns this project.
     * 
     */
    public Output<String> organizationId() {
        return this.organizationId;
    }

    /**
     * Organization private key to authenticate the call.
     * 
     */
    @Import(name="organizationPrivateKey", required=true)
    private Output<String> organizationPrivateKey;

    /**
     * @return Organization private key to authenticate the call.
     * 
     */
    public Output<String> organizationPrivateKey() {
        return this.organizationPrivateKey;
    }

    /**
     * Organization public key to authenticate the call.
     * 
     */
    @Import(name="organizationPublicKey", required=true)
    private Output<String> organizationPublicKey;

    /**
     * @return Organization public key to authenticate the call.
     * 
     */
    public Output<String> organizationPublicKey() {
        return this.organizationPublicKey;
    }

    /**
     * The retention period for the project in days. If not set, or set with a value of 0, data will be stored indefinitely.
     * 
     */
    @Import(name="retentionDays")
    private @Nullable Output<Double> retentionDays;

    /**
     * @return The retention period for the project in days. If not set, or set with a value of 0, data will be stored indefinitely.
     * 
     */
    public Optional<Output<Double>> retentionDays() {
        return Optional.ofNullable(this.retentionDays);
    }

    private ProjectArgs() {}

    private ProjectArgs(ProjectArgs $) {
        this.metadata = $.metadata;
        this.name = $.name;
        this.organizationId = $.organizationId;
        this.organizationPrivateKey = $.organizationPrivateKey;
        this.organizationPublicKey = $.organizationPublicKey;
        this.retentionDays = $.retentionDays;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(ProjectArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private ProjectArgs $;

        public Builder() {
            $ = new ProjectArgs();
        }

        public Builder(ProjectArgs defaults) {
            $ = new ProjectArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param metadata Metadata for the project as key-value pairs.
         * 
         * @return builder
         * 
         */
        public Builder metadata(@Nullable Output<Map<String,String>> metadata) {
            $.metadata = metadata;
            return this;
        }

        /**
         * @param metadata Metadata for the project as key-value pairs.
         * 
         * @return builder
         * 
         */
        public Builder metadata(Map<String,String> metadata) {
            return metadata(Output.of(metadata));
        }

        /**
         * @param name The display name of the project.
         * 
         * @return builder
         * 
         */
        public Builder name(@Nullable Output<String> name) {
            $.name = name;
            return this;
        }

        /**
         * @param name The display name of the project.
         * 
         * @return builder
         * 
         */
        public Builder name(String name) {
            return name(Output.of(name));
        }

        /**
         * @param organizationId The ID of the organization that owns this project.
         * 
         * @return builder
         * 
         */
        public Builder organizationId(Output<String> organizationId) {
            $.organizationId = organizationId;
            return this;
        }

        /**
         * @param organizationId The ID of the organization that owns this project.
         * 
         * @return builder
         * 
         */
        public Builder organizationId(String organizationId) {
            return organizationId(Output.of(organizationId));
        }

        /**
         * @param organizationPrivateKey Organization private key to authenticate the call.
         * 
         * @return builder
         * 
         */
        public Builder organizationPrivateKey(Output<String> organizationPrivateKey) {
            $.organizationPrivateKey = organizationPrivateKey;
            return this;
        }

        /**
         * @param organizationPrivateKey Organization private key to authenticate the call.
         * 
         * @return builder
         * 
         */
        public Builder organizationPrivateKey(String organizationPrivateKey) {
            return organizationPrivateKey(Output.of(organizationPrivateKey));
        }

        /**
         * @param organizationPublicKey Organization public key to authenticate the call.
         * 
         * @return builder
         * 
         */
        public Builder organizationPublicKey(Output<String> organizationPublicKey) {
            $.organizationPublicKey = organizationPublicKey;
            return this;
        }

        /**
         * @param organizationPublicKey Organization public key to authenticate the call.
         * 
         * @return builder
         * 
         */
        public Builder organizationPublicKey(String organizationPublicKey) {
            return organizationPublicKey(Output.of(organizationPublicKey));
        }

        /**
         * @param retentionDays The retention period for the project in days. If not set, or set with a value of 0, data will be stored indefinitely.
         * 
         * @return builder
         * 
         */
        public Builder retentionDays(@Nullable Output<Double> retentionDays) {
            $.retentionDays = retentionDays;
            return this;
        }

        /**
         * @param retentionDays The retention period for the project in days. If not set, or set with a value of 0, data will be stored indefinitely.
         * 
         * @return builder
         * 
         */
        public Builder retentionDays(Double retentionDays) {
            return retentionDays(Output.of(retentionDays));
        }

        public ProjectArgs build() {
            if ($.organizationId == null) {
                throw new MissingRequiredPropertyException("ProjectArgs", "organizationId");
            }
            if ($.organizationPrivateKey == null) {
                throw new MissingRequiredPropertyException("ProjectArgs", "organizationPrivateKey");
            }
            if ($.organizationPublicKey == null) {
                throw new MissingRequiredPropertyException("ProjectArgs", "organizationPublicKey");
            }
            return $;
        }
    }

}
