// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.langfuse;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import com.pulumi.langfuse.ProjectArgs;
import com.pulumi.langfuse.Utilities;
import com.pulumi.langfuse.inputs.ProjectState;
import java.lang.Double;
import java.lang.String;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import javax.annotation.Nullable;

@ResourceType(type="langfuse:index/project:Project")
public class Project extends com.pulumi.resources.CustomResource {
    /**
     * Metadata for the project as key-value pairs.
     * 
     */
    @Export(name="metadata", refs={Map.class,String.class}, tree="[0,1,1]")
    private Output</* @Nullable */ Map<String,String>> metadata;

    /**
     * @return Metadata for the project as key-value pairs.
     * 
     */
    public Output<Optional<Map<String,String>>> metadata() {
        return Codegen.optional(this.metadata);
    }
    /**
     * The display name of the project.
     * 
     */
    @Export(name="name", refs={String.class}, tree="[0]")
    private Output<String> name;

    /**
     * @return The display name of the project.
     * 
     */
    public Output<String> name() {
        return this.name;
    }
    /**
     * The ID of the organization that owns this project.
     * 
     */
    @Export(name="organizationId", refs={String.class}, tree="[0]")
    private Output<String> organizationId;

    /**
     * @return The ID of the organization that owns this project.
     * 
     */
    public Output<String> organizationId() {
        return this.organizationId;
    }
    /**
     * Organization private key to authenticate the call.
     * 
     */
    @Export(name="organizationPrivateKey", refs={String.class}, tree="[0]")
    private Output<String> organizationPrivateKey;

    /**
     * @return Organization private key to authenticate the call.
     * 
     */
    public Output<String> organizationPrivateKey() {
        return this.organizationPrivateKey;
    }
    /**
     * Organization public key to authenticate the call.
     * 
     */
    @Export(name="organizationPublicKey", refs={String.class}, tree="[0]")
    private Output<String> organizationPublicKey;

    /**
     * @return Organization public key to authenticate the call.
     * 
     */
    public Output<String> organizationPublicKey() {
        return this.organizationPublicKey;
    }
    /**
     * The retention period for the project in days. If not set, or set with a value of 0, data will be stored indefinitely.
     * 
     */
    @Export(name="retentionDays", refs={Double.class}, tree="[0]")
    private Output<Double> retentionDays;

    /**
     * @return The retention period for the project in days. If not set, or set with a value of 0, data will be stored indefinitely.
     * 
     */
    public Output<Double> retentionDays() {
        return this.retentionDays;
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public Project(java.lang.String name) {
        this(name, ProjectArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public Project(java.lang.String name, ProjectArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public Project(java.lang.String name, ProjectArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("langfuse:index/project:Project", name, makeArgs(args, options), makeResourceOptions(options, Codegen.empty()), false, Utilities.getPackageRef());
    }

    private Project(java.lang.String name, Output<java.lang.String> id, @Nullable ProjectState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("langfuse:index/project:Project", name, state, makeResourceOptions(options, id), false, Utilities.getPackageRef());
    }

    private static ProjectArgs makeArgs(ProjectArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        if (options != null && options.getUrn().isPresent()) {
            return null;
        }
        return args == null ? ProjectArgs.Empty : args;
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<java.lang.String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .additionalSecretOutputs(List.of(
                "organizationPrivateKey",
                "organizationPublicKey"
            ))
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static Project get(java.lang.String name, Output<java.lang.String> id, @Nullable ProjectState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new Project(name, id, state, options);
    }
}
