// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.langfuse;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import com.pulumi.langfuse.ProjectApiKeyArgs;
import com.pulumi.langfuse.Utilities;
import com.pulumi.langfuse.inputs.ProjectApiKeyState;
import java.lang.String;
import java.util.List;
import java.util.Optional;
import javax.annotation.Nullable;

@ResourceType(type="langfuse:index/projectApiKey:ProjectApiKey")
public class ProjectApiKey extends com.pulumi.resources.CustomResource {
    /**
     * Optional note for the API key (POST /api/public/projects/{projectId}/apiKeys). Because the Langfuse public API only accepts a note at creation time, changing this attribute forces replacement: the old key is deleted and a new one is created (new id and credentials).
     * 
     */
    @Export(name="note", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> note;

    /**
     * @return Optional note for the API key (POST /api/public/projects/{projectId}/apiKeys). Because the Langfuse public API only accepts a note at creation time, changing this attribute forces replacement: the old key is deleted and a new one is created (new id and credentials).
     * 
     */
    public Output<Optional<String>> note() {
        return Codegen.optional(this.note);
    }
    /**
     * Organization private key to authenticate the call.
     * 
     */
    @Export(name="organizationPrivateKey", refs={String.class}, tree="[0]")
    private Output<String> organizationPrivateKey;

    /**
     * @return Organization private key to authenticate the call.
     * 
     */
    public Output<String> organizationPrivateKey() {
        return this.organizationPrivateKey;
    }
    /**
     * Organization public key to authenticate the call.
     * 
     */
    @Export(name="organizationPublicKey", refs={String.class}, tree="[0]")
    private Output<String> organizationPublicKey;

    /**
     * @return Organization public key to authenticate the call.
     * 
     */
    public Output<String> organizationPublicKey() {
        return this.organizationPublicKey;
    }
    /**
     * The ID of the project the key belongs to.
     * 
     */
    @Export(name="projectId", refs={String.class}, tree="[0]")
    private Output<String> projectId;

    /**
     * @return The ID of the project the key belongs to.
     * 
     */
    public Output<String> projectId() {
        return this.projectId;
    }
    /**
     * The public value of the API key (only returned at creation time).
     * 
     */
    @Export(name="publicKey", refs={String.class}, tree="[0]")
    private Output<String> publicKey;

    /**
     * @return The public value of the API key (only returned at creation time).
     * 
     */
    public Output<String> publicKey() {
        return this.publicKey;
    }
    /**
     * The secret value of the API key (only returned at creation time).
     * 
     */
    @Export(name="secretKey", refs={String.class}, tree="[0]")
    private Output<String> secretKey;

    /**
     * @return The secret value of the API key (only returned at creation time).
     * 
     */
    public Output<String> secretKey() {
        return this.secretKey;
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public ProjectApiKey(java.lang.String name) {
        this(name, ProjectApiKeyArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public ProjectApiKey(java.lang.String name, ProjectApiKeyArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public ProjectApiKey(java.lang.String name, ProjectApiKeyArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("langfuse:index/projectApiKey:ProjectApiKey", name, makeArgs(args, options), makeResourceOptions(options, Codegen.empty()), false, Utilities.getPackageRef());
    }

    private ProjectApiKey(java.lang.String name, Output<java.lang.String> id, @Nullable ProjectApiKeyState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("langfuse:index/projectApiKey:ProjectApiKey", name, state, makeResourceOptions(options, id), false, Utilities.getPackageRef());
    }

    private static ProjectApiKeyArgs makeArgs(ProjectApiKeyArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        if (options != null && options.getUrn().isPresent()) {
            return null;
        }
        return args == null ? ProjectApiKeyArgs.Empty : args;
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<java.lang.String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .additionalSecretOutputs(List.of(
                "organizationPrivateKey",
                "publicKey",
                "secretKey"
            ))
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static ProjectApiKey get(java.lang.String name, Output<java.lang.String> id, @Nullable ProjectApiKeyState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new ProjectApiKey(name, id, state, options);
    }
}
