// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.langfuse;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class ProviderArgs extends com.pulumi.resources.ResourceArgs {

    public static final ProviderArgs Empty = new ProviderArgs();

    /**
     * Admin API key. Only needed when managing organizations. Can also come from LANGFUSE_ADMIN_KEY.
     * 
     */
    @Import(name="adminApiKey")
    private @Nullable Output<String> adminApiKey;

    /**
     * @return Admin API key. Only needed when managing organizations. Can also come from LANGFUSE_ADMIN_KEY.
     * 
     */
    public Optional<Output<String>> adminApiKey() {
        return Optional.ofNullable(this.adminApiKey);
    }

    /**
     * Base URI of the Langfuse instance (defaults to https://app.langfuse.com).
     * 
     */
    @Import(name="host")
    private @Nullable Output<String> host;

    /**
     * @return Base URI of the Langfuse instance (defaults to https://app.langfuse.com).
     * 
     */
    public Optional<Output<String>> host() {
        return Optional.ofNullable(this.host);
    }

    /**
     * Hostname to verify the TLS certificate against, also sent as the SNI value. Set this when the instance is reached through a port forward or tunnel, where the host above (typically localhost) cannot match the certificate. Certificate verification remains enabled.
     * 
     */
    @Import(name="tlsServerName")
    private @Nullable Output<String> tlsServerName;

    /**
     * @return Hostname to verify the TLS certificate against, also sent as the SNI value. Set this when the instance is reached through a port forward or tunnel, where the host above (typically localhost) cannot match the certificate. Certificate verification remains enabled.
     * 
     */
    public Optional<Output<String>> tlsServerName() {
        return Optional.ofNullable(this.tlsServerName);
    }

    private ProviderArgs() {}

    private ProviderArgs(ProviderArgs $) {
        this.adminApiKey = $.adminApiKey;
        this.host = $.host;
        this.tlsServerName = $.tlsServerName;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(ProviderArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private ProviderArgs $;

        public Builder() {
            $ = new ProviderArgs();
        }

        public Builder(ProviderArgs defaults) {
            $ = new ProviderArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param adminApiKey Admin API key. Only needed when managing organizations. Can also come from LANGFUSE_ADMIN_KEY.
         * 
         * @return builder
         * 
         */
        public Builder adminApiKey(@Nullable Output<String> adminApiKey) {
            $.adminApiKey = adminApiKey;
            return this;
        }

        /**
         * @param adminApiKey Admin API key. Only needed when managing organizations. Can also come from LANGFUSE_ADMIN_KEY.
         * 
         * @return builder
         * 
         */
        public Builder adminApiKey(String adminApiKey) {
            return adminApiKey(Output.of(adminApiKey));
        }

        /**
         * @param host Base URI of the Langfuse instance (defaults to https://app.langfuse.com).
         * 
         * @return builder
         * 
         */
        public Builder host(@Nullable Output<String> host) {
            $.host = host;
            return this;
        }

        /**
         * @param host Base URI of the Langfuse instance (defaults to https://app.langfuse.com).
         * 
         * @return builder
         * 
         */
        public Builder host(String host) {
            return host(Output.of(host));
        }

        /**
         * @param tlsServerName Hostname to verify the TLS certificate against, also sent as the SNI value. Set this when the instance is reached through a port forward or tunnel, where the host above (typically localhost) cannot match the certificate. Certificate verification remains enabled.
         * 
         * @return builder
         * 
         */
        public Builder tlsServerName(@Nullable Output<String> tlsServerName) {
            $.tlsServerName = tlsServerName;
            return this;
        }

        /**
         * @param tlsServerName Hostname to verify the TLS certificate against, also sent as the SNI value. Set this when the instance is reached through a port forward or tunnel, where the host above (typically localhost) cannot match the certificate. Certificate verification remains enabled.
         * 
         * @return builder
         * 
         */
        public Builder tlsServerName(String tlsServerName) {
            return tlsServerName(Output.of(tlsServerName));
        }

        public ProviderArgs build() {
            return $;
        }
    }

}
