// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package config

import (
	"github.com/gvtlabs/pulumi-langfuse/sdks/go/langfuse/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi/config"
)

var _ = internal.GetEnvOrDefault

// Admin API key. Only needed when managing organizations. Can also come from LANGFUSE_ADMIN_KEY.
func GetAdminApiKey(ctx *pulumi.Context) string {
	return config.Get(ctx, "langfuse:adminApiKey")
}

// Base URI of the Langfuse instance (defaults to https://app.langfuse.com).
func GetHost(ctx *pulumi.Context) string {
	return config.Get(ctx, "langfuse:host")
}

// Hostname to verify the TLS certificate against, also sent as the SNI value. Set this when the instance is reached through a port forward or tunnel, where the host above (typically localhost) cannot match the certificate. Certificate verification remains enabled.
func GetTlsServerName(ctx *pulumi.Context) string {
	return config.Get(ctx, "langfuse:tlsServerName")
}
