// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Langfuse
{
    [LangfuseResourceType("langfuse:index/llmConnection:LlmConnection")]
    public partial class LlmConnection : global::Pulumi.CustomResource
    {
        /// <summary>
        /// The LLM service type. Valid values: anthropic, openai, azure, bedrock, google-vertex-ai, google-ai-studio.
        /// </summary>
        [Output("adapter")]
        public Output<string> Adapter { get; private set; } = null!;

        /// <summary>
        /// Optional base URL override for the LLM provider API.
        /// </summary>
        [Output("baseUrl")]
        public Output<string?> BaseUrl { get; private set; } = null!;

        /// <summary>
        /// Adapter-specific configuration as a JSON string.
        /// </summary>
        [Output("config")]
        public Output<string?> Config { get; private set; } = null!;

        /// <summary>
        /// Optional list of custom model identifiers.
        /// </summary>
        [Output("customModels")]
        public Output<ImmutableArray<string>> CustomModels { get; private set; } = null!;

        /// <summary>
        /// Optional map of additional HTTP headers for LLM API requests.
        /// </summary>
        [Output("extraHeaders")]
        public Output<ImmutableDictionary<string, string>?> ExtraHeaders { get; private set; } = null!;

        /// <summary>
        /// The project public key used to authenticate API calls.
        /// </summary>
        [Output("projectPublicKey")]
        public Output<string> ProjectPublicKey { get; private set; } = null!;

        /// <summary>
        /// The project secret key used to authenticate API calls.
        /// </summary>
        [Output("projectSecretKey")]
        public Output<string> ProjectSecretKey { get; private set; } = null!;

        /// <summary>
        /// The unique name identifying this LLM connection within the project. Changing this value destroys and recreates the resource, as the provider name is the upsert key.
        /// </summary>
        [Output("providerName")]
        public Output<string> ProviderName { get; private set; } = null!;

        /// <summary>
        /// The API authentication key for the LLM provider.
        /// </summary>
        [Output("secretKey")]
        public Output<string> SecretKey { get; private set; } = null!;

        /// <summary>
        /// Whether to include default models. Defaults to true if not set.
        /// </summary>
        [Output("withDefaultModels")]
        public Output<bool> WithDefaultModels { get; private set; } = null!;


        /// <summary>
        /// Create a LlmConnection resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public LlmConnection(string name, LlmConnectionArgs args, CustomResourceOptions? options = null)
            : base("langfuse:index/llmConnection:LlmConnection", name, args ?? new LlmConnectionArgs(), MakeResourceOptions(options, ""), Utilities.PackageParameterization())
        {
        }

        private LlmConnection(string name, Input<string> id, LlmConnectionState? state = null, CustomResourceOptions? options = null)
            : base("langfuse:index/llmConnection:LlmConnection", name, state, MakeResourceOptions(options, id), Utilities.PackageParameterization())
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                AdditionalSecretOutputs =
                {
                    "extraHeaders",
                    "projectPublicKey",
                    "projectSecretKey",
                    "secretKey",
                },
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing LlmConnection resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static LlmConnection Get(string name, Input<string> id, LlmConnectionState? state = null, CustomResourceOptions? options = null)
        {
            return new LlmConnection(name, id, state, options);
        }
    }

    public sealed class LlmConnectionArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The LLM service type. Valid values: anthropic, openai, azure, bedrock, google-vertex-ai, google-ai-studio.
        /// </summary>
        [Input("adapter", required: true)]
        public Input<string> Adapter { get; set; } = null!;

        /// <summary>
        /// Optional base URL override for the LLM provider API.
        /// </summary>
        [Input("baseUrl")]
        public Input<string>? BaseUrl { get; set; }

        /// <summary>
        /// Adapter-specific configuration as a JSON string.
        /// </summary>
        [Input("config")]
        public Input<string>? Config { get; set; }

        [Input("customModels")]
        private InputList<string>? _customModels;

        /// <summary>
        /// Optional list of custom model identifiers.
        /// </summary>
        public InputList<string> CustomModels
        {
            get => _customModels ?? (_customModels = new InputList<string>());
            set => _customModels = value;
        }

        [Input("extraHeaders")]
        private InputMap<string>? _extraHeaders;

        /// <summary>
        /// Optional map of additional HTTP headers for LLM API requests.
        /// </summary>
        public InputMap<string> ExtraHeaders
        {
            get => _extraHeaders ?? (_extraHeaders = new InputMap<string>());
            set
            {
                var emptySecret = Output.CreateSecret(ImmutableDictionary.Create<string, string>());
                _extraHeaders = Output.All(value, emptySecret).Apply(v => v[0]);
            }
        }

        [Input("projectPublicKey", required: true)]
        private Input<string>? _projectPublicKey;

        /// <summary>
        /// The project public key used to authenticate API calls.
        /// </summary>
        public Input<string>? ProjectPublicKey
        {
            get => _projectPublicKey;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _projectPublicKey = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        [Input("projectSecretKey", required: true)]
        private Input<string>? _projectSecretKey;

        /// <summary>
        /// The project secret key used to authenticate API calls.
        /// </summary>
        public Input<string>? ProjectSecretKey
        {
            get => _projectSecretKey;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _projectSecretKey = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        /// <summary>
        /// The unique name identifying this LLM connection within the project. Changing this value destroys and recreates the resource, as the provider name is the upsert key.
        /// </summary>
        [Input("providerName", required: true)]
        public Input<string> ProviderName { get; set; } = null!;

        [Input("secretKey", required: true)]
        private Input<string>? _secretKey;

        /// <summary>
        /// The API authentication key for the LLM provider.
        /// </summary>
        public Input<string>? SecretKey
        {
            get => _secretKey;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _secretKey = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        /// <summary>
        /// Whether to include default models. Defaults to true if not set.
        /// </summary>
        [Input("withDefaultModels")]
        public Input<bool>? WithDefaultModels { get; set; }

        public LlmConnectionArgs()
        {
        }
        public static new LlmConnectionArgs Empty => new LlmConnectionArgs();
    }

    public sealed class LlmConnectionState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The LLM service type. Valid values: anthropic, openai, azure, bedrock, google-vertex-ai, google-ai-studio.
        /// </summary>
        [Input("adapter")]
        public Input<string>? Adapter { get; set; }

        /// <summary>
        /// Optional base URL override for the LLM provider API.
        /// </summary>
        [Input("baseUrl")]
        public Input<string>? BaseUrl { get; set; }

        /// <summary>
        /// Adapter-specific configuration as a JSON string.
        /// </summary>
        [Input("config")]
        public Input<string>? Config { get; set; }

        [Input("customModels")]
        private InputList<string>? _customModels;

        /// <summary>
        /// Optional list of custom model identifiers.
        /// </summary>
        public InputList<string> CustomModels
        {
            get => _customModels ?? (_customModels = new InputList<string>());
            set => _customModels = value;
        }

        [Input("extraHeaders")]
        private InputMap<string>? _extraHeaders;

        /// <summary>
        /// Optional map of additional HTTP headers for LLM API requests.
        /// </summary>
        public InputMap<string> ExtraHeaders
        {
            get => _extraHeaders ?? (_extraHeaders = new InputMap<string>());
            set
            {
                var emptySecret = Output.CreateSecret(ImmutableDictionary.Create<string, string>());
                _extraHeaders = Output.All(value, emptySecret).Apply(v => v[0]);
            }
        }

        [Input("projectPublicKey")]
        private Input<string>? _projectPublicKey;

        /// <summary>
        /// The project public key used to authenticate API calls.
        /// </summary>
        public Input<string>? ProjectPublicKey
        {
            get => _projectPublicKey;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _projectPublicKey = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        [Input("projectSecretKey")]
        private Input<string>? _projectSecretKey;

        /// <summary>
        /// The project secret key used to authenticate API calls.
        /// </summary>
        public Input<string>? ProjectSecretKey
        {
            get => _projectSecretKey;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _projectSecretKey = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        /// <summary>
        /// The unique name identifying this LLM connection within the project. Changing this value destroys and recreates the resource, as the provider name is the upsert key.
        /// </summary>
        [Input("providerName")]
        public Input<string>? ProviderName { get; set; }

        [Input("secretKey")]
        private Input<string>? _secretKey;

        /// <summary>
        /// The API authentication key for the LLM provider.
        /// </summary>
        public Input<string>? SecretKey
        {
            get => _secretKey;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _secretKey = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        /// <summary>
        /// Whether to include default models. Defaults to true if not set.
        /// </summary>
        [Input("withDefaultModels")]
        public Input<bool>? WithDefaultModels { get; set; }

        public LlmConnectionState()
        {
        }
        public static new LlmConnectionState Empty => new LlmConnectionState();
    }
}
