// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Langfuse
{
    [LangfuseResourceType("langfuse:index/organizationApiKey:OrganizationApiKey")]
    public partial class OrganizationApiKey : global::Pulumi.CustomResource
    {
        /// <summary>
        /// The Langfuse organization the key belongs to.
        /// </summary>
        [Output("organizationId")]
        public Output<string> OrganizationId { get; private set; } = null!;

        /// <summary>
        /// The public value of the API key (only returned at creation time).
        /// </summary>
        [Output("publicKey")]
        public Output<string> PublicKey { get; private set; } = null!;

        /// <summary>
        /// The secret value of the API key (only returned at creation time).
        /// </summary>
        [Output("secretKey")]
        public Output<string> SecretKey { get; private set; } = null!;


        /// <summary>
        /// Create a OrganizationApiKey resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public OrganizationApiKey(string name, OrganizationApiKeyArgs args, CustomResourceOptions? options = null)
            : base("langfuse:index/organizationApiKey:OrganizationApiKey", name, args ?? new OrganizationApiKeyArgs(), MakeResourceOptions(options, ""), Utilities.PackageParameterization())
        {
        }

        private OrganizationApiKey(string name, Input<string> id, OrganizationApiKeyState? state = null, CustomResourceOptions? options = null)
            : base("langfuse:index/organizationApiKey:OrganizationApiKey", name, state, MakeResourceOptions(options, id), Utilities.PackageParameterization())
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                AdditionalSecretOutputs =
                {
                    "publicKey",
                    "secretKey",
                },
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing OrganizationApiKey resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static OrganizationApiKey Get(string name, Input<string> id, OrganizationApiKeyState? state = null, CustomResourceOptions? options = null)
        {
            return new OrganizationApiKey(name, id, state, options);
        }
    }

    public sealed class OrganizationApiKeyArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The Langfuse organization the key belongs to.
        /// </summary>
        [Input("organizationId", required: true)]
        public Input<string> OrganizationId { get; set; } = null!;

        public OrganizationApiKeyArgs()
        {
        }
        public static new OrganizationApiKeyArgs Empty => new OrganizationApiKeyArgs();
    }

    public sealed class OrganizationApiKeyState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The Langfuse organization the key belongs to.
        /// </summary>
        [Input("organizationId")]
        public Input<string>? OrganizationId { get; set; }

        [Input("publicKey")]
        private Input<string>? _publicKey;

        /// <summary>
        /// The public value of the API key (only returned at creation time).
        /// </summary>
        public Input<string>? PublicKey
        {
            get => _publicKey;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _publicKey = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        [Input("secretKey")]
        private Input<string>? _secretKey;

        /// <summary>
        /// The secret value of the API key (only returned at creation time).
        /// </summary>
        public Input<string>? SecretKey
        {
            get => _secretKey;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _secretKey = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        public OrganizationApiKeyState()
        {
        }
        public static new OrganizationApiKeyState Empty => new OrganizationApiKeyState();
    }
}
