// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Langfuse
{
    [LangfuseResourceType("langfuse:index/organizationMembership:OrganizationMembership")]
    public partial class OrganizationMembership : global::Pulumi.CustomResource
    {
        /// <summary>
        /// The email address of the user to invite.
        /// </summary>
        [Output("email")]
        public Output<string> Email { get; private set; } = null!;

        /// <summary>
        /// Organization private key to authenticate the call.
        /// </summary>
        [Output("organizationPrivateKey")]
        public Output<string> OrganizationPrivateKey { get; private set; } = null!;

        /// <summary>
        /// Organization public key to authenticate the call.
        /// </summary>
        [Output("organizationPublicKey")]
        public Output<string> OrganizationPublicKey { get; private set; } = null!;

        /// <summary>
        /// The role to assign to the user. Valid values are: ADMIN, MEMBER, VIEWER.
        /// </summary>
        [Output("role")]
        public Output<string> Role { get; private set; } = null!;

        /// <summary>
        /// The status of the membership invitation.
        /// </summary>
        [Output("status")]
        public Output<string> Status { get; private set; } = null!;

        /// <summary>
        /// The unique identifier of the user.
        /// </summary>
        [Output("userId")]
        public Output<string> UserId { get; private set; } = null!;

        /// <summary>
        /// The username of the user.
        /// </summary>
        [Output("username")]
        public Output<string> Username { get; private set; } = null!;


        /// <summary>
        /// Create a OrganizationMembership resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public OrganizationMembership(string name, OrganizationMembershipArgs args, CustomResourceOptions? options = null)
            : base("langfuse:index/organizationMembership:OrganizationMembership", name, args ?? new OrganizationMembershipArgs(), MakeResourceOptions(options, ""), Utilities.PackageParameterization())
        {
        }

        private OrganizationMembership(string name, Input<string> id, OrganizationMembershipState? state = null, CustomResourceOptions? options = null)
            : base("langfuse:index/organizationMembership:OrganizationMembership", name, state, MakeResourceOptions(options, id), Utilities.PackageParameterization())
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                AdditionalSecretOutputs =
                {
                    "organizationPrivateKey",
                    "organizationPublicKey",
                },
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing OrganizationMembership resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static OrganizationMembership Get(string name, Input<string> id, OrganizationMembershipState? state = null, CustomResourceOptions? options = null)
        {
            return new OrganizationMembership(name, id, state, options);
        }
    }

    public sealed class OrganizationMembershipArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The email address of the user to invite.
        /// </summary>
        [Input("email", required: true)]
        public Input<string> Email { get; set; } = null!;

        [Input("organizationPrivateKey", required: true)]
        private Input<string>? _organizationPrivateKey;

        /// <summary>
        /// Organization private key to authenticate the call.
        /// </summary>
        public Input<string>? OrganizationPrivateKey
        {
            get => _organizationPrivateKey;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _organizationPrivateKey = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        [Input("organizationPublicKey", required: true)]
        private Input<string>? _organizationPublicKey;

        /// <summary>
        /// Organization public key to authenticate the call.
        /// </summary>
        public Input<string>? OrganizationPublicKey
        {
            get => _organizationPublicKey;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _organizationPublicKey = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        /// <summary>
        /// The role to assign to the user. Valid values are: ADMIN, MEMBER, VIEWER.
        /// </summary>
        [Input("role", required: true)]
        public Input<string> Role { get; set; } = null!;

        public OrganizationMembershipArgs()
        {
        }
        public static new OrganizationMembershipArgs Empty => new OrganizationMembershipArgs();
    }

    public sealed class OrganizationMembershipState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The email address of the user to invite.
        /// </summary>
        [Input("email")]
        public Input<string>? Email { get; set; }

        [Input("organizationPrivateKey")]
        private Input<string>? _organizationPrivateKey;

        /// <summary>
        /// Organization private key to authenticate the call.
        /// </summary>
        public Input<string>? OrganizationPrivateKey
        {
            get => _organizationPrivateKey;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _organizationPrivateKey = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        [Input("organizationPublicKey")]
        private Input<string>? _organizationPublicKey;

        /// <summary>
        /// Organization public key to authenticate the call.
        /// </summary>
        public Input<string>? OrganizationPublicKey
        {
            get => _organizationPublicKey;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _organizationPublicKey = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        /// <summary>
        /// The role to assign to the user. Valid values are: ADMIN, MEMBER, VIEWER.
        /// </summary>
        [Input("role")]
        public Input<string>? Role { get; set; }

        /// <summary>
        /// The status of the membership invitation.
        /// </summary>
        [Input("status")]
        public Input<string>? Status { get; set; }

        /// <summary>
        /// The unique identifier of the user.
        /// </summary>
        [Input("userId")]
        public Input<string>? UserId { get; set; }

        /// <summary>
        /// The username of the user.
        /// </summary>
        [Input("username")]
        public Input<string>? Username { get; set; }

        public OrganizationMembershipState()
        {
        }
        public static new OrganizationMembershipState Empty => new OrganizationMembershipState();
    }
}
