// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Langfuse
{
    [LangfuseResourceType("langfuse:index/projectApiKey:ProjectApiKey")]
    public partial class ProjectApiKey : global::Pulumi.CustomResource
    {
        /// <summary>
        /// Optional note for the API key (POST /api/public/projects/{projectId}/apiKeys). Because the Langfuse public API only accepts a note at creation time, changing this attribute forces replacement: the old key is deleted and a new one is created (new id and credentials).
        /// </summary>
        [Output("note")]
        public Output<string?> Note { get; private set; } = null!;

        /// <summary>
        /// Organization private key to authenticate the call.
        /// </summary>
        [Output("organizationPrivateKey")]
        public Output<string> OrganizationPrivateKey { get; private set; } = null!;

        /// <summary>
        /// Organization public key to authenticate the call.
        /// </summary>
        [Output("organizationPublicKey")]
        public Output<string> OrganizationPublicKey { get; private set; } = null!;

        /// <summary>
        /// The ID of the project the key belongs to.
        /// </summary>
        [Output("projectId")]
        public Output<string> ProjectId { get; private set; } = null!;

        /// <summary>
        /// The public value of the API key (only returned at creation time).
        /// </summary>
        [Output("publicKey")]
        public Output<string> PublicKey { get; private set; } = null!;

        /// <summary>
        /// The secret value of the API key (only returned at creation time).
        /// </summary>
        [Output("secretKey")]
        public Output<string> SecretKey { get; private set; } = null!;


        /// <summary>
        /// Create a ProjectApiKey resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public ProjectApiKey(string name, ProjectApiKeyArgs args, CustomResourceOptions? options = null)
            : base("langfuse:index/projectApiKey:ProjectApiKey", name, args ?? new ProjectApiKeyArgs(), MakeResourceOptions(options, ""), Utilities.PackageParameterization())
        {
        }

        private ProjectApiKey(string name, Input<string> id, ProjectApiKeyState? state = null, CustomResourceOptions? options = null)
            : base("langfuse:index/projectApiKey:ProjectApiKey", name, state, MakeResourceOptions(options, id), Utilities.PackageParameterization())
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                AdditionalSecretOutputs =
                {
                    "organizationPrivateKey",
                    "publicKey",
                    "secretKey",
                },
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing ProjectApiKey resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static ProjectApiKey Get(string name, Input<string> id, ProjectApiKeyState? state = null, CustomResourceOptions? options = null)
        {
            return new ProjectApiKey(name, id, state, options);
        }
    }

    public sealed class ProjectApiKeyArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Optional note for the API key (POST /api/public/projects/{projectId}/apiKeys). Because the Langfuse public API only accepts a note at creation time, changing this attribute forces replacement: the old key is deleted and a new one is created (new id and credentials).
        /// </summary>
        [Input("note")]
        public Input<string>? Note { get; set; }

        [Input("organizationPrivateKey", required: true)]
        private Input<string>? _organizationPrivateKey;

        /// <summary>
        /// Organization private key to authenticate the call.
        /// </summary>
        public Input<string>? OrganizationPrivateKey
        {
            get => _organizationPrivateKey;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _organizationPrivateKey = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        /// <summary>
        /// Organization public key to authenticate the call.
        /// </summary>
        [Input("organizationPublicKey", required: true)]
        public Input<string> OrganizationPublicKey { get; set; } = null!;

        /// <summary>
        /// The ID of the project the key belongs to.
        /// </summary>
        [Input("projectId", required: true)]
        public Input<string> ProjectId { get; set; } = null!;

        public ProjectApiKeyArgs()
        {
        }
        public static new ProjectApiKeyArgs Empty => new ProjectApiKeyArgs();
    }

    public sealed class ProjectApiKeyState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Optional note for the API key (POST /api/public/projects/{projectId}/apiKeys). Because the Langfuse public API only accepts a note at creation time, changing this attribute forces replacement: the old key is deleted and a new one is created (new id and credentials).
        /// </summary>
        [Input("note")]
        public Input<string>? Note { get; set; }

        [Input("organizationPrivateKey")]
        private Input<string>? _organizationPrivateKey;

        /// <summary>
        /// Organization private key to authenticate the call.
        /// </summary>
        public Input<string>? OrganizationPrivateKey
        {
            get => _organizationPrivateKey;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _organizationPrivateKey = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        /// <summary>
        /// Organization public key to authenticate the call.
        /// </summary>
        [Input("organizationPublicKey")]
        public Input<string>? OrganizationPublicKey { get; set; }

        /// <summary>
        /// The ID of the project the key belongs to.
        /// </summary>
        [Input("projectId")]
        public Input<string>? ProjectId { get; set; }

        [Input("publicKey")]
        private Input<string>? _publicKey;

        /// <summary>
        /// The public value of the API key (only returned at creation time).
        /// </summary>
        public Input<string>? PublicKey
        {
            get => _publicKey;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _publicKey = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        [Input("secretKey")]
        private Input<string>? _secretKey;

        /// <summary>
        /// The secret value of the API key (only returned at creation time).
        /// </summary>
        public Input<string>? SecretKey
        {
            get => _secretKey;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _secretKey = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        public ProjectApiKeyState()
        {
        }
        public static new ProjectApiKeyState Empty => new ProjectApiKeyState();
    }
}
