// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Langfuse
{
    [LangfuseResourceType("langfuse:index/projectMembership:ProjectMembership")]
    public partial class ProjectMembership : global::Pulumi.CustomResource
    {
        /// <summary>
        /// The email address of the user to add to the project.
        /// </summary>
        [Output("email")]
        public Output<string> Email { get; private set; } = null!;

        /// <summary>
        /// The name of the user.
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        /// <summary>
        /// Organization private key to authenticate the call.
        /// </summary>
        [Output("organizationPrivateKey")]
        public Output<string> OrganizationPrivateKey { get; private set; } = null!;

        /// <summary>
        /// Organization public key to authenticate the call.
        /// </summary>
        [Output("organizationPublicKey")]
        public Output<string> OrganizationPublicKey { get; private set; } = null!;

        /// <summary>
        /// The ID of the project.
        /// </summary>
        [Output("projectId")]
        public Output<string> ProjectId { get; private set; } = null!;

        /// <summary>
        /// The role to assign to the user. Valid values are: OWNER, ADMIN, MEMBER, VIEWER, NONE.
        /// </summary>
        [Output("role")]
        public Output<string> Role { get; private set; } = null!;

        /// <summary>
        /// The unique identifier of the user.
        /// </summary>
        [Output("userId")]
        public Output<string> UserId { get; private set; } = null!;


        /// <summary>
        /// Create a ProjectMembership resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public ProjectMembership(string name, ProjectMembershipArgs args, CustomResourceOptions? options = null)
            : base("langfuse:index/projectMembership:ProjectMembership", name, args ?? new ProjectMembershipArgs(), MakeResourceOptions(options, ""), Utilities.PackageParameterization())
        {
        }

        private ProjectMembership(string name, Input<string> id, ProjectMembershipState? state = null, CustomResourceOptions? options = null)
            : base("langfuse:index/projectMembership:ProjectMembership", name, state, MakeResourceOptions(options, id), Utilities.PackageParameterization())
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                AdditionalSecretOutputs =
                {
                    "organizationPrivateKey",
                    "organizationPublicKey",
                },
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing ProjectMembership resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static ProjectMembership Get(string name, Input<string> id, ProjectMembershipState? state = null, CustomResourceOptions? options = null)
        {
            return new ProjectMembership(name, id, state, options);
        }
    }

    public sealed class ProjectMembershipArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The email address of the user to add to the project.
        /// </summary>
        [Input("email", required: true)]
        public Input<string> Email { get; set; } = null!;

        [Input("organizationPrivateKey", required: true)]
        private Input<string>? _organizationPrivateKey;

        /// <summary>
        /// Organization private key to authenticate the call.
        /// </summary>
        public Input<string>? OrganizationPrivateKey
        {
            get => _organizationPrivateKey;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _organizationPrivateKey = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        [Input("organizationPublicKey", required: true)]
        private Input<string>? _organizationPublicKey;

        /// <summary>
        /// Organization public key to authenticate the call.
        /// </summary>
        public Input<string>? OrganizationPublicKey
        {
            get => _organizationPublicKey;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _organizationPublicKey = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        /// <summary>
        /// The ID of the project.
        /// </summary>
        [Input("projectId", required: true)]
        public Input<string> ProjectId { get; set; } = null!;

        /// <summary>
        /// The role to assign to the user. Valid values are: OWNER, ADMIN, MEMBER, VIEWER, NONE.
        /// </summary>
        [Input("role", required: true)]
        public Input<string> Role { get; set; } = null!;

        public ProjectMembershipArgs()
        {
        }
        public static new ProjectMembershipArgs Empty => new ProjectMembershipArgs();
    }

    public sealed class ProjectMembershipState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The email address of the user to add to the project.
        /// </summary>
        [Input("email")]
        public Input<string>? Email { get; set; }

        /// <summary>
        /// The name of the user.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("organizationPrivateKey")]
        private Input<string>? _organizationPrivateKey;

        /// <summary>
        /// Organization private key to authenticate the call.
        /// </summary>
        public Input<string>? OrganizationPrivateKey
        {
            get => _organizationPrivateKey;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _organizationPrivateKey = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        [Input("organizationPublicKey")]
        private Input<string>? _organizationPublicKey;

        /// <summary>
        /// Organization public key to authenticate the call.
        /// </summary>
        public Input<string>? OrganizationPublicKey
        {
            get => _organizationPublicKey;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _organizationPublicKey = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        /// <summary>
        /// The ID of the project.
        /// </summary>
        [Input("projectId")]
        public Input<string>? ProjectId { get; set; }

        /// <summary>
        /// The role to assign to the user. Valid values are: OWNER, ADMIN, MEMBER, VIEWER, NONE.
        /// </summary>
        [Input("role")]
        public Input<string>? Role { get; set; }

        /// <summary>
        /// The unique identifier of the user.
        /// </summary>
        [Input("userId")]
        public Input<string>? UserId { get; set; }

        public ProjectMembershipState()
        {
        }
        public static new ProjectMembershipState Empty => new ProjectMembershipState();
    }
}
