# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from .. import _utilities

import types

__config__ = pulumi.Config('langfuse')


class _ExportableConfig(types.ModuleType):
    @_builtins.property
    def admin_api_key(self) -> Optional[str]:
        """
        Admin API key. Only needed when managing organizations. Can also come from LANGFUSE_ADMIN_KEY.
        """
        return __config__.get('adminApiKey')

    @_builtins.property
    def host(self) -> Optional[str]:
        """
        Base URI of the Langfuse instance (defaults to https://app.langfuse.com).
        """
        return __config__.get('host')

    @_builtins.property
    def tls_server_name(self) -> Optional[str]:
        """
        Hostname to verify the TLS certificate against, also sent as the SNI value. Set this when the instance is reached through a port forward or tunnel, where the host above (typically localhost) cannot match the certificate. Certificate verification remains enabled.
        """
        return __config__.get('tlsServerName')

