// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

// Export members:
export { LlmConnectionArgs, LlmConnectionState } from "./llmConnection";
export type LlmConnection = import("./llmConnection").LlmConnection;
export const LlmConnection: typeof import("./llmConnection").LlmConnection = null as any;
utilities.lazyLoad(exports, ["LlmConnection"], () => require("./llmConnection"));

export { OrganizationArgs, OrganizationState } from "./organization";
export type Organization = import("./organization").Organization;
export const Organization: typeof import("./organization").Organization = null as any;
utilities.lazyLoad(exports, ["Organization"], () => require("./organization"));

export { OrganizationApiKeyArgs, OrganizationApiKeyState } from "./organizationApiKey";
export type OrganizationApiKey = import("./organizationApiKey").OrganizationApiKey;
export const OrganizationApiKey: typeof import("./organizationApiKey").OrganizationApiKey = null as any;
utilities.lazyLoad(exports, ["OrganizationApiKey"], () => require("./organizationApiKey"));

export { OrganizationMembershipArgs, OrganizationMembershipState } from "./organizationMembership";
export type OrganizationMembership = import("./organizationMembership").OrganizationMembership;
export const OrganizationMembership: typeof import("./organizationMembership").OrganizationMembership = null as any;
utilities.lazyLoad(exports, ["OrganizationMembership"], () => require("./organizationMembership"));

export { ProjectArgs, ProjectState } from "./project";
export type Project = import("./project").Project;
export const Project: typeof import("./project").Project = null as any;
utilities.lazyLoad(exports, ["Project"], () => require("./project"));

export { ProjectApiKeyArgs, ProjectApiKeyState } from "./projectApiKey";
export type ProjectApiKey = import("./projectApiKey").ProjectApiKey;
export const ProjectApiKey: typeof import("./projectApiKey").ProjectApiKey = null as any;
utilities.lazyLoad(exports, ["ProjectApiKey"], () => require("./projectApiKey"));

export { ProjectMembershipArgs, ProjectMembershipState } from "./projectMembership";
export type ProjectMembership = import("./projectMembership").ProjectMembership;
export const ProjectMembership: typeof import("./projectMembership").ProjectMembership = null as any;
utilities.lazyLoad(exports, ["ProjectMembership"], () => require("./projectMembership"));

export * from "./provider";
import { Provider } from "./provider";


// Export sub-modules:
import * as config from "./config";

export {
    config,
};

const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "langfuse:index/llmConnection:LlmConnection":
                return new LlmConnection(name, <any>undefined, { urn })
            case "langfuse:index/organization:Organization":
                return new Organization(name, <any>undefined, { urn })
            case "langfuse:index/organizationApiKey:OrganizationApiKey":
                return new OrganizationApiKey(name, <any>undefined, { urn })
            case "langfuse:index/organizationMembership:OrganizationMembership":
                return new OrganizationMembership(name, <any>undefined, { urn })
            case "langfuse:index/project:Project":
                return new Project(name, <any>undefined, { urn })
            case "langfuse:index/projectApiKey:ProjectApiKey":
                return new ProjectApiKey(name, <any>undefined, { urn })
            case "langfuse:index/projectMembership:ProjectMembership":
                return new ProjectMembership(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("langfuse", "index/llmConnection", _module)
pulumi.runtime.registerResourceModule("langfuse", "index/organization", _module)
pulumi.runtime.registerResourceModule("langfuse", "index/organizationApiKey", _module)
pulumi.runtime.registerResourceModule("langfuse", "index/organizationMembership", _module)
pulumi.runtime.registerResourceModule("langfuse", "index/project", _module)
pulumi.runtime.registerResourceModule("langfuse", "index/projectApiKey", _module)
pulumi.runtime.registerResourceModule("langfuse", "index/projectMembership", _module)
pulumi.runtime.registerResourcePackage("langfuse", {
    version: utilities.getVersion(),
    constructProvider: (name: string, type: string, urn: string): pulumi.ProviderResource => {
        if (type !== "pulumi:providers:langfuse") {
            throw new Error(`unknown provider type ${type}`);
        }
        return new Provider(name, <any>undefined, { urn });
    },
});
