// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class LlmConnection extends pulumi.CustomResource {
    /**
     * Get an existing LlmConnection resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: LlmConnectionState, opts?: pulumi.CustomResourceOptions): LlmConnection {
        return new LlmConnection(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'langfuse:index/llmConnection:LlmConnection';

    /**
     * Returns true if the given object is an instance of LlmConnection.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is LlmConnection {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === LlmConnection.__pulumiType;
    }

    /**
     * The LLM service type. Valid values: anthropic, openai, azure, bedrock, google-vertex-ai, google-ai-studio.
     */
    declare public readonly adapter: pulumi.Output<string>;
    /**
     * Optional base URL override for the LLM provider API.
     */
    declare public readonly baseUrl: pulumi.Output<string | undefined>;
    /**
     * Adapter-specific configuration as a JSON string. Required for bedrock (`{"region": "<aws-region>"}`), optional for openai (`{"useResponsesApi": <bool>}`) and google-vertex-ai (`{"location": "<gcp-location>"}`), and unsupported for other adapters. Computed, because the API returns any config the connection holds and offers no way to unset one.
     */
    declare public readonly config: pulumi.Output<string>;
    /**
     * Optional list of custom model identifiers.
     */
    declare public readonly customModels: pulumi.Output<string[] | undefined>;
    /**
     * Optional map of additional HTTP headers for LLM API requests.
     */
    declare public readonly extraHeaders: pulumi.Output<{[key: string]: string} | undefined>;
    /**
     * The project public key used to authenticate API calls.
     */
    declare public readonly projectPublicKey: pulumi.Output<string>;
    /**
     * The project secret key used to authenticate API calls.
     */
    declare public readonly projectSecretKey: pulumi.Output<string>;
    /**
     * The unique name identifying this LLM connection within the project. Changing this value destroys and recreates the resource, as the provider name is the upsert key.
     */
    declare public readonly providerName: pulumi.Output<string>;
    /**
     * The API authentication key for the LLM provider.
     */
    declare public readonly secretKey: pulumi.Output<string>;
    /**
     * Whether to include default models. Defaults to true if not set.
     */
    declare public readonly withDefaultModels: pulumi.Output<boolean>;

    /**
     * Create a LlmConnection resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: LlmConnectionArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: LlmConnectionArgs | LlmConnectionState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as LlmConnectionState | undefined;
            resourceInputs["adapter"] = state?.adapter;
            resourceInputs["baseUrl"] = state?.baseUrl;
            resourceInputs["config"] = state?.config;
            resourceInputs["customModels"] = state?.customModels;
            resourceInputs["extraHeaders"] = state?.extraHeaders;
            resourceInputs["projectPublicKey"] = state?.projectPublicKey;
            resourceInputs["projectSecretKey"] = state?.projectSecretKey;
            resourceInputs["providerName"] = state?.providerName;
            resourceInputs["secretKey"] = state?.secretKey;
            resourceInputs["withDefaultModels"] = state?.withDefaultModels;
        } else {
            const args = argsOrState as LlmConnectionArgs | undefined;
            if (args?.adapter === undefined && !opts.urn) {
                throw new Error("Missing required property 'adapter'");
            }
            if (args?.projectPublicKey === undefined && !opts.urn) {
                throw new Error("Missing required property 'projectPublicKey'");
            }
            if (args?.projectSecretKey === undefined && !opts.urn) {
                throw new Error("Missing required property 'projectSecretKey'");
            }
            if (args?.providerName === undefined && !opts.urn) {
                throw new Error("Missing required property 'providerName'");
            }
            if (args?.secretKey === undefined && !opts.urn) {
                throw new Error("Missing required property 'secretKey'");
            }
            resourceInputs["adapter"] = args?.adapter;
            resourceInputs["baseUrl"] = args?.baseUrl;
            resourceInputs["config"] = args?.config;
            resourceInputs["customModels"] = args?.customModels;
            resourceInputs["extraHeaders"] = args?.extraHeaders ? pulumi.secret(args.extraHeaders) : undefined;
            resourceInputs["projectPublicKey"] = args?.projectPublicKey ? pulumi.secret(args.projectPublicKey) : undefined;
            resourceInputs["projectSecretKey"] = args?.projectSecretKey ? pulumi.secret(args.projectSecretKey) : undefined;
            resourceInputs["providerName"] = args?.providerName;
            resourceInputs["secretKey"] = args?.secretKey ? pulumi.secret(args.secretKey) : undefined;
            resourceInputs["withDefaultModels"] = args?.withDefaultModels;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["extraHeaders", "projectPublicKey", "projectSecretKey", "secretKey"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(LlmConnection.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering LlmConnection resources.
 */
export interface LlmConnectionState {
    /**
     * The LLM service type. Valid values: anthropic, openai, azure, bedrock, google-vertex-ai, google-ai-studio.
     */
    adapter?: pulumi.Input<string | undefined>;
    /**
     * Optional base URL override for the LLM provider API.
     */
    baseUrl?: pulumi.Input<string | undefined>;
    /**
     * Adapter-specific configuration as a JSON string. Required for bedrock (`{"region": "<aws-region>"}`), optional for openai (`{"useResponsesApi": <bool>}`) and google-vertex-ai (`{"location": "<gcp-location>"}`), and unsupported for other adapters. Computed, because the API returns any config the connection holds and offers no way to unset one.
     */
    config?: pulumi.Input<string | undefined>;
    /**
     * Optional list of custom model identifiers.
     */
    customModels?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * Optional map of additional HTTP headers for LLM API requests.
     */
    extraHeaders?: pulumi.Input<{[key: string]: pulumi.Input<string>} | undefined>;
    /**
     * The project public key used to authenticate API calls.
     */
    projectPublicKey?: pulumi.Input<string | undefined>;
    /**
     * The project secret key used to authenticate API calls.
     */
    projectSecretKey?: pulumi.Input<string | undefined>;
    /**
     * The unique name identifying this LLM connection within the project. Changing this value destroys and recreates the resource, as the provider name is the upsert key.
     */
    providerName?: pulumi.Input<string | undefined>;
    /**
     * The API authentication key for the LLM provider.
     */
    secretKey?: pulumi.Input<string | undefined>;
    /**
     * Whether to include default models. Defaults to true if not set.
     */
    withDefaultModels?: pulumi.Input<boolean | undefined>;
}

/**
 * The set of arguments for constructing a LlmConnection resource.
 */
export interface LlmConnectionArgs {
    /**
     * The LLM service type. Valid values: anthropic, openai, azure, bedrock, google-vertex-ai, google-ai-studio.
     */
    adapter: pulumi.Input<string>;
    /**
     * Optional base URL override for the LLM provider API.
     */
    baseUrl?: pulumi.Input<string | undefined>;
    /**
     * Adapter-specific configuration as a JSON string. Required for bedrock (`{"region": "<aws-region>"}`), optional for openai (`{"useResponsesApi": <bool>}`) and google-vertex-ai (`{"location": "<gcp-location>"}`), and unsupported for other adapters. Computed, because the API returns any config the connection holds and offers no way to unset one.
     */
    config?: pulumi.Input<string | undefined>;
    /**
     * Optional list of custom model identifiers.
     */
    customModels?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * Optional map of additional HTTP headers for LLM API requests.
     */
    extraHeaders?: pulumi.Input<{[key: string]: pulumi.Input<string>} | undefined>;
    /**
     * The project public key used to authenticate API calls.
     */
    projectPublicKey: pulumi.Input<string>;
    /**
     * The project secret key used to authenticate API calls.
     */
    projectSecretKey: pulumi.Input<string>;
    /**
     * The unique name identifying this LLM connection within the project. Changing this value destroys and recreates the resource, as the provider name is the upsert key.
     */
    providerName: pulumi.Input<string>;
    /**
     * The API authentication key for the LLM provider.
     */
    secretKey: pulumi.Input<string>;
    /**
     * Whether to include default models. Defaults to true if not set.
     */
    withDefaultModels?: pulumi.Input<boolean | undefined>;
}
