// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class OrganizationApiKey extends pulumi.CustomResource {
    /**
     * Get an existing OrganizationApiKey resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: OrganizationApiKeyState, opts?: pulumi.CustomResourceOptions): OrganizationApiKey {
        return new OrganizationApiKey(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'langfuse:index/organizationApiKey:OrganizationApiKey';

    /**
     * Returns true if the given object is an instance of OrganizationApiKey.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is OrganizationApiKey {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === OrganizationApiKey.__pulumiType;
    }

    /**
     * The Langfuse organization the key belongs to.
     */
    declare public readonly organizationId: pulumi.Output<string>;
    /**
     * The public value of the API key (only returned at creation time).
     */
    declare public /*out*/ readonly publicKey: pulumi.Output<string>;
    /**
     * The secret value of the API key (only returned at creation time).
     */
    declare public /*out*/ readonly secretKey: pulumi.Output<string>;

    /**
     * Create a OrganizationApiKey resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: OrganizationApiKeyArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: OrganizationApiKeyArgs | OrganizationApiKeyState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as OrganizationApiKeyState | undefined;
            resourceInputs["organizationId"] = state?.organizationId;
            resourceInputs["publicKey"] = state?.publicKey;
            resourceInputs["secretKey"] = state?.secretKey;
        } else {
            const args = argsOrState as OrganizationApiKeyArgs | undefined;
            if (args?.organizationId === undefined && !opts.urn) {
                throw new Error("Missing required property 'organizationId'");
            }
            resourceInputs["organizationId"] = args?.organizationId;
            resourceInputs["publicKey"] = undefined /*out*/;
            resourceInputs["secretKey"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["publicKey", "secretKey"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(OrganizationApiKey.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering OrganizationApiKey resources.
 */
export interface OrganizationApiKeyState {
    /**
     * The Langfuse organization the key belongs to.
     */
    organizationId?: pulumi.Input<string | undefined>;
    /**
     * The public value of the API key (only returned at creation time).
     */
    publicKey?: pulumi.Input<string | undefined>;
    /**
     * The secret value of the API key (only returned at creation time).
     */
    secretKey?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a OrganizationApiKey resource.
 */
export interface OrganizationApiKeyArgs {
    /**
     * The Langfuse organization the key belongs to.
     */
    organizationId: pulumi.Input<string>;
}
