// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class OrganizationMembership extends pulumi.CustomResource {
    /**
     * Get an existing OrganizationMembership resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: OrganizationMembershipState, opts?: pulumi.CustomResourceOptions): OrganizationMembership {
        return new OrganizationMembership(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'langfuse:index/organizationMembership:OrganizationMembership';

    /**
     * Returns true if the given object is an instance of OrganizationMembership.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is OrganizationMembership {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === OrganizationMembership.__pulumiType;
    }

    /**
     * The email address of the user to invite.
     */
    declare public readonly email: pulumi.Output<string>;
    /**
     * Organization private key to authenticate the call.
     */
    declare public readonly organizationPrivateKey: pulumi.Output<string>;
    /**
     * Organization public key to authenticate the call.
     */
    declare public readonly organizationPublicKey: pulumi.Output<string>;
    /**
     * The role to assign to the user. Valid values are: ADMIN, MEMBER, VIEWER.
     */
    declare public readonly role: pulumi.Output<string>;
    /**
     * The status of the membership invitation.
     */
    declare public /*out*/ readonly status: pulumi.Output<string>;
    /**
     * The unique identifier of the user.
     */
    declare public /*out*/ readonly userId: pulumi.Output<string>;
    /**
     * The username of the user.
     */
    declare public /*out*/ readonly username: pulumi.Output<string>;

    /**
     * Create a OrganizationMembership resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: OrganizationMembershipArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: OrganizationMembershipArgs | OrganizationMembershipState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as OrganizationMembershipState | undefined;
            resourceInputs["email"] = state?.email;
            resourceInputs["organizationPrivateKey"] = state?.organizationPrivateKey;
            resourceInputs["organizationPublicKey"] = state?.organizationPublicKey;
            resourceInputs["role"] = state?.role;
            resourceInputs["status"] = state?.status;
            resourceInputs["userId"] = state?.userId;
            resourceInputs["username"] = state?.username;
        } else {
            const args = argsOrState as OrganizationMembershipArgs | undefined;
            if (args?.email === undefined && !opts.urn) {
                throw new Error("Missing required property 'email'");
            }
            if (args?.organizationPrivateKey === undefined && !opts.urn) {
                throw new Error("Missing required property 'organizationPrivateKey'");
            }
            if (args?.organizationPublicKey === undefined && !opts.urn) {
                throw new Error("Missing required property 'organizationPublicKey'");
            }
            if (args?.role === undefined && !opts.urn) {
                throw new Error("Missing required property 'role'");
            }
            resourceInputs["email"] = args?.email;
            resourceInputs["organizationPrivateKey"] = args?.organizationPrivateKey ? pulumi.secret(args.organizationPrivateKey) : undefined;
            resourceInputs["organizationPublicKey"] = args?.organizationPublicKey ? pulumi.secret(args.organizationPublicKey) : undefined;
            resourceInputs["role"] = args?.role;
            resourceInputs["status"] = undefined /*out*/;
            resourceInputs["userId"] = undefined /*out*/;
            resourceInputs["username"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["organizationPrivateKey", "organizationPublicKey"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(OrganizationMembership.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering OrganizationMembership resources.
 */
export interface OrganizationMembershipState {
    /**
     * The email address of the user to invite.
     */
    email?: pulumi.Input<string | undefined>;
    /**
     * Organization private key to authenticate the call.
     */
    organizationPrivateKey?: pulumi.Input<string | undefined>;
    /**
     * Organization public key to authenticate the call.
     */
    organizationPublicKey?: pulumi.Input<string | undefined>;
    /**
     * The role to assign to the user. Valid values are: ADMIN, MEMBER, VIEWER.
     */
    role?: pulumi.Input<string | undefined>;
    /**
     * The status of the membership invitation.
     */
    status?: pulumi.Input<string | undefined>;
    /**
     * The unique identifier of the user.
     */
    userId?: pulumi.Input<string | undefined>;
    /**
     * The username of the user.
     */
    username?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a OrganizationMembership resource.
 */
export interface OrganizationMembershipArgs {
    /**
     * The email address of the user to invite.
     */
    email: pulumi.Input<string>;
    /**
     * Organization private key to authenticate the call.
     */
    organizationPrivateKey: pulumi.Input<string>;
    /**
     * Organization public key to authenticate the call.
     */
    organizationPublicKey: pulumi.Input<string>;
    /**
     * The role to assign to the user. Valid values are: ADMIN, MEMBER, VIEWER.
     */
    role: pulumi.Input<string>;
}
