// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class ProjectMembership extends pulumi.CustomResource {
    /**
     * Get an existing ProjectMembership resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: ProjectMembershipState, opts?: pulumi.CustomResourceOptions): ProjectMembership {
        return new ProjectMembership(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'langfuse:index/projectMembership:ProjectMembership';

    /**
     * Returns true if the given object is an instance of ProjectMembership.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is ProjectMembership {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === ProjectMembership.__pulumiType;
    }

    /**
     * The email address of the user to add to the project.
     */
    declare public readonly email: pulumi.Output<string>;
    /**
     * The name of the user.
     */
    declare public /*out*/ readonly name: pulumi.Output<string>;
    /**
     * Organization private key to authenticate the call.
     */
    declare public readonly organizationPrivateKey: pulumi.Output<string>;
    /**
     * Organization public key to authenticate the call.
     */
    declare public readonly organizationPublicKey: pulumi.Output<string>;
    /**
     * The ID of the project.
     */
    declare public readonly projectId: pulumi.Output<string>;
    /**
     * The role to assign to the user. Valid values are: OWNER, ADMIN, MEMBER, VIEWER, NONE.
     */
    declare public readonly role: pulumi.Output<string>;
    /**
     * The unique identifier of the user.
     */
    declare public /*out*/ readonly userId: pulumi.Output<string>;

    /**
     * Create a ProjectMembership resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ProjectMembershipArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: ProjectMembershipArgs | ProjectMembershipState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as ProjectMembershipState | undefined;
            resourceInputs["email"] = state?.email;
            resourceInputs["name"] = state?.name;
            resourceInputs["organizationPrivateKey"] = state?.organizationPrivateKey;
            resourceInputs["organizationPublicKey"] = state?.organizationPublicKey;
            resourceInputs["projectId"] = state?.projectId;
            resourceInputs["role"] = state?.role;
            resourceInputs["userId"] = state?.userId;
        } else {
            const args = argsOrState as ProjectMembershipArgs | undefined;
            if (args?.email === undefined && !opts.urn) {
                throw new Error("Missing required property 'email'");
            }
            if (args?.organizationPrivateKey === undefined && !opts.urn) {
                throw new Error("Missing required property 'organizationPrivateKey'");
            }
            if (args?.organizationPublicKey === undefined && !opts.urn) {
                throw new Error("Missing required property 'organizationPublicKey'");
            }
            if (args?.projectId === undefined && !opts.urn) {
                throw new Error("Missing required property 'projectId'");
            }
            if (args?.role === undefined && !opts.urn) {
                throw new Error("Missing required property 'role'");
            }
            resourceInputs["email"] = args?.email;
            resourceInputs["organizationPrivateKey"] = args?.organizationPrivateKey ? pulumi.secret(args.organizationPrivateKey) : undefined;
            resourceInputs["organizationPublicKey"] = args?.organizationPublicKey ? pulumi.secret(args.organizationPublicKey) : undefined;
            resourceInputs["projectId"] = args?.projectId;
            resourceInputs["role"] = args?.role;
            resourceInputs["name"] = undefined /*out*/;
            resourceInputs["userId"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["organizationPrivateKey", "organizationPublicKey"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(ProjectMembership.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering ProjectMembership resources.
 */
export interface ProjectMembershipState {
    /**
     * The email address of the user to add to the project.
     */
    email?: pulumi.Input<string | undefined>;
    /**
     * The name of the user.
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * Organization private key to authenticate the call.
     */
    organizationPrivateKey?: pulumi.Input<string | undefined>;
    /**
     * Organization public key to authenticate the call.
     */
    organizationPublicKey?: pulumi.Input<string | undefined>;
    /**
     * The ID of the project.
     */
    projectId?: pulumi.Input<string | undefined>;
    /**
     * The role to assign to the user. Valid values are: OWNER, ADMIN, MEMBER, VIEWER, NONE.
     */
    role?: pulumi.Input<string | undefined>;
    /**
     * The unique identifier of the user.
     */
    userId?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a ProjectMembership resource.
 */
export interface ProjectMembershipArgs {
    /**
     * The email address of the user to add to the project.
     */
    email: pulumi.Input<string>;
    /**
     * Organization private key to authenticate the call.
     */
    organizationPrivateKey: pulumi.Input<string>;
    /**
     * Organization public key to authenticate the call.
     */
    organizationPublicKey: pulumi.Input<string>;
    /**
     * The ID of the project.
     */
    projectId: pulumi.Input<string>;
    /**
     * The role to assign to the user. Valid values are: OWNER, ADMIN, MEMBER, VIEWER, NONE.
     */
    role: pulumi.Input<string>;
}
