// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class Project extends pulumi.CustomResource {
    /**
     * Get an existing Project resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: ProjectState, opts?: pulumi.CustomResourceOptions): Project {
        return new Project(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'langfuse:index/project:Project';

    /**
     * Returns true if the given object is an instance of Project.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Project {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Project.__pulumiType;
    }

    /**
     * Metadata for the project as key-value pairs.
     */
    declare public readonly metadata: pulumi.Output<{[key: string]: string} | undefined>;
    /**
     * The display name of the project.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * The ID of the organization that owns this project.
     */
    declare public readonly organizationId: pulumi.Output<string>;
    /**
     * Organization private key to authenticate the call.
     */
    declare public readonly organizationPrivateKey: pulumi.Output<string>;
    /**
     * Organization public key to authenticate the call.
     */
    declare public readonly organizationPublicKey: pulumi.Output<string>;
    /**
     * The retention period for the project in days. If not set, or set with a value of 0, data will be stored indefinitely.
     */
    declare public readonly retentionDays: pulumi.Output<number>;

    /**
     * Create a Project resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ProjectArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: ProjectArgs | ProjectState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as ProjectState | undefined;
            resourceInputs["metadata"] = state?.metadata;
            resourceInputs["name"] = state?.name;
            resourceInputs["organizationId"] = state?.organizationId;
            resourceInputs["organizationPrivateKey"] = state?.organizationPrivateKey;
            resourceInputs["organizationPublicKey"] = state?.organizationPublicKey;
            resourceInputs["retentionDays"] = state?.retentionDays;
        } else {
            const args = argsOrState as ProjectArgs | undefined;
            if (args?.organizationId === undefined && !opts.urn) {
                throw new Error("Missing required property 'organizationId'");
            }
            if (args?.organizationPrivateKey === undefined && !opts.urn) {
                throw new Error("Missing required property 'organizationPrivateKey'");
            }
            if (args?.organizationPublicKey === undefined && !opts.urn) {
                throw new Error("Missing required property 'organizationPublicKey'");
            }
            resourceInputs["metadata"] = args?.metadata;
            resourceInputs["name"] = args?.name;
            resourceInputs["organizationId"] = args?.organizationId;
            resourceInputs["organizationPrivateKey"] = args?.organizationPrivateKey ? pulumi.secret(args.organizationPrivateKey) : undefined;
            resourceInputs["organizationPublicKey"] = args?.organizationPublicKey ? pulumi.secret(args.organizationPublicKey) : undefined;
            resourceInputs["retentionDays"] = args?.retentionDays;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["organizationPrivateKey", "organizationPublicKey"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(Project.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering Project resources.
 */
export interface ProjectState {
    /**
     * Metadata for the project as key-value pairs.
     */
    metadata?: pulumi.Input<{[key: string]: pulumi.Input<string>} | undefined>;
    /**
     * The display name of the project.
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * The ID of the organization that owns this project.
     */
    organizationId?: pulumi.Input<string | undefined>;
    /**
     * Organization private key to authenticate the call.
     */
    organizationPrivateKey?: pulumi.Input<string | undefined>;
    /**
     * Organization public key to authenticate the call.
     */
    organizationPublicKey?: pulumi.Input<string | undefined>;
    /**
     * The retention period for the project in days. If not set, or set with a value of 0, data will be stored indefinitely.
     */
    retentionDays?: pulumi.Input<number | undefined>;
}

/**
 * The set of arguments for constructing a Project resource.
 */
export interface ProjectArgs {
    /**
     * Metadata for the project as key-value pairs.
     */
    metadata?: pulumi.Input<{[key: string]: pulumi.Input<string>} | undefined>;
    /**
     * The display name of the project.
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * The ID of the organization that owns this project.
     */
    organizationId: pulumi.Input<string>;
    /**
     * Organization private key to authenticate the call.
     */
    organizationPrivateKey: pulumi.Input<string>;
    /**
     * Organization public key to authenticate the call.
     */
    organizationPublicKey: pulumi.Input<string>;
    /**
     * The retention period for the project in days. If not set, or set with a value of 0, data will be stored indefinitely.
     */
    retentionDays?: pulumi.Input<number | undefined>;
}
