// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class ProjectApiKey extends pulumi.CustomResource {
    /**
     * Get an existing ProjectApiKey resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: ProjectApiKeyState, opts?: pulumi.CustomResourceOptions): ProjectApiKey {
        return new ProjectApiKey(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'langfuse:index/projectApiKey:ProjectApiKey';

    /**
     * Returns true if the given object is an instance of ProjectApiKey.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is ProjectApiKey {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === ProjectApiKey.__pulumiType;
    }

    /**
     * Optional note for the API key (POST /api/public/projects/{projectId}/apiKeys). Because the Langfuse public API only accepts a note at creation time, changing this attribute forces replacement: the old key is deleted and a new one is created (new id and credentials).
     */
    declare public readonly note: pulumi.Output<string | undefined>;
    /**
     * Organization private key to authenticate the call.
     */
    declare public readonly organizationPrivateKey: pulumi.Output<string>;
    /**
     * Organization public key to authenticate the call.
     */
    declare public readonly organizationPublicKey: pulumi.Output<string>;
    /**
     * The ID of the project the key belongs to.
     */
    declare public readonly projectId: pulumi.Output<string>;
    /**
     * The public value of the API key (only returned at creation time).
     */
    declare public /*out*/ readonly publicKey: pulumi.Output<string>;
    /**
     * The secret value of the API key (only returned at creation time).
     */
    declare public /*out*/ readonly secretKey: pulumi.Output<string>;

    /**
     * Create a ProjectApiKey resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ProjectApiKeyArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: ProjectApiKeyArgs | ProjectApiKeyState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as ProjectApiKeyState | undefined;
            resourceInputs["note"] = state?.note;
            resourceInputs["organizationPrivateKey"] = state?.organizationPrivateKey;
            resourceInputs["organizationPublicKey"] = state?.organizationPublicKey;
            resourceInputs["projectId"] = state?.projectId;
            resourceInputs["publicKey"] = state?.publicKey;
            resourceInputs["secretKey"] = state?.secretKey;
        } else {
            const args = argsOrState as ProjectApiKeyArgs | undefined;
            if (args?.organizationPrivateKey === undefined && !opts.urn) {
                throw new Error("Missing required property 'organizationPrivateKey'");
            }
            if (args?.organizationPublicKey === undefined && !opts.urn) {
                throw new Error("Missing required property 'organizationPublicKey'");
            }
            if (args?.projectId === undefined && !opts.urn) {
                throw new Error("Missing required property 'projectId'");
            }
            resourceInputs["note"] = args?.note;
            resourceInputs["organizationPrivateKey"] = args?.organizationPrivateKey ? pulumi.secret(args.organizationPrivateKey) : undefined;
            resourceInputs["organizationPublicKey"] = args?.organizationPublicKey;
            resourceInputs["projectId"] = args?.projectId;
            resourceInputs["publicKey"] = undefined /*out*/;
            resourceInputs["secretKey"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["organizationPrivateKey", "publicKey", "secretKey"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(ProjectApiKey.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering ProjectApiKey resources.
 */
export interface ProjectApiKeyState {
    /**
     * Optional note for the API key (POST /api/public/projects/{projectId}/apiKeys). Because the Langfuse public API only accepts a note at creation time, changing this attribute forces replacement: the old key is deleted and a new one is created (new id and credentials).
     */
    note?: pulumi.Input<string | undefined>;
    /**
     * Organization private key to authenticate the call.
     */
    organizationPrivateKey?: pulumi.Input<string | undefined>;
    /**
     * Organization public key to authenticate the call.
     */
    organizationPublicKey?: pulumi.Input<string | undefined>;
    /**
     * The ID of the project the key belongs to.
     */
    projectId?: pulumi.Input<string | undefined>;
    /**
     * The public value of the API key (only returned at creation time).
     */
    publicKey?: pulumi.Input<string | undefined>;
    /**
     * The secret value of the API key (only returned at creation time).
     */
    secretKey?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a ProjectApiKey resource.
 */
export interface ProjectApiKeyArgs {
    /**
     * Optional note for the API key (POST /api/public/projects/{projectId}/apiKeys). Because the Langfuse public API only accepts a note at creation time, changing this attribute forces replacement: the old key is deleted and a new one is created (new id and credentials).
     */
    note?: pulumi.Input<string | undefined>;
    /**
     * Organization private key to authenticate the call.
     */
    organizationPrivateKey: pulumi.Input<string>;
    /**
     * Organization public key to authenticate the call.
     */
    organizationPublicKey: pulumi.Input<string>;
    /**
     * The ID of the project the key belongs to.
     */
    projectId: pulumi.Input<string>;
}
